### ISSUE TITLE
ImportError: No module named idna

### ISSUE THREAD

**Issue by arthall** [oracle/oci-python-sdk#101]
The latest release of Cryptography, version 2.5, stopped requiring idna.  This uncovered an issue in the oci-python-sdk where idna is imported but is not part of the required packages for oci-python-sdk.  If you receive an ImportError for idna, you can resolve it by upgrading to oci>=2.1.5 or running `pip install idna` in your virtual environment containing the oci package.

Here is an snippet from the stack trace for the import error. 
```
File "/lib/python2.7/site-packages/oci/_vendor/urllib3/contrib/pyopenssl.py", line 171, in idna_encode
    import idna
ImportError: No module named idna
```

**Comment by arthall** [comment]
Closing this ticket since the issue has been resolved for a couple of releases now.

**Comment by VictorZhang2014** [comment]
<img width="1107" alt="WX20200623-110344@2x" src="https://user-images.githubusercontent.com/6853884/85356307-3c74a300-b541-11ea-8d08-a25090a0c234.png">

```
pip install idna
```
