### ISSUE TITLE
Announcement Service Not Found

### ISSUE THREAD

**Issue by pastyGRB** [oracle/oci-python-sdk#105]
After updating the OCI package with `pip install oci -U`, I received the error message:

```
Traceback (most recent call last):
  File "/opt/goat/www/cgi-bin/test.py", line 25, in <module>
    announcement_client = oci.announcements_service.AnnouncementClient(config, signer=signer)
AttributeError: 'module' object has no attribute 'announcements_service'
```

I attempted to define an announcements client just like I defined the network client as shown.  The network client was created without issue, but the python script fails at the creation of the announcement client:

```
    network_client = oci.core.VirtualNetworkClient(config, signer=signer)
    announcement_client = oci.announcements_service.AnnouncementClient(config, signer=signer)
```

Is there a known lag between the release of the oci package to git and it's deployment through pip?

**Comment by arthall** [comment]
@pastyGRB what do you get for the version of the oci package?  I don't see anything wrong in the code snippets which makes me think the Python environment is picking up an older version of the oci package.  You can get the version at runtime with `oci.__version__`

PyPI is updated before GitHub so any delays should be on the GitHub side.

**Comment by pastyGRB** [comment]
Great catch!  It looks like pip was pointed to pip3 instead of pip2.

Running the following did the trick:
`pip2 install oci -U`

Thanks for the help and it's good to hear that PyPI is updated first.
