### ISSUE TITLE
examples/stream_example.py not working

### ISSUE THREAD

**Issue by miles182** [oracle/oci-python-sdk#121]
I am using Python 3.7.2. and trying the stream_examples.

When I am trying to publish sample messages this part:

```
key = "key" + str(i)
value = "value" + str(i)
encoded_key = base64.b64encode(key)
encoded_value = base64.b64encode(value)
```

Won't work as I can only base64 encode a bytes object. I can fix it with:

```
        encoded_key = base64.b64encode(key.encode('utf-8'))
        encoded_value = base64.b64encode(value.encode('utf-8'))
```

But it leads to the error:

> Traceback (most recent call last):
>   File "C:/Users/xx/IdeaProjects/cloud-wuzzler-streeaming-agent/agent.py", line 151, in <module>
>     publish_example_messages(stream_client, s_id)
>   File "C:/Users/xx/IdeaProjects/cloud-wuzzler-streeaming-agent/agent.py", line 43, in publish_example_messages
>     put_message_result = client.put_messages(stream_id, messages)
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oci\streaming\stream_client.py", line 666, in put_messages
>     enforce_content_headers=False)
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oci\base_client.py", line 208, in call_api
>     body = self.sanitize_for_serialization(body)
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oci\base_client.py", line 465, in sanitize_for_serialization
>     sanitized_dict[key] = self.sanitize_for_serialization(val, value_declared_type, inner_field_name)
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oci\base_client.py", line 428, in sanitize_for_serialization
>     for sub_obj in obj]
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oci\base_client.py", line 428, in <listcomp>
>     for sub_obj in obj]
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oci\base_client.py", line 465, in sanitize_for_serialization
>     sanitized_dict[key] = self.sanitize_for_serialization(val, value_declared_type, inner_field_name)
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oci\base_client.py", line 417, in sanitize_for_serialization
>     self.raise_type_error_serializing_model(field_name, obj, declared_type)
>   File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\oci\base_client.py", line 473, in raise_type_error_serializing_model
>     raise TypeError('Field {} with value {} was expected to be of type {} but was of type {}'.format(field_name, str(obj), declared_type, type(obj).__name__))
> **TypeError: Field messages[*].key with value b'a2V5MA==' was expected to be of type str but was of type bytes**

It looks like sanitize_for_serialization in base_client does not allow bytes as type, but then how can we send a base64 encoded string?

**Comment by arthall** [comment]
Thank you for bringing this to our attention.  

The baseclient doesn't allow bytes in this case, because the API specifies the values as string.  https://docs.cloud.oracle.com/iaas/api/#/en/streaming/20180418/datatypes/PutMessagesDetailsEntry

I've tested the following changes in Python 2.7.12, 3.5.1 and 3.7.2 and they work in all three environments.  

First, I imported encode and decode from the codecs package.

```
from codecs import encode, decode
```

Then changed the encoding of the key and message to 

```
        encoded_key = encode(key.encode(), "base-64").decode().strip()
        encoded_value = encode(value.encode(), "base-64").decode().strip()
```

and changed the reading of the messages to 

```
        for message in get_response.data:
            print("{}: {}".format(decode(message.key.encode(), "base64").decode(),
                                  decode(message.value.encode(), "base64").decode()))
```

Not related encodings, but also updated the line where the stream is deleted.

```
client.delete_stream_and_wait_for_state(stream_id, wait_for_states=[oci.streaming.models.StreamSummary.LIFECYCLE_STATE_DELETED])
```

Some of the encoding and decoding isn't required, but it keeps the results consistent between Python 2 and Python 3.  I haven't tried to use unicode in my test, and there may be more steps required in that case.  I'll update the example for the next release.

**Comment by miles182** [comment]
Thanks for the fast response I really appreciate it. I just changed the example using codecs package, that indeed works.

**Comment by arthall** [comment]
The example has been updated with the latest release.  Thanks again @miles182 for pointing out the issue.

**Comment by arthall** [comment]
The solution presented here introduces a bug if the key or value is too long.  See https://github.com/oracle/oci-python-sdk/issues/147.
