### ISSUE TITLE
Consider updating python-dateutil 

### ISSUE THREAD

**Issue by mayanklahiri** [oracle/oci-python-sdk#122]
(Oracle employee here)

python-dateutil is pinned to <=2.7.3

Common packages like Luigi (workflow engine) require >= 2.7.5. This causes a pipenv conflict and an inability to create a package lock file.

All updates for python-dateutil since 2.7.3 seem to be tzdata updates, so this should be a safe change to make.

Suggest pinning to <3 rather than <=2.7.3

**Comment by arthall** [comment]
Hi @mayanklahiri I'll see if there are any issues with changing the pinning for python-dateutil.  If there aren't any blockers, I try to get it changed for the next release.

**Comment by arthall** [comment]
@mayanklahiri, I didn't get this in place in time for this release.  I did get it into the internal preview branch a couple of days ago and it's caused no issues with any of the builds.  I should be able to get it into the release branch this week for release next week.

**Comment by mayanklahiri** [comment]
Thank you @arthall, much appreciated.

**Comment by arthall** [comment]
@mayanklahiri, the change was released today:  https://github.com/oracle/oci-python-sdk/commit/243fc08adccbd1a165ef5142bf86c16832fb6154#diff-2eeaed663bd0d25b7e608891384b7298R36

I'm closing this ticket now, but don't hesitate to reopen it if this change doesn't resolve the issue.
