### ISSUE TITLE
OCI Search Client : Call multiple functions at one go : Suggest best search model with sample example

### ISSUE THREAD

**Issue by rajarams123** [oracle/oci-python-sdk#128]
currently i am coding on search functionality using python SDK
https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/resource_search.html

I need your suggestion to get best model to use to get search results

below is my current code where i am doing two calls 1 ) to get instance data 2 ) get subnet level information
which is using Free Text search
Is there a way i can get both these calls at one go ?
1) call :                 singleInstanceData = compute_client.get_instance(value).data
2) call :                 singleInstanceSubnetDataDict = get_instance_ip_addresses_and_dns_info(compute_client, virtual_network_client, identity_client, value, config)
It is working but a performance hit as i am using Free Text Search
I want both calls to be done at one go.

I used some of the functionality shown here -
https://github.com/oracle/oci-python-sdk/blob/master/examples/get_all_instance_ip_addresses_and_dns_info.py

Below is my code snippet for  reference.

def search(input_text) :
    free_text_search = oci.resource_search.models.FreeTextSearchDetails(text=input_text,
                                                                        type='FreeText',
                                                                        matching_context_type=oci.resource_search.models.SearchDetails.MATCHING_CONTEXT_TYPE_HIGHLIGHTS)
    data = {}
    data['searchresults'] = []
    multiInstanceDataList = []
    singleInstanceDict = {}

    compute_client = oci.core.ComputeClient(config)
    virtual_network_client = oci.core.VirtualNetworkClient(config)
    identity_client = oci.identity.IdentityClient(config)
    account=json.loads(str(identity_client.get_compartment(compartment_id).data)).get('name')
    print account
    instance_Info={}

    for response in oci.pagination.list_call_get_all_results_generator(search_client.search_resources, 'response', free_text_search):
            for resource in response.data.items:
                print("Resource type: {}, Resource name: {}".format(resource.resource_type, resource.identifier))
                data['searchresults'].append({str(resource.resource_type):str(resource.identifier)})

    for iterable in data['searchresults']:
        for key, value in iterable.items():
            print('{}: {}'.format(key, value))
            if key == "Instance":
                singleInstanceData = compute_client.get_instance(value).data
                #print singleInstanceDataJson

                .......
                ........

                singleInstanceSubnetDataDict = get_instance_ip_addresses_and_dns_info(compute_client, virtual_network_client, identity_client, value, config)
                print singleInstanceSubnetDataDict

                
                .........
                .........

                #print singleInstanceDict
                if singleInstanceDict.copy() not in multiInstanceDataList:
                    multiInstanceDataList.append(singleInstanceDict.copy())

    #print("******************************")
    #print(multiInstanceDataList[0].values())
    #print("finalllllll******************************")
    print multiInstanceDataList
    return multiInstanceDataList

**Comment by arthall** [comment]
I'm sorry, but I do not understand what you are requesting so I can't help with providing a better way of doing it.  Please fix the formatting of the snippet above so I tell if all the code is part of the search function.  Please also add a sample output for what you are expecting from the program.

You mention a performance hit because you are using Free Text search, but the example that you reference does not use search.  What advantage are you trying to achieve using search?  You also mention making two calls using Free Text search, but I only see one.  The other two calls do not use search.  What is coming back in the search results?

How is singleInstanceData used?  The example doesn't show this being used.  Since you already have the instance identifier which is used by get_instance_ip_addresses_and_dns_info it maybe possible to skip the call to get_instance.

**Comment by rajarams123** [comment]
#Below is my complete snippet.

import oci,json
from util  import ociconfutil

config = oci.config.from_file(file_location="~/.oci/config", profile_name="DEFAULT")

#config = ociconfutil.setupConfig("mpaasocimt", "us-ashburn-1")
search_client = oci.resource_search.ResourceSearchClient(config)
compartment_id = config["tenancy"]
vcn_info = {}
private_ip_to_public_ip = {}


def load_reserved_public_ips_for_all_compartments(virtual_network_client, identity_client, config):
    compartments = oci.pagination.list_call_get_all_results(
        identity_client.list_compartments,
        config['tenancy']
    ).data
    compartment_ids = [c.id for c in compartments]
    if config['tenancy'] not in compartment_ids:
        compartment_ids.append(config['tenancy'])

    for compartment_id in compartment_ids:
        public_ips = get_reserved_public_ips_for_compartment(virtual_network_client, compartment_id)
        private_ip_to_public_ip_for_compartment = {p.private_ip_id: p for p in public_ips}
        private_ip_to_public_ip.update(private_ip_to_public_ip_for_compartment)

def get_reserved_public_ips_for_compartment(virtual_network_client, compartment_id):
    return oci.pagination.list_call_get_all_results(
        virtual_network_client.list_public_ips,
        'REGION',
        compartment_id
    ).data

def get_subnet_info(virtual_network_client, subnet_id):
    subnet = virtual_network_client.get_subnet(subnet_id).data

    if subnet.vcn_id not in vcn_info:
        vcn_info[subnet.vcn_id] = virtual_network_client.get_vcn(subnet.vcn_id).data

    return subnet

def get_instance_ip_addresses_and_dns_info(compute_client, virtual_network_client, identity_client, instance_id, config):
    instance_info = {
        'private_ips': [],
        'dns_info': [],
        'public_ips': [],
        'subnet' : []
    }

    instance = compute_client.get_instance(instance_id).data

    vnic_attachments = oci.pagination.list_call_get_all_results(
        compute_client.list_vnic_attachments,
        compartment_id=instance.compartment_id,
        instance_id=instance.id
    ).data

    vnics = [virtual_network_client.get_vnic(va.vnic_id).data for va in vnic_attachments]
    subnet_info = {}
    print vnics
    for vnic in vnics:

        if vnic.public_ip:
            instance_info['public_ips'].append(vnic.public_ip)
        print vnic.subnet_id
        print subnet_info
        if vnic.subnet_id not in subnet_info:
            subnet_info[vnic.subnet_id] = get_subnet_info(virtual_network_client, vnic.subnet_id)
            instance_info['subnet'].append(subnet_info[vnic.subnet_id])

        private_ips_for_vnic = oci.pagination.list_call_get_all_results(
            virtual_network_client.list_private_ips,
            vnic_id=vnic.id
        ).data

        for private_ip in private_ips_for_vnic:
            instance_info['private_ips'].append(private_ip.ip_address)

            subnet = subnet_info[private_ip.subnet_id]  # Could also use vnic_id rather than private_ip.subnet_id
            vcn = vcn_info[subnet.vcn_id]

            if subnet.dns_label and vcn.dns_label and private_ip.hostname_label:
                instance_info['dns_info'].append(
                    '{}.{}.{}.oraclevcn.com'.format(private_ip.hostname_label, subnet.dns_label, vcn.dns_label)
                )

            if not private_ip_to_public_ip:
                load_reserved_public_ips_for_all_compartments(virtual_network_client, identity_client, config)

            if private_ip.id in private_ip_to_public_ip:  # This is (F1)
                print('Found public IP mapping for private IP in list. Public IP details: {}'.format(private_ip_to_public_ip[private_ip.id]))

            try:
                public_ip = virtual_network_client.get_public_ip_by_private_ip_id(
                    oci.core.models.GetPublicIpByPrivateIpIdDetails(
                        private_ip_id=private_ip.id
                    )
                ).data

                if public_ip.ip_address not in instance_info['public_ips']:
                    instance_info['public_ips'].append(public_ip.ip_address)
            except oci.exceptions.ServiceError as e:
                if e.status == 404:
                    print('No public IP mapping found for private IP: {} ({})'.format(private_ip.id, private_ip.ip_address))
                else:
                    print('Unexpected error when retrieving public IPs: {}'.format(str(e)))

    return instance_info

# My function starts here..
# Takes input of text
def search(input_text) :
    free_text_search = oci.resource_search.models.FreeTextSearchDetails(text=input_text,
                                                                        type='FreeText',
                                                                        matching_context_type=oci.resource_search.models.SearchDetails.MATCHING_CONTEXT_TYPE_HIGHLIGHTS)
    data = {}
    data['searchresults'] = []
    multiInstanceDataList = []
    singleInstanceDict = {}


    compute_client = oci.core.ComputeClient(config)
    virtual_network_client = oci.core.VirtualNetworkClient(config)
    identity_client = oci.identity.IdentityClient(config)
    account=json.loads(str(identity_client.get_compartment(compartment_id).data)).get('name')
    print account
    instance_Info={}


    for response in oci.pagination.list_call_get_all_results_generator(search_client.search_resources, 'response', free_text_search):
            for resource in response.data.items:
                print("Resource type: {}, Resource name: {}".format(resource.resource_type, resource.identifier))
                data['searchresults'].append({str(resource.resource_type):str(resource.identifier)})


    for iterable in data['searchresults']:
        for key, value in iterable.items():
            print('{}: {}'.format(key, value))
            if key == "Instance":
                singleInstanceData = compute_client.get_instance(value).data
                singleInstanceDataJson = json.loads(str(singleInstanceData))
                #print singleInstanceDataJson

                if account != None :
                    singleInstanceDict.update({'IdDomain':account})

                avl_domain = singleInstanceDataJson.get('availability_domain')
                if avl_domain != None :
                    singleInstanceDict.update ({'availability_domain': avl_domain})

                compart_id = singleInstanceDataJson.get('compartment_id')
                if compart_id != None :
                    singleInstanceDict.update({'compartment_id': compart_id})

                lfc_state = singleInstanceDataJson.get('lifecycle_state')
                if lfc_state != None :
                    singleInstanceDict.update({'lifecycle_state': lfc_state})

                region_v = singleInstanceDataJson.get('region')
                if region_v != None :
                    singleInstanceDict.update({'region': region_v})

                time_created_v=singleInstanceDataJson.get('time_created')
                if time_created_v != None :
                    singleInstanceDict.update({'time_created': time_created_v})

                image_id_v = time_created_v=singleInstanceDataJson.get('image_id')
                if image_id_v != None :
                    singleInstanceDict.update({'image_id': image_id_v})

                instance_shape = singleInstanceDataJson.get('shape')
                if instance_shape != None:
                    singleInstanceDict.update({'shape': instance_shape})

                fault_domain_v = singleInstanceDataJson.get('fault_domain')
                if fault_domain_v != None:
                    singleInstanceDict.update({'fault_domain': fault_domain_v})

                display_name_v = singleInstanceDataJson.get('display_name')
                if display_name_v != None:
                    singleInstanceDict.update({'display_name': display_name_v})

                identifier = singleInstanceDataJson.get('id')
                if identifier != None:
                    singleInstanceDict.update({'id': identifier})

                singleInstanceSubnetDataDict = get_instance_ip_addresses_and_dns_info(compute_client, virtual_network_client, identity_client, value, config)
                print singleInstanceSubnetDataDict

                publicIpsList = singleInstanceSubnetDataDict.get('public_ips')
                if len(publicIpsList) > 0:
                    singleInstanceDict.update({'public_ips': str(publicIpsList[0])})

                privateIpsList = singleInstanceSubnetDataDict.get('private_ips')
                if len(privateIpsList) > 0:
                    singleInstanceDict.update({'private_ips': str(privateIpsList[0])})

                subnetList = singleInstanceSubnetDataDict.get('subnet')
                print "SUBNET"
                print subnetList
                if len(subnetList) > 0 :
                    subnetJson=json.loads(str(subnetList[0]))

                    cidr_block_v = subnetJson.get('cidr_block')
                    if cidr_block_v != None:
                        singleInstanceDict.update({'cidr_block': cidr_block_v})

                    virtual_router_mac_v = subnetJson.get('virtual_router_mac')
                    if virtual_router_mac_v != None:
                        singleInstanceDict.update({'virtual_router_mac': virtual_router_mac_v})



                #print singleInstanceDict
                if singleInstanceDict.copy() not in multiInstanceDataList:
                    multiInstanceDataList.append(singleInstanceDict.copy())


    #print("******************************")
    #print(multiInstanceDataList[0].values())
    #print("finalllllll******************************")
    print multiInstanceDataList
    return multiInstanceDataList

**Comment by rajarams123** [comment]
How to call :

search("instance")


It will list all instance data where ever it matches instance text.

**Comment by arthall** [comment]
What is the goal that you are trying to achieve?  The formatting is still making things difficult read, but it looks like you want information on all the instance you have.  Is this correct?  Are you looking for a more efficient way of getting the instances without using search?  If that is the case, you can use list_instances, https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/Instance/ListInstances.

I don't think this is related to the performance issue, but there is no need to convert to JSON and back to get the attributes of the instance.

```
singleInstanceData = compute_client.get_instance(value).data
```

singleInstanceData will contain a populated Instance model, https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.Instance.html#oci.core.models.Instance.  The attributes of the instance can be accessed directly.

```
singleInstanceData.display_name
singleInstanceData.availability_domain
singleInstanceData.id
```

Using the instance object rather than the JSON will save the cost of creating the JSON object and using the get call.  The gathering of the data can be simplified from:
```
compart_id = singleInstanceDataJson.get('compartment_id')
if compart_id != None :
    singleInstanceDict.update({'compartment_id': compart_id})
```
to:
```
if singleInstanceData.compartment_id:
    singleInstanceDict.update({'compartment_id': singleInstanceData.compartment_id})
```

**Comment by rajarams123** [comment]
Thanks for the suggestions. I will do necessary changes and try again

**Comment by rajarams123** [comment]
Is it possible to get singleinstance data and the corresponding subnet information from a single call. Because i am doing separate call to get subnet level info - 
                        singleInstanceSubnetDataDict = get_instance_ip_addresses_and_dns_info(compute_client, virtual_network_client, identity_client, value, config)

**Comment by rajarams123** [comment]
1) What is the goal that you are trying to achieve? - Decrease retrieval time 
2) Yes. I want to all instances data along with subnet information of that instance
3) I am looking for list instances method using python SDK ( my input will be config which contains tenancy, region )

**Comment by arthall** [comment]
1. Without profiling information it's hard to determine where changes can be made to decrease runtime time.  My guess is that replacing the free text search with list_instances() will help.  It might also help to gather all the instances and all the subnets independently and then merging the data programmatically rather than retrieving subnet data for each instance.

2. Thank you.  I now have a better idea of what you are trying to do which leads to 3.

3. There isn't a single API call that will gather all the information you are wanting.  The showoci program may be useful to you.  It uses the Python SDK to report on resources.  See https://github.com/oracle/oci-python-sdk/blob/master/examples/showoci/README.md

**Comment by arthall** [comment]
@rajarams123, Did the showoci program help you?

I'm going to close this issue now, but you can reopen it if there is more to discuss.
