### ISSUE TITLE
Instance Principal - tenancy ocid

### ISSUE THREAD

**Issue by cruepprich** [oracle/oci-python-sdk#130]
When using instance principal authentication, is there a way to fetch the tenancy's OCID, rather than coding it?

**Comment by causey** [comment]
Does the compartmentId of the instance meet your use case or do you actually need the tenancy?  You could do something like `curl -L http://169.254.169.254/opc/v1/instance/compartmentId`

**Comment by arthall** [comment]
If you do need the tenancy OCID, you can get that from the InstancePrincipalsSecurityTokenSigner.

```
signer = oci.auth.signers.InstancePrincipalsSecurityTokenSigner()
tenancy_id = signer.tenancy_id
```

**Comment by arthall** [comment]
@cruepprich I'm closing this ticket, because I think it's been answered.  Please reopen it if you don't have what you need.

**Comment by cruepprich** [comment]
Thank you arthall. That worked for me.
