### ISSUE TITLE
Issue creating image with object storage source

### ISSUE THREAD

**Issue by rosalexander** [oracle/oci-python-sdk#133]
Hi all, I am attempting to create a new image through a file upload through object storage. Hitting an error with the ImageSourceViaObjectStorageTupleDetails source_type I suppose. Heres my following code. Thank you for any help!

```python
>>> img_details = oci.core.models.ImageSourceViaObjectStorageTupleDetails()
>>> img_details
{
  "bucket_name": null,
  "namespace_name": null,
  "object_name": null,
  "source_image_type": null,
  "source_type": "objectStorageTuple"
}
>>> img_details.bucket_name, img_details.namespace_name, img_details.object_name = "bucket_alex", "orasenatdpltoci02", "python_sdk_test_image3_PV.oci"
>>> img_details
{
  "bucket_name": "bucket_alex",
  "namespace_name": "orasenatdpltoci02",
  "object_name": "python_sdk_test_image3_PV.oci",
  "source_image_type": null,
  "source_type": "objectStorageTuple"
}
>>> compute_client
<oci.core.compute_client.ComputeClient object at 0x10c832b70>
>>> compute_client.create_image(img_details)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alros/.local/share/virtualenvs/oci-pv-8fx0y000/lib/python3.7/site-packages/oci/core/compute_client.py", line 546, in create_image
    response_type="Image")
  File "/Users/alros/.local/share/virtualenvs/oci-pv-8fx0y000/lib/python3.7/site-packages/oci/base_client.py", line 225, in call_api
    response = self.request(request)
  File "/Users/alros/.local/share/virtualenvs/oci-pv-8fx0y000/lib/python3.7/site-packages/oci/base_client.py", line 342, in request
    self.raise_service_error(request, response)
  File "/Users/alros/.local/share/virtualenvs/oci-pv-8fx0y000/lib/python3.7/site-packages/oci/base_client.py", line 510, in raise_service_error
    original_request=request)
oci.exceptions.ServiceError: {'opc-request-id': '6BF3E69979FC4CD38434AB4F1047059D/B4344961F32B24EEB0C24383421F928A/821B605102F18930710BDF6046E1B3BE', 'code': 'InvalidParameter', 'message': 'Invalid property name sourceType. Available property names are compartmentId, definedTags, displayName, freeformTags, imageSourceDetails, instanceId, launchMode, launchOptions', 'status': 400}
```

**Comment by ravvitta** [comment]
Please try this code instead. I hope that helps. 

img_details = oci.core.models.ImageSourceViaObjectStorageTupleDetails()
img_details.bucket_name = 'RandomOne'
img_details.namespace_name ='XXXXXXX'
img_details.object_name = 'SampleCustomImage'
img_details.source_image_type =None
img_details.source_type = 'objectStorageTuple'

details = oci.core.models.CreateImageDetails()
details.display_name = 'RaviVittal'
details.compartment_id='ocid1.compartment.oc1..XXXXXXXX'
details.launch_mode='PARAVIRTUALIZED'
details.image_source_details = img_details

client = oci.core.ComputeClient(config)
client.create_image(details)

/Users/ravvitta/repos/UnTocuhedOCIPythonSDK/venv/bin/python /Users/ravvitta/repos/UnTocuhedOCIPythonSDK/oci-python-sdk/examples/SampleCompute1.py

Process finished with exit code 0

**Comment by arthall** [comment]
As @ravvitta demonstrates, create image takes a `oci.core.models.CreateImageDetails` model.  That model has a field named `image_source_details` which is of type `oci.core.models.ImageSourceViaObjectStorageTupleDetails` or `oci.core.models.ImageSourceViaObjectStorageUriDetails`

https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/client/oci.core.ComputeClient.html#oci.core.ComputeClient.create_image

**Comment by arthall** [comment]
@rosalexander, Were you to get your image created?

**Comment by rosalexander** [comment]
Hey @ravvita and @arthall,

Thank you so much for the response. I misunderstood the purpose of ImageSourceViaObjectStorageTupleDetails and that clears things up. Thank you!
