### ISSUE TITLE
ER: showoci example

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle/oci-python-sdk#134]
The "showoci" example is extremely useful! Thank you for providing that code.
Is there a way to print only the non-zero resources on the screen -- i.e., suppress all the zero-count resource lines?

**Comment by adizohar** [comment]
Hi Kumar
The feedback shows the progress of each resource while querying it
I will add additional flag in future version to suppress zero-count resource lines
Thank you for the feedback, appreciate it
Adi.

**Comment by adizohar** [comment]
Hi Kumar
Changing the showoci_service.py to eliminate zero-count resource lines is not an easy tasks
It requires to rewrite the print function which require massive code change

This may be done in future versions.
This item should be close.

**Comment by kumar-dhanagopal** [comment]
Thanks for thinking about this, Adi. I understand that this is a non-trivial change. I'll close the ER.
