### ISSUE TITLE
create stack in resource manager

### ISSUE THREAD

**Issue by T-Srikanth** [oracle/oci-python-sdk#136]
While trying to create a OCI resource manager stack, I'm getting the following error:

 File ".\copy3.py", line 30, in <module>
    Stack.create_stack(create_stack_details=resourcemanager)
  File "C:\Users\sqreddy\ab\bc\env\lib\site-packages\oci\resource_manager\resource_manager_client.py", line 313, in create_stack
    response_type="Stack")
  File "C:\Users\sqreddy\ab\bc\env\lib\site-packages\oci\base_client.py", line 225, in call_api
    response = self.request(request)
  File "C:\Users\sqreddy\ab\bc\env\lib\site-packages\oci\base_client.py", line 336, in request
    raise exceptions.RequestException(e)
oci.exceptions.RequestException: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))

Following is my code sinppet:

config1 = from_file(file_location="")
with open( r"file location",'rb' ) as file: 
	zipContents = file.read() 
	encodedZip = base64.b64encode(zipContents).decode('ascii') 

zipfileupload = oci.resource_manager.models.CreateZipUploadConfigSourceDetails() 
zipfileupload.config_source_type = 'ZIP_UPLOAD' 
#zipfileupload.working_directory = 'MyTerraformScripts' 
zipfileupload.zip_file_base64_encoded = encodedZip 

resourcemanager = oci.resource_manager.models.CreateStackDetails() 
resourcemanager.compartment_id = "ocid1.compartment.oc1..aaaaaaaag5yi4yhckr2m34czfo2jw4e" 
resourcemanager.display_name = "Sample Stack" 
resourcemanager.description = "Sample Stack" 
resourcemanager.config_source = zipfileupload 

Stack = oci.resource_manager.ResourceManagerClient(config1) 
Stack.create_stack(create_stack_details=resourcemanager)

**Comment by ravvitta** [comment]
The code above that I sent you is working for me. Looks like some issues with your ZIP file. Can you email me your Terraform zip file?

**Comment by T-Srikanth** [comment]
Sure, may I know your email id?

**Comment by ravvitta** [comment]
Both the CLI and SDK is working for Srikanth now.

**Comment by T-Srikanth** [comment]
Thank you for your time. It was an issue with the working directory.
