### ISSUE TITLE
AttachVnicDetails on compute client **kwargs error 

### ISSUE THREAD

**Issue by jauyzed** [oracle/oci-python-sdk#138]
Hello,
I'm trying to attach 2nd vnic to instance. I am passing required and optional arguments to the compute object on attach_vnic method. Here is a rough snipped of code

      for instance in all_instances.data:
      instance_id_set = '{}'.format(instance.id)
      if instance_id_set == "ocid1.instance.oc1.phx.abyhqljspz53apnwfoewr4flbon4uqn2tbliogfmwse7x7fic237gymlj4rq":
      		
      		for count in range(number_of_vnics_count):
      			vnic_display_name = str(instance.display_name+"-"+str(count))
      			print(vnic_display_name)
      			c_vnicdets = oci.core.models.CreateVnicDetails(assign_public_ip="false",display_name=vnic_display_name,subnet_id="ocid1.subnet.oc1.phx.aaaaaaaa5zz54ywvi4xvwif2y4famqtkodq245v4i3jupno3bf7fpe6p5owa")
      			a_vnicdets = oci.core.models.AttachVnicDetails(c_vnicdets, display_name=vnic_display_name, instance_id=instance_id_set)

      			compute.attach_vnic(a_vnicdets)

Error Details: 

```
a_vnicdets = oci.core.models.AttachVnicDetails(c_vnicdets, display_name=vnic_display_name, instance_id=instance_id_set)
TypeError: init() takes 1 positional argument but 2 were given
```

I did try wrapping up something like this in one line as well: 

`compute.attach_vnic(oci.core.models.AttachVnicDetails(oci.core.models.CreateVnicDetails(assign_public_ip="false",display_name=vnic_display_name,subnet_id="ocid1.subnet.oc1.phx.aaaaaaaa5zz54ywvi4xvwif2y4famqtkodq245v4i3jupno3bf7fpe6p5owa"), display_name=vnic_display_name, instance_id=instance_id_set))`

Both produce the same TypeError. Can you please suggest what I'm doing wrong? 

Thank you!

**Comment by arthall** [comment]
The error is because all of the parameters to __init__() are kwargs.  The one positional parameter is `self`.  https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.AttachVnicDetails.html#oci.core.models.AttachVnicDetails

setting create_vnic_details= c_vnicdetails when initializing oci.core.models.AttachVnicDetails should get you past the TypeError.

```
for count in range(number_of_vnics_count):
  			vnic_display_name = str(instance.display_name+"-"+str(count))
  			print(vnic_display_name)
  			c_vnicdets = oci.core.models.CreateVnicDetails(assign_public_ip="false",display_name=vnic_display_name,subnet_id="ocid1.subnet.oc1.phx.aaaaaaaa5zz54ywvi4xvwif2y4famqtkodq245v4i3jupno3bf7fpe6p5owa")
  			a_vnicdets = oci.core.models.AttachVnicDetails(create_vnic_details=c_vnicdets, display_name=vnic_display_name, instance_id=instance_id_set)

  			compute.attach_vnic(a_vnicdets)
```

**Comment by ravvitta** [comment]
You can use this code block which I tested if that helps you. 
rv = "ocid1.instance.oc1.XXXXXXX"

cvnic = oci.core.models.CreateVnicDetails()
cvnic.assign_public_ip = False
cvnic.display_name = "SampleVnic"
cvnic.subnet_id = config['subnet_id']
cvnic.skip_source_dest_check = False

avnic = oci.core.models.AttachVnicDetails()
avnic.create_vnic_details = cvnic
avnic.display_name = "SampleVnic"
avnic.instance_id = rv
compute.attach_vnic(avnic)

**Comment by jauyzed** [comment]
@arthall that fixed it.
