### ISSUE TITLE
OCI Python SDK logs parts via logging, parts to stdout. It should use logging only.

### ISSUE THREAD

**Issue by xdobiasl** [oracle/oci-python-sdk#140]
In docs https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/logging.html there is written "The Python SDK uses Python's logging module" when `log_requests` attribute is set to `True`. This is true only partially. Because part of debug details goes directly to STDOUT.

Can you make all debug logs to go via logging and nothing to STDOUT?

Steps to reproduce:

- run this script:
```
#! /usr/bin/env python3

import oci
import logging

config = oci.config.from_file()
config['log_requests'] = True

logging.basicConfig(filename='/tmp/test.log')
client = oci.identity.IdentityClient(config)
client.list_regions()
```

- then in file `/tmp/test.log`, there will be:
```
INFO:oci.base_client.139749236980648:Request: GET https://identity.us-ashburn-1.oraclecloud.com/20160918/regions
DEBUG:oci.base_client.139749236980648:Response status: 200
DEBUG:oci.base_client.139749236980648:python SDK time elapsed for deserializing: 0.0008255462162196636
DEBUG:oci.base_client.139749236980648:time elapsed for request: 0.5240561221726239
```

* and in STDOUT this:
```
send: b'CONNECT identity.us-ashburn-1.oraclecloud.com:443 HTTP/1.0\r\n'
send: b'\r\n'
send: b'GET /20160918/regions HTTP/1.1\r\nuser-agent: Oracle-PythonSDK/2.2.11 (python 3.6.8; x86_64-Linux)\r\naccept-encoding: gzip, deflate\r\naccept: application/json\r\nconnection: keep-alive\r\ncontent-type: application/json\r\nopc-client-info: Oracle-PythonSDK/2.2.11\r\nopc-request-id: 590228C8FE1846F9ACE0E1607876000F\r\ndate: Tue, 25 Jun 2019 17:51:45 GMT\r\nhost: identity.us-ashburn-1.oraclecloud.com\r\nauthorization: Signature algorithm="rsa-sha256",headers="date (request-target) host",keyId="ocid1.tenancy.oc1..aaaaaaaajh6gxgbuudok7odjpwe5wyv2iq74ihhac5lyulxdgrhsssxc4hna/ocid1.user.oc1..aaaaaaaagjc73oavd67jpgocmvcpxxmkgryu5n52kgj6724fabeyslnxfjmq/3d:9d:cf:9a:d3:59:51:96:21:73:62:3f:d8:cc:f8:6a",signature="f3ZwdA37SZKCG8QMIpTBvzdDPscEHZ+A2H8jgBOwVaW1qk+rt+qNRem5Psu2xBP20l2XwrZS421lzlY9yE/kAadGvpsAbRSopWmIz1ymL/4hwYyivKohXF+vA3xdcBi0rE9cL/0nrhOV1rQbaBgaJDBS2LwxPxyBb4PgTPBv6DAQ43Bx5HzYEqHRVXsUA9dgCGij5SsHUID0IUL+KTwaJBq/EDZdaky8aOYJqLGgd1k2GG9vfC8dIcTn7Bk+DaRl7Q9OYo6nEh+Swh1fKLOCBIZfd9igy4bcXD2G0W8l1zeHRo2iqRVC+We04QxH1Xn2BCFnYv2FR+vZLK9ALI0suw==",version="1"\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Tue, 25 Jun 2019 17:51:46 GMT
header: Content-Type: application/json
header: Content-Length: 158
header: Connection: keep-alive
header: opc-request-id: 590228C8FE1846F9ACE0E1607876000F/F02AB495DBEF1EB5284EBA3492F43A75/3455D8E24CB7749C1E9A1EDB58CFAFE5
header: Cache-Control: no-cache, no-store, must-revalidate
header: Content-Encoding: gzip
header: Vary: Accept-Encoding
header: Pragma: no-cache
header: X-Content-Type-Options: nosniff
```

Ideally, all this output should be in test.log.

The reason is that when I'm writing some tests, I don't want debug output in STDOUT, as I want there just test names and results...

**Comment by arthall** [comment]
I don't think this issue is resolvable in the oci package.  The information going to the log is from the oci package. The information going to STDOUT is coming from the Python http.client.  The documentation for http.client states that debugging output is sent to STDOUT if the debug level is set to anything greater than zero.  http.client doesn't appear to support any options other than STDOUT.

https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection.set_debuglevel

I think the only option is set `config['log_requests'] = False` when you want to have the tests run without the debugging information getting in the way.

**Comment by xdobiasl** [comment]
OK, in that case - can you please document it?

**Comment by arthall** [comment]
Thank you for the feed back on making it clear in the documentation that logging can be turned on without enabling request logging.  I'll update the docs and try to make that separation between logging and enabling request logging more clearer.

**Comment by arthall** [comment]
I've updated the docs, but the first code block didn't render.  I'll need to track down what happened.  For now, please take a look https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/logging.html and imagine your example for turning on debugging for the oci package was immediately before the section on Request Logging.  Does this do a better job of explaining that logging can be enabled without also turning on request logging?

**Comment by arthall** [comment]
The issue with the example code block has fixed.  I'm going to close this issue now.  @xdobiasl please reopen it if you don't feel the updated documentation is adequate.
