### ISSUE TITLE
get_bucket returns null approximateCount and approximateSize

### ISSUE THREAD

**Issue by rrossouw01** [oracle/oci-python-sdk#142]
v2.2.16 (and earlier) get_bucket should return approximate_count and approximate_size as the documentation show here https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/object_storage/client/oci.object_storage.ObjectStorageClient.html

OCI Console works but python API and OCI cli v2.5.2 does not it returns null.

**Comment by adizohar** [comment]
I tested it and it works well with both OCI SDK and OCI-CLI

$oci --version
2.5.14

$ oci os bucket get --bucket-name JDE_Backup --fields approximateSize | jq '.data."approximate-size"'
213322359895

# Upgraded to oci-cli and oci:

Successfully installed oci-2.2.16 oci-cli-2.5.17
$ oci os bucket get --bucket-name JDE_Backup --fields approximateSize | jq '.data."approximate-size"'
213322359895

You can check my script at ~/examples/showoci as well

**Comment by rrossouw01** [comment]
Thanks!  I was obviously not understanding I had to pass --fields.  CLI works for me.  I will check your python for get_bucket to pass fields.

# oci --profile oci os bucket get --bucket-name fs-apps-tifs --fields approximateSize --fields approximateCount --region us-phoenix-1 | jq '.data | [."approximate-size",."approximate-count"]'
[
  1391993047215,
  4899805
]

**Comment by ravvitta** [comment]
Here is a simple Python Script to list the contents of your bucket and also get the size of all objects. 

I hope this helps. 

import requests
from requests.auth import HTTPBasicAuth
import json

url = "https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/<NameSapce>/<BucketName>"
result = requests.get(url)
creds = HTTPBasicAuth("<Username/email>","<Token Password>")

result = requests.get(url, auth=creds)
jsonstr = json.dumps(result.json(),indent=4)
print("Contents :{0}".format(jsonstr))

TotalSize = 0
jsonloads = json.loads(jsonstr)
locals()["bytes"] = jsonloads
for a in bytes.__iter__():
    TotalSize = TotalSize + a["bytes"]
print("Total Size of the objects in your Bucket: - " + str(round(TotalSize/(1024*1024*1024),2)) + "GB")

**Comment by rrossouw01** [comment]
Ravitta looks like you are counting and that will take a long on my 5 million items.  I just want approximate like in the console.  CLI and API worked for me now with adizohar's pointer to pass fields.

`details = object_storage.get_bucket(namespace, b.name, fields=['approximateCount','approximateSize']).data
    print(' {:50}  | {:70} | {:20} | {:10} | {:20}'.format(b.name, compartmentNS, details.storage_tier, convert_size(details.approximate_size),details.approximate_count))
`
