### ISSUE TITLE
The Python streaming example will break if you use longer keys or values

### ISSUE THREAD

**Issue by cartershanklin** [oracle/oci-python-sdk#147]
The Python streaming example at https://github.com/oracle/oci-python-sdk/blob/master/examples/stream_example.py uses the codecs library to perform base64 encoding.

This is fine until your key or value length gets around 64 or so. At that point the codecs approach will insert a linefeed to break lines into a certain max length.

```
[{
  "key": "QVNDLTIwMTktMDctMzBUMDc6Mzk6NDg=",
  "value": "QkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJC\nQg=="
}]
```

This, in turn, causes a message of the form:

```
oci.exceptions.ServiceError: {'opc-request-id': '47F4B3A3FB6A4B5AA32B58DC38BCBC19/7AEE33713B629408FE514713ECF0594D/A21AC3A21C520739739D3A3AFE3BC1D4', 'code': 'InvalidParameter', 'message': 'Unable to parse JSON body', 'status': 400}
```

This may be considered a backend glitch in the streaming service, not sure.

Anyway it's straightforward to be more robust at the Python level by using the base64 library instead as in:

```
encoded_value = base64.b64encode(value.encode()).decode()
```

I can confirm that this does not produce linefeeds and allows larger values to be streamed in.

**Comment by arthall** [comment]
Thanks @cartershanklin.  I'll update the example.

**Comment by arthall** [comment]
Thanks again @cartershanklin for reporting this.  The streaming team updated the example and it will be included with the next release.

**Comment by arthall** [comment]
The latest version of the example has been updated.  I'm closing this issue now.  Thanks again @cartershanklin
