### ISSUE TITLE
How to list tags& Values asscocited to a Tenancy resource

### ISSUE THREAD

**Issue by vbulusu16** [oracle/oci-python-sdk#154]
Hi All,

I wold like to knw using pythin sdk if we have a ny way to list all the tags and their assigned values of a particular resource in a tenancy. 

oci.identity.IdentityClient.list_tags(config,args)
Is listing the defined_tags of a tenancy but not able to get the tags associated to any specific resource and the values of those tags.. 

Thanks in Anticipation 
Bindu

**Comment by arthall** [comment]
I don't have much context on tags or how they are used so please bear with me if I am not answering the question you are asking.

The tagging overview documentation, https://docs.cloud.oracle.com/iaas/Content/Identity/Concepts/taggingoverview.htm.  It looks like list_tag_namespaces may be useful for getting all the tags and values.

```
import oci
config = oci.config.from_file()
identity = oci.identity.IdentityClient(config)
identity.list_tag_namespaces(config['tenancy']).data
```
Results with id's edited
```
[{
  "compartment_id": "ocid1.tenancy.oc1..aaa",
  "defined_tags": {},
  "description": "Java SDK Tag Namespace Level 1.",
  "freeform_tags": {},
  "id": "ocid1.tagnamespace.oc1..aaa",
  "is_retired": false,
  "lifecycle_state": "ACTIVE",
  "name": "java_sdk_tag_ns_001",
  "time_created": "2018-07-20T00:08:01.318000+00:00"
}, {
  "compartment_id": "ocid1.tenancy.oc1..aaa",
  "defined_tags": {
    "java_sdk_tag_ns_001": {
      "java_sdk_tag_01": "10",
      "java_sdk_tag_02": "JavaSDK",
      "java_sdk_tag_03": "2018-07-20T00:08:08.916Z"
    }
  },
  "description": "Java SDK Tag Namespace Level 2.",
  "freeform_tags": {
    "tag1": "value1",
    "tag2": "value2"
  },
  "id": "ocid1.tagnamespace.oc1..aaa",
  "is_retired": false,
  "lifecycle_state": "ACTIVE",
  "name": "java_sdk_tag_ns_002",
  "time_created": "2018-07-20T00:08:09.272000+00:00"
}]
```

To get the resources associated with a tag you can use the search service.  The following searches for instances that have the "java_sdk_tag_02" tag which was returned above.

```
search_client = oci.resource_search.ResourceSearchClient(config)
structured_search = oci.resource_search.models.StructuredSearchDetails(query="query instance resources where definedTags.namespace='java_sdk_tag_ns_001' && definedTags.key='java_sdk_tag_02'", type="Structured")
search_client.search_resources(structured_search).data
```

Results, again ids have been modified.
```
{
  "items": [
    {
      "availability_domain": "PHX-AD-2",
      "compartment_id": "ocid1.compartment.oc1..aaa",
      "defined_tags": {
        "java_sdk_tag_ns_001": {
          "java_sdk_tag_01": "10",
          "java_sdk_tag_02": "JavaSDK",
          "java_sdk_tag_03": "2019-06-04T22:05:25.948Z"
        }
      },
      "display_name": "JavaSDK",
      "freeform_tags": {
        "tag1": "value1",
        "tag2": "value2"
      },
      "identifier": "ocid1.instance.oc1.phx.aby",
      "lifecycle_state": "Running",
      "resource_type": "Instance",
      "search_context": null,
      "time_created": "2019-06-04T22:05:28.968000+00:00"
    }
  ]
}
```
More examples of using the search service are here: https://github.com/oracle/oci-python-sdk/blob/master/examples/search_example.py

**Comment by vbulusu16** [comment]
Hi Allan, 
Thanks for reviewing ..  
But when I list the name spaces im getting the details of teh name space alone .. but not the defined tags under it ..  

import oci
config = oci.config.from_file()
identity = oci.identity.IdentityClient(config)
identity.list_tag_namespaces(config['tenancy']).data
[{
  "compartment_id": "ocid1.tenancy.oc1..aaa......",
  "defined_tags": {},
  "description": "XXXXX Tagnamespace under XXXX compartment",
  "freeform_tags": {},
  "id": "ocid1.tagnamespace.oc1..aaaXXXXXXX",
  "is_retired": false,
  "lifecycle_state": "ACTIVE",
  "name": "XXXXXX",
  "time_created": "2019-09-04T06:05:34.205000+00:00"
}]

I have 2 defined tags under this namepsace .. but not able to list them ..  any suggestions for this 
<< ids have been modified.>>

**Comment by adizohar** [comment]
Hi 
You can use the showoci tool under examples to produce JSON file with all tenant resources including tags
Adi

**Comment by jodoglevy** [comment]
@vbulusu16  are you still in need of assistance here?

**Comment by jodoglevy** [comment]
@vbulusu16 since we haven't heard from you in a while, I'm closing this ticket. Feel free to reopen it if you are still having issues
