### ISSUE TITLE
Adding a date column for the CSV values

### ISSUE THREAD

**Issue by alxfirst** [oracle/oci-python-sdk#156]
I want to run showoci everyday, then merge the resulting files, to show the fluctuation of resources over the course of the month. Is there a possibility that you add a date (file creation, data collection) in every line of resource that get's written to the CSV?

**Comment by adizohar** [comment]
I will add to next version
Hopefully succeed to next Tuesday

**Comment by adizohar** [comment]
I added to next showoci version 19.9.11

**Comment by alxfirst** [comment]
Thanks Adi, when is that coming out?

**Comment by adizohar** [comment]
Should be tomorrow

**Comment by adizohar** [comment]
Alxfirst, code is released, can you please check and let me know if this work ?

**Comment by alxfirst** [comment]
extract_date ! Super Cool ! Thanks Adi !

**Comment by jodoglevy** [comment]
Fix has been deployed - closing this. If its not working let us know and we'll reopen.
