### ISSUE TITLE
Python 2 end of support

### ISSUE THREAD

**Issue by arthall** [oracle/oci-python-sdk#160]
Community support for Python 2 ends on January 1 2020.  Oracle OCI Python SDK depends on community supported packages and therefore will also be ending support for Python 2 on January 1 2020.  After that date bug fixes and enhancements will not take Python 2 compatibility into consideration.

**Comment by jodoglevy** [comment]
Closing this, as we are over 4 months past the end of support date of Python 2 in the SDK
