### ISSUE TITLE
delete_autonomous_database_and_wait_for_state errors out with 'DatabaseClient' object has no attribute 'get_work_request'

### ISSUE THREAD

**Issue by sauravmistry1989** [oracle/oci-python-sdk#165]
The following code block under delete_autonomous_database_and_wait_for_state of /usr/lib/python2.7/site-packages/oci/database/database_client_composite_operations.py is causing atp deletion to error out without waiting for completion:

`self.client.get_work_request(wait_for_resource_id),`

The client is and object of DatabaseClient which does not have get_work_request. Please help us with a fix.

**Comment by sauravmistry1989** [comment]
Any update on it ?

**Comment by jasonyin** [comment]
hi @sauravmistry1989 which API you are using under database_client_composite_operations.py ?

**Comment by jasonyin** [comment]
@sauravmistry1989 this is a bug in that API, we will working on a fix for it.

At same time, can you use 'delete_autonomous_database_and_wait_for_work_request' instead to unblock you for now? or you can just use the oci.wait_until for now.

**Comment by jasonyin** [comment]
I saw this API only returns work request, so the 'delete_autonomous_database_and_wait_for_work_request' operation is the right one to use. and the other method wait for status is for operation return with response body, such as lifecycle_status which doesn't apply in this case. 

That API will be removed.

**Comment by jodoglevy** [comment]
This issue has been fixed in the release today
