### ISSUE TITLE
ShowOci _limits.csv shows blank Used and Available columns

### ISSUE THREAD

**Issue by alxfirst** [oracle/oci-python-sdk#168]
Can this be fixed to show correct number of used and Available compared to the limits?

**Comment by jasonyin** [comment]
thanks for reporting the issue. it's been forwarded to the owner of this sample.

**Comment by adizohar** [comment]
HI Alxfirst, the API does not support all areas, therefore blank it means available is not supported yet, please check the documentation: 

https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/limits/client/oci.limits.LimitsClient.html

--> get_resource_availability(service_name, limit_name, compartment_id, **kwargs)
Get the availability and usage within a compartment for a given resource limit.

For a given compartmentId, resource limit name, and scope, returns the following:
the number of available resources associated with the given limit
the usage in the selected compartment for the given limit
Note: not all resource limits support this API. If the value is not available, the API will return 404.

**Comment by alxfirst** [comment]
Thanks Adi for the swift reply.
