### ISSUE TITLE
Add contents table to client documentation

### ISSUE THREAD

**Issue by EpicWink** [oracle/oci-python-sdk#169]
Navigating the client documentation to find what is supported, or the name of a feature, is tedious due to the inability to see all of the features at a glance. This is solved by having a table of contents for the client members.

This can be added automatically using [autodocsumm](https://github.com/Chilipp/autodocsumm): only 2 lines need to be added (see the quick-start guide in [the documentation](https://autodocsumm.readthedocs.io/en/latest/)). This will also add a member table of contents for the models as well, which may be beneficial.

**Comment by pelliu** [comment]
Hi @EpicWink, Thanks for submitting your request, we are currently working on the feature you needed and will update the status once done.

**Comment by pelliu** [comment]
Hi @EpicWink, we added the content table in this release, FYI, thanks!
