### ISSUE TITLE
Documentation for exceptions and exception handling does not discuss how to access the information from the exception

### ISSUE THREAD

**Issue by jearls** [oracle/oci-python-sdk#173]
Neither the documentation section *Exception Handling* nor the API reference on *Exceptions* document how to actually obtain the status code, error message, etc. from the exceptions that are raised by the SDK.

**Comment by jasonyin** [comment]
Hi @jearls the python exception doc is here: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/exceptions.html

copied from that link
'''
import oci

config = oci.config.from_file()
client = oci.object_storage.ObjectStorageClient(config)

try:
    get_object_response = client.get_object('my_namespace', 'my_bucket', 'my_object', if_none_match='some_etag_value')
except oci.exceptions.ServiceError as e:
    if e.status == 304:
        # Object exists but has not been modified (based on the etag value)
        pass
    else:
        raise
'''
