### ISSUE TITLE
Can we replace (gb) with (GB) in the Summary Total ?      

### ISSUE THREAD

**Issue by alxfirst** [oracle/oci-python-sdk#174]
Compute - Block Storage (gb)                  -        2142342

to 

Compute - Block Storage (GB)                  -        2142342

Pretty please :)

**Comment by adizohar** [comment]
Hi
Fixed for next version - next week 
For your info
Adi

**Comment by adizohar** [comment]
Hi alxfirst

The next version will be on the week of 10/29, for your info

Adi.

**Comment by adizohar** [comment]
Alxfirst
Code fixed, can you please download and confirm
Thank you 
Adi

**Comment by alxfirst** [comment]
All good, thanks !

**Comment by jodoglevy** [comment]
This issue is fixed, closing
