### ISSUE TITLE
No support to retreive a DNS record by record ID

### ISSUE THREAD

**Issue by tyskjohan** [oracle/oci-python-sdk#176]
When getting the details of a database system, one of the attributes returned is this:
```
 "scan-dns-record-id": "ocid1.vcndnsrecord.oc1.eu-frankfurt-1.abtheljro2hehxuxxtstbp26dfms7blit5na6ovughtandhna5ejplez7taq"
```
But there is no API support to get the actual DNS record (FQDN) from this ID!

**Comment by jodoglevy** [comment]
Update: we've reached out to the DNS team on this

**Comment by jtrier** [comment]
Exposure of the scan-dns-record-id field in the DBaaS API spec is a incorrect and not supported.  That field has meaning only in the context of an internal system and will not be exposed.  Customers would be best served by ignoring the field altogether.

**Comment by tyskjohan** [comment]
But then the Database System query API should return the actual FQDN instead of thar OCID.

**Comment by tyskjohan** [comment]
Any update here?

**Comment by jodoglevy** [comment]
We'll ping the owning team for an update

**Comment by adizohar** [comment]
Hi tyskjohan, 
I discussed with the product management and new API is coming later this year
Options for you:

1. The scan dns name uses a naming convention, you can construct it using dbs.hostname + "-scan." + dbs.domain
2. Use a generic REST client (from the console) and call the API endpoint directly without SDK.

Please let me know if this answer your question

For your info

Adi

**Comment by adizohar** [comment]
Hi 
New API added with version 2.31.1 - 2021-02-16
Added - Support for scan DNS names and zone ids on database system, cloud VM cluster, and autonomous Exadata infrastructure responses in the Database service

**Comment by jodoglevy** [comment]
Thanks @adizohar . This is indeed supported now. Closing this one
