### ISSUE TITLE
Can we rename VCN in OCI using OCI Python SDK 

### ISSUE THREAD

**Issue by vbulusu16** [oracle/oci-python-sdk#177]
Hi Team , 

From OCI console We don't have a option to rename a VCN display name  ..  Do we have a option of renaming a VCN Display name using python SDK .

**Comment by adizohar** [comment]
I did the change with oci-cli, it will be the same with python sdk, below example with oci-cli
oci network vcn update --vcn-id ocid1.vcn.oc1.iad.aaaaaaaahqrzdljtxzpll3wgiijch7npwqs2skdc57wn7fklgqp2tnrdoawa --auth instance_principal --display-name adi_vcn

**Comment by jodoglevy** [comment]
Yes, you can rename a VCN. Please see [here](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/client/oci.core.VirtualNetworkClient.html#oci.core.VirtualNetworkClient.update_vcn) (operation) and [here](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.UpdateVcnDetails.html#oci.core.models.UpdateVcnDetails) (model with the display name field)
