### ISSUE TITLE
Getting SSL error only for resource manager client

### ISSUE THREAD

**Issue by manpreet333** [oracle/oci-python-sdk#179]
I had openssl 1.0.1 installed already on my OEL 7.3 box and I updated it to 1.0.2 to resolve this.

```
python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2k-fips  26 Jan 2017
```

When calling other clients (compute, identity etc.) I see no issues at all.

```
comp_client = oci.core.ComputeClient(cfg)
resp = comp_client.list_instances('<TENANCY_OCID>')
resp.status
200
```

But when trying to use the resource manager client to list stacks:

```
clt = oci.resource_manager.ResourceManagerClient(cfg)
resp = clt.list_stacks()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/mbhamba/envs/279/oci/lib/python2.7/site-packages/oci/resource_manager/resource_manager_client.py", line 1454, in list_stacks
    response_type="list[StackSummary]")
  File "/scratch/mbhamba/envs/279/oci/lib/python2.7/site-packages/oci/base_client.py", line 235, in call_api
    response = self.request(request)
  File "/scratch/mbhamba/envs/279/oci/lib/python2.7/site-packages/oci/base_client.py", line 352, in request
    raise exceptions.RequestException(e)
oci.exceptions.RequestException: HTTPSConnectionPool(host='resourcemanager.us-ashburn-1.oraclecloud.com', port=443): Max retries exceeded with url: /20180917/stacks (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
```

**Comment by jodoglevy** [comment]
Update: we've reached out to the Resource Manager team on this

**Comment by adizohar** [comment]
Hi Manpreet333
I use open SSL 1.0.2  which updated in 2017, earlier SSL possibly not supported
For list_stacks, you must pass parameter, below does work for me:

import oci
config = oci.config.from_file('~/.oci/config', 'DEFAULT')
comp_client = oci.core.ComputeClient(config)
resp = comp_client.list_instances(config['tenancy'])
resp.status
200

clt = oci.resource_manager.ResourceManagerClient(config)
resp = clt.list_stacks(compartment_id=config['tenancy'])
resp.status
200

Please let me know if you need additional assistance ?
Thank you 
Adi.

**Comment by jodoglevy** [comment]
@manpreet333  are you still facing this issue? @adizohar responded end of May but we haven't heard back from you yet

**Comment by jodoglevy** [comment]
@manpreet333 since we haven't heard back from you in a while, and @adizohar posted a solution, I'm going to close this. If you are still facing issues please feel free to reopen
