### ISSUE TITLE
opc-next-page header is not showing under list_load_balancers even though we have 400+ active LB's 

### ISSUE THREAD

**Issue by anushj200** [oracle/oci-python-sdk#180]
opc-next-page header is not showing under list_load_balancers even though we have 400+ active LB's 

Code: 

lb_cli = oci.load_balancer.LoadBalancerClient(config)

Case: 1
lbrs = lb_cli.list_load_balancers(icompartment, lifecycle_state='ACTIVE')
print(lbrs.headers)

Under headers, we are not getting "opc-next-page" even though we have 400+ active LB's 

Case: 2
lbrs = lb_cli.list_load_balancers(icompartment)
print(lbrs.headers)

without lifecycle_state='ACTIVE' we are getting all the LoadBalancer with "opc-next-page" header 

Document: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/load_balancer/client/oci.load_balancer.LoadBalancerClient.html

**Comment by jodoglevy** [comment]
Update: we've reached out to the Load Balancing service team on this

**Comment by abdusherif** [comment]
@anushj200 What region did you use in your config? Also can you please provide your compartmentId so we can take a look at the logs?

**Comment by jodoglevy** [comment]
@anushj200 since we haven't heard from you, I'm closing this ticket. Please feel free to reopen it if you are still having the issue
