### ISSUE TITLE
Compartment list with subtree not returning all compartments

### ISSUE THREAD

**Issue by cruepprich** [oracle/oci-python-sdk#182]
When comparing the list compartments returned with the SDK to the actual number of compartments in the tenancy, I notice that some compartments are missing when using the SDK with  --compartment-id-in-subtree.

```
#!/usr/bin/env python3

import oci

config = oci.config.from_file()

IdentityClient = oci.identity.IdentityClient(config=config)

compartments   = IdentityClient.list_compartments(
                    config["tenancy"],
                    compartment_id_in_subtree=True,
                    access_level="ANY"
                 ).data

print(len(compartments))
```

This results in 16 compartments being listed. When I run the OCI CLI from the same config file and profile (DEFAULT), I get 21 compartments.
Am I doing anything wrong here?

oci version 2.6.2.

**Comment by adizohar** [comment]
Hi Michael
You may need to use the pagination call to list all results
Check example under examples folder
For your info
Adi

**Comment by cruepprich** [comment]
Thanks Adi,
that did the trick.

Christoph
