### ISSUE TITLE
in the compute showoci CSV, can we get total block storage volume instead of + delimited list

### ISSUE THREAD

**Issue by alxfirst** [oracle/oci-python-sdk#183]
I saw that this value is in the form of 100+ 500+ 2000. 
I think the total size would be more interesting in this view. 

Does that make sense? I can't see an instance where you would need the CSV with this type of data.

**Comment by adizohar** [comment]
Hi Alxfirst
I added column block_volumes_total_gb , it will be available on next release
For your info
Adi

**Comment by adizohar** [comment]
Hi Alxfirst
Code published, Please check and let me know if does work as expected
Thank you 
Adi
