### ISSUE TITLE
Document/Provide Example for how to use key_content

### ISSUE THREAD

**Issue by priteshkp** [oracle/oci-python-sdk#185]
There are use cases that need to provide the private key but not from a file.  This is possible by utilizing key_content, but that feature is not documented anywhere and there is no example of using it.

Could you please provide an example and/or documentation for how to utilize it?

According to this SO responder, it is available to use: https://stackoverflow.com/questions/58423652/is-the-key-content-field-safe-to-use-in-the-oci-python-sdk

**Comment by dmitrypol** [comment]
+1

**Comment by pelliu** [comment]
Hi priteshkp and dmitrypol,  thanks for letting us know directly use key_content use case, currently we can support this, just not provide the example, I will update our document, could be available in GA87.

**Comment by dmitrypol** [comment]
So key_content will be officially supported in the future?

**Comment by pelliu** [comment]
Hi @dmitrypol and @priteshkp the latest python SDK includes the example of key_content, you can find from here:
https://github.com/oracle/oci-python-sdk/blob/master/examples/configuration_example.py
https://github.com/oracle/oci-python-sdk/blob/master/docs/configuration.rst

Again, really appreciate your suggestions.
