### ISSUE TITLE
LimitsClient - ability to search all usage values for a given scope and service

### ISSUE THREAD

**Issue by mannyreds11** [oracle/oci-python-sdk#190]
I need to get all values displayed on this dashboard for monitoring purposes: https://console.us-phoenix-1.oraclecloud.com/limits
I'm currently unable to do this within a simple endpoint here: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/limits/client/oci.limits.LimitsClient.html

The closest call would be: 
```
list_limit_values(compartment_id, service_name, **kwargs)
```
e.g.
```
➜  ~ oci limits value list --compartment-id ocid1.tenancy.oc1..XXX --service-name database --region us-ashburn-1
{
  "data": [
    {
      "availability-domain": null,
      "name": "adb-free-count",
      "scope-type": "REGION",
      "value": 0
    },
    {
      "availability-domain": null,
      "name": "adw-ocpu-count",
      "scope-type": "REGION",
      "value": 8
    },
    {
      "availability-domain": null,
      "name": "atp-ocpu-count",
      "scope-type": "REGION",
      "value": 8
    },
    {
      "availability-domain": "HUYg:US-ASHBURN-AD-1",
      "name": "bm-dense-io1-36-count",
      "scope-type": "AD",
      "value": 0
    },
    {
      "availability-domain": "HUYg:US-ASHBURN-AD-2",
      "name": "bm-dense-io1-36-count",
      "scope-type": "AD",
      "value": 0
    },
    {
      "availability-domain": "HUYg:US-ASHBURN-AD-3",
      "name": "bm-dense-io1-36-count",
      "scope-type": "AD",
      "value": 0
    }
...
```

but that only lists the limit's cap value, and not the usage values
Would it be possible to include the usage as well on this call? 
Maybe there's an easier way to do it but right now it's taking me over 200+ api calls to get all the values I need with: 
```
get_resource_availability(service_name, limit_name, compartment_id, **kwargs)
```

Any help would be appreciated

**Comment by adizohar** [comment]
Hi Manuel
This is the way the service API designed there are different security roles to run the list limits and other policy for usage and availability APIs
For your info
Adi.

**Comment by jodoglevy** [comment]
Closing as this question has been answered
