### ISSUE TITLE
Does oci sdk support authorization to custom applications 

### ISSUE THREAD

**Issue by manikarthikk** [oracle/oci-python-sdk#192]
we want to add authentication to our service api's using oci identity. Does this library support  authorization to authorize requests from other applications ?

**Comment by jodoglevy** [comment]
Hi @manikarthikk  - are you asking about OAuth support?

**Comment by manikarthikk** [comment]
Yes

**Comment by jodoglevy** [comment]
Got it. Please see https://github.com/oracle/oci-java-sdk/issues/35

**Comment by manikarthikk** [comment]
Looks like not supported right now based on that thread. Thanks
