### ISSUE TITLE
Create instance from partner image

### ISSUE THREAD

**Issue by smarlowucf** [oracle/oci-python-sdk#194]
I am attempting to create an instance from a partner image. However, it looks like you need the compartment ID where the partner images live to get a list containing the image. And even if you have the ID the user still needs a policy available to get a list of images for that compartment.

How can an instance be created from the SDK based on a partner image without requiring the compartment ID or a policy being created for each user?

The method I'm using is:

```
list_images_response = oci.pagination.list_call_get_all_results(
            self.compute_client.list_images,
            compartment_id
        )
```

Where compartment_id would have to match the compartment that the partner image lives in. It seems like this would be possible if you owned the compartment but not if a you are a third party user.

**Comment by smarlowucf** [comment]
As a note I'm following the example https://github.com/oracle/oci-python-sdk/blob/master/examples/launch_instance_example.py. However, the get_images method only returns platform images but I need a list of partner images without requiring compartment_id or a way to find a partner image by image build that doesn't require the compartment_id.

**Comment by smarlowucf** [comment]
I see there is mention of "Oracle Cloud Infrastructure enables you to launch instances from images published by Oracle partners from the Partner Image catalog." But there's no info on how to launch an instance related to AppCatalog functions.

**Comment by sdstewar** [comment]
As you surmised the `list_images` call only returns all the "Platform Images" and the  Custom Images that would be available in the compartment you're passing requesting.  To get access to partner images you need to look at the `list_app_catalog_listings` call.  

```python
resp = oci.pagination.list_call_get_all_results(
    compute_client.list_app_catalog_listings,
    publisher_type="ORACLE", 
    display_name=display_name, 
    sort_order="DESC")
```

**Comment by jodoglevy** [comment]
@smarlowucf do you still need help, or does the above answer your question?

**Comment by smarlowucf** [comment]
Hi, @jodoglevy. Yes, I was able to get things figured out, thank you. I will go ahead and close this although I think it would still be helpful to have some more documentation or examples around using partner images. Thanks.
