### ISSUE TITLE
Unable to get console history content

### ISSUE THREAD

**Issue by smarlowucf** [oracle/oci-python-sdk#195]
An attempt to get console history content from an instance leads to 404 error even though the user has full permissions. The policy that affects the user is:

```
Allow group {user_group} to manage all-resources in compartment {compartment_name}
```

The code that leads to 404 error is:

```
history_details = oci.core.models.CaptureConsoleHistoryDetails(
    instance_id=instance_id
)

result = self.compute_composite_client.capture_console_history_and_wait_for_state(
    history_details,
    wait_for_states=[oci.core.models.ConsoleHistory.LIFECYCLE_STATE_SUCCEEDED]
).data

output = self.compute_client.get_console_history_content(result.id).data

return output
```

Is there a specific policy for getting the content or an issue with the code being used?

**Comment by adizohar** [comment]
This work well for me, please try and let me know:

import oci

signer = oci.auth.signers.InstancePrincipalsSecurityTokenSigner()
config = {'region': signer.region, 'tenancy': signer.tenancy_id}

compute_client = oci.core.ComputeClient(config, signer=signer)

instance_id = 'ocid1.instance.oc1.iad.abuwcljsd27ddpfvlq3boailo2cgrd27bgat7v4e53mk4d5zb4z2d33loohq'

history_details = oci.core.models.CaptureConsoleHistoryDetails(instance_id=instance_id)

result = compute_client.capture_console_history(history_details).data
output = compute_client.get_console_history_content(result.id).data

**Comment by jodoglevy** [comment]
@smarlowucf  does @adizohar 's response resolve your issue? Haven't heard from you in a while. If we don't hear from you in another week or so, I'll assume your issue is resolved and close this

**Comment by smarlowucf** [comment]
Hi, I will give this a test and follow up with the result. Thank you!

**Comment by smarlowucf** [comment]
I got this to work but with the wait method `capture_console_history_and_wait_for_state`. If I only use `capture_console_history` it leads to a 409 error `Console history cannot be retrieved in state Requested`.

However the output seems to be in a weird encoding and has chars that UTF-8 doesn't understand. Is there a specific encoding that should be used when decoding from bytes?

```
[2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01H[0m[35m[40m[2J[01;01H[=3h[2J[01;01H[0m[37m[40m


[1m[37m[40miPXE 1.0.0+ ()[0m[37m[40m -- Open Source Network Boot Firmware -- [0m[36m[40mhttp://ipxe.org[0m[37m[40m
Features: DNS HTTP HTTPS iSCSI TFTP AoE EFI Menu


iPXE GIT : 0e31029
iPXE Built for: snp
Configuring (net0 00:00:17:00:93:5c)...... ok
NETWORK info :
IP address.....10.0.0.2
Netmask........255.255.255.248
Gateway........10.0.0.1
Domain.........
```
