### ISSUE TITLE
there are no apigateway files in src/oci

### ISSUE THREAD

**Issue by AndreyAdnreyev** [oracle/oci-python-sdk#199]
# pip install .
Processing /home/opc/oci-python-sdk
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/lib/python2.7/site-packages (from oci==2.8.0)
Requirement already satisfied (use --upgrade to upgrade): configparser>=3.5.0b1 in /usr/lib/python2.7/site-packages (from oci==2.8.0)
Collecting cryptography>=2.1.4 (from oci==2.8.0)
  Using cached https://files.pythonhosted.org/packages/e2/67/4597fc5d5de01bb44887844647ab8e73239079dd478c35c52d58a9eb3d45/cryptography-2.8-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyOpenSSL>=17.5.0 (from oci==2.8.0)
  Using cached https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): python-dateutil<3.0.0,>=2.5.3 in /usr/lib/python2.7/site-packages (from oci==2.8.0)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2016.10 in /usr/lib/python2.7/site-packages (from oci==2.8.0)
Requirement already satisfied (use --upgrade to upgrade): enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=2.1.4->oci==2.8.0)
Requirement already satisfied (use --upgrade to upgrade): cffi!=1.11.3,>=1.8 in /usr/lib64/python2.7/site-packages (from cryptography>=2.1.4->oci==2.8.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography>=2.1.4->oci==2.8.0)
Requirement already satisfied (use --upgrade to upgrade): ipaddress; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=2.1.4->oci==2.8.0)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4->oci==2.8.0)
Installing collected packages: cryptography, pyOpenSSL, oci
  Found existing installation: cryptography 1.7.2
    Uninstalling cryptography-1.7.2:
      Successfully uninstalled cryptography-1.7.2
  Found existing installation: pyOpenSSL 0.13.1
    DEPRECATION: Uninstalling a distutils installed project (pyOpenSSL) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pyOpenSSL-0.13.1:
      Successfully uninstalled pyOpenSSL-0.13.1
  Running setup.py install for oci ... done
Successfully installed cryptography-2.8 oci-2.8.0 pyOpenSSL-18.0.0
You are using pip version 8.1.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@andrey oci-python-sdk]# python
Python 2.7.5 (default, Dec  4 2019, 17:34:13) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import oci
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/oci/__init__.py", line 4, in <module>
    from . import analytics, announcements_service, apigateway, audit, autoscaling, budget, container_engine, core, database, dns, dts, email, events, file_storage, functions, healthchecks, identity, integration, key_management, limits, load_balancer, marketplace, monitoring, object_storage, oce, oda, ons, os_management, resource_manager, resource_search, streaming, waas, work_requests
ImportError: cannot import name apigateway

**Comment by pelliu** [comment]
Hi @AndreyAdnreyev, the oci-python-sdk version v2.8.0 releasing is still in process, please do not pick up the commit, we will add release package and release tag once everything is done, then you pick up there, sorry for the inconvenience.

**Comment by pelliu** [comment]
@AndreyAdnreyev, we successfully released oci-python-sdk v2.8.0, so it should be fine to get the new service apigateway, thanks!
