### ISSUE TITLE
Can we get the script to pull usage as well from the console

### ISSUE THREAD

**Issue by alxfirst** [oracle/oci-python-sdk#202]
For customers who want to get this data into analytics, and have the usage info as well, is there a way to get the usage data for example the one in the Cost Analysis module?

**Comment by jodoglevy** [comment]
Currently, the cost analysis APIs are not publicly exposed for direct customer use.

You can get current usage for some of the limits using the service limits APIs: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/limits/client/oci.limits.LimitsClient.html

**Comment by philneworacle** [comment]
We are working on improved APIs that we plan to release in the coming months that will solve this issue. In the meantime, you can use the Oracle Cloud Metering API to get the data. https://docs.oracle.com/en/cloud/get-started/subscriptions-cloud/meter/Use_Cases.html

**Comment by adizohar** [comment]
Cost usage already in production, please check my script - https://github.com/oracle/oci-python-sdk/tree/master/examples/usage_reports_to_adw

**Comment by jodoglevy** [comment]
@alxfirst  does @adizohar 's response resolve your issue? Haven't heard from you in a while. If we don't hear from you in another week or so, I'll assume your issue is resolved and close this

**Comment by jodoglevy** [comment]
@alxfirst since we haven't heard from you in a couple weeks, I'm going to close this ticket. Feel free to reopen it if you're still having issues
