### ISSUE TITLE
Code error in decrypt example

### ISSUE THREAD

**Issue by mengqi1984** [oracle/oci-python-sdk#207]
https://github.com/oracle/oci-python-sdk/blob/master/examples/kms_example.py
line 251, 
response = key_crypto_client.encrypt(decrypt_data_details)
=================
should use decrypt function, not encrypt.

**Comment by suryanarayanan** [comment]
https://github.com/oracle/oci-python-sdk/pull/221 should fix it

**Comment by adizohar** [comment]
I pushed the changed and it should be there on next release
