### ISSUE TITLE
list_databases still requires db_home_id

### ISSUE THREAD

**Issue by fauzank** [oracle/oci-python-sdk#208]
In 2.10.0 the list_databases method removed the required arguement for db_home_id. However, the method does not run with just the compartment_id field passed

'message': 'This request is missing a required value for at least one of the following arguments: dbHomeId,systemId', 'status': 400

**Comment by pelliu** [comment]
Thanks for the comments @fauzank, could you please add more context in which test case you run into the issue? Based on my checking,  `showoci_service.py` have one test case(def __load_database_dbsystems_dbhomes_databases) is with the issue, we will update `db_home_id` to `db_home_id=db_home_id`,the fix will be merged on next release.

**Comment by vedika-jd** [comment]
@fauzank, We made db_home_id optional for shared db home enabled platforms (Exadata Cloud Service platform for now). That said, one of db_home_id or system_id is still a required parameter. For BM/VM/Exadata cloud at customer platforms, db_home_id is still required and this is enforced using api validation code.

**Comment by jodoglevy** [comment]
I'm going to close this based on the response above from the Database team. If you still have questions, please feel free to reopen this

**Comment by amaslows** [comment]
Might be good to add this info the the docs, I also was expecting to list all databases in the compartment without home id or system id based in https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/database/client/oci.database.DatabaseClient.html#oci.database.DatabaseClient.list_databases

**Comment by vedika-jd** [comment]
Thanks @amaslows ! This will be added to the docs soon.
