### ISSUE TITLE
Create WAAS Policy(python SDK and OCI CLI) Policy creating it, but showing errors.

### ISSUE THREAD

**Issue by nadeem-taj73** [oracle/oci-python-sdk#209]
Used OCI CLI to create WAAS Policy. Created the Policy but Policy Information on Console show:
**"Encountered an unexpected error - reload the page or contact customer support."**

Tried using Python SDK as well but with the same result:
--------------------------------------------------------------------
waas_client = oci.waas.WaasClient(config)
policy_details = oci.waas.models.CreateWaasPolicyDetails(compartment_id=tenancy, domain="ociwaasdemo1.net", origins = origins_waf )
policy_waas_created = waas_client.create_waas_policy(policy_details)
print(policy_waas_created.status)                        #### prints 202

COMMANDS USED WITH CLI:
-------------------------------------
[root@xxxxx ~]# oci waas waas-policy create --compartment-id ocid1.xxxxxxxxxxxx --domain xxxxx.com --display-name xxxxxxx --profile XXXXX
{
        "message": "GetOrCreateTenantOp: start",
        "timestamp": "2020-01-21T04:14:37.216000+00:00"
      },
      {
        "message": "GetOrCreateTenantOp: finished **(50% of request completed**)",
        "timestamp": "2020-01-21T04:14:37.216000+00:00"
      },
      {
        "**message": "Starting Work Request",**
        "timestamp": "2020-01-21T04:14:37.137000+00:00"
      }

Can you please let me know if i am missing some parameters or any info i have missed out. 
Thanks
Nadeem

**Comment by jodoglevy** [comment]
This seems to be an issue with the WaaS service, and/or the OCI console. We'll work to route this to the correct team to follow up here.

**Comment by adizohar** [comment]
It works well - see below, you may have limit issue in your tenancy, it is not SDK or CLI issue, please check your tenancy limits

adiwork> oci waas waas-policy create --compartment-id ocid1.compartment.oc1..aaaaaaaa24b3mfwu6aulib33oan3eqicwm4az65cog7o7ql5sluqtaahn76q --domain test.com --disply-name adi-test
{
  "etag": "W/\"2020-05-12T18:05:02.448Z\"",
  "opc-work-request-id": "ocid1.waasworkrequest.oc1..aaaaaaaamfpskxumkmxgvupfjkbsnqp3nywcjfolafspgnfgojeglwghlqkq"
}

adiwork> oci waas work-request get --work-request-id ocid1.waasworkrequest.oc1..aaaaaaaamfpskxumkmxgvupfjkbsnqp3nywcjfolafspgnfgojeglwghlqkq
{
  "data": {
    "compartment-id": "ocid1.compartment.oc1..aaaaaaaa24b3mfwu6aulib33oan3eqicwm4az65cog7o7ql5sluqtaahn76q",
    "errors": [],
    "id": "ocid1.waasworkrequest.oc1..aaaaaaaamfpskxumkmxgvupfjkbsnqp3nywcjfolafspgnfgojeglwghlqkq",
    "logs": [
      {
        "message": "Work request complete",
        "timestamp": "2020-05-12T18:05:25.875000+00:00"
      },
      {
        "message": "FinishCreateWaasPolicyOp: start",
        "timestamp": "2020-05-12T18:05:25.868000+00:00"
      },
      {
        "message": "FinishCreateWaasPolicyOp: finished (100% of request completed)",
        "timestamp": "2020-05-12T18:05:25.868000+00:00"
      },
      {
        "message": "GetOrCreateTenantOp: start",
        "timestamp": "2020-05-12T18:05:25.843000+00:00"
      },
      {
        "message": "GetOrCreateTenantOp: finished (50% of request completed)",
        "timestamp": "2020-05-12T18:05:25.843000+00:00"
      },
      {
        "message": "Starting Work Request",
        "timestamp": "2020-05-12T18:05:25.749000+00:00"
      }
    ],
    "operation-type": "CREATE_WAAS_POLICY",
    "percent-complete": 100,
    "resources": [
      {
        "action-type": "CREATED",
        "entity-type": "waas",
        "entity-uri": "/20181116/waasPolicies/ocid1.waaspolicy.oc1..aaaaaaaazobynkxp7h2kf4jlmyxthaulgatkmgdodahy75lfinlvaexxbzya",
        "identifier": "ocid1.waaspolicy.oc1..aaaaaaaazobynkxp7h2kf4jlmyxthaulgatkmgdodahy75lfinlvaexxbzya"
      }
    ],
    "status": "SUCCEEDED",
    "time-accepted": "2020-05-12T18:05:02.605000+00:00",
    "time-finished": "2020-05-12T18:05:25+00:00",
    "time-started": "2020-05-12T18:05:25+00:00"
  },
  "etag": "W/\"2020-05-12T18:05:02.448Z\""

**Comment by jodoglevy** [comment]
@nadeem-taj73  does @adizohar 's response resolve your issue? Haven't heard from you in a while. If we don't hear from you in another week or so, I'll assume your issue is resolved and close this

**Comment by jodoglevy** [comment]
@nadeem-taj73 since we haven't heard from you in a couple weeks, I'm going to close this ticket. Feel free to reopen it if you're still having issues
