### ISSUE TITLE
Configparser is in python3 standard library

### ISSUE THREAD

**Issue by smarlowucf** [oracle/oci-python-sdk#211]
There is a requirement in setup.py for `configparser>=3.5.0b1`. This seems to be incorrect as configparser is part of the python3 standard library. I think the requirement would only be valid for python2 which is no longer supported by the PSF.

**Comment by HenryLinTw** [comment]
any plan to remove configparser?

**Comment by jhult** [comment]
Bump. Any updates?

**Comment by bhagwatvyas** [comment]
We're planning to unpin the dependency version soon for configparser. We cannot remove configparser completely because we have some internal customers we are still working with to move off Python 2. @jhult @smarlowucf would this help solve your issue?

**Comment by smarlowucf** [comment]
@bhagwatvyas for my case I have things patched so it's not a blocker. However, the requirements file ideally would not pin the dependency for python3. It could use a specifier for python 2 only like:

`configparser==4.0.2  ; python_version < '3'`

**Comment by bhagwatvyas** [comment]
@smarlowucf thank you for your suggestion. We're working on testing the change.

**Comment by bhagwatvyas** [comment]
This is fixed in v2.46.0. Closing this issue, but feel free to comment in case of any issues. Thank you!
