### ISSUE TITLE
What is the procedure to get the Status of Backend Health

### ISSUE THREAD

**Issue by sreecharanm** [oracle/oci-python-sdk#213]
1. Please let me know what are the methods we need to use to get the Backend Health.
2. I am getting the status through oci - cli
3. Whereas with Python SDK it is not giving the exact Result.
4. Please provide me the step by step process. It will be helpful for me

**Comment by jodoglevy** [comment]
Hi - we'll route this to the Load Balancing team to provide an answer here

**Comment by aditya-jalan** [comment]
Here is the api for your reference:
https://docs.cloud.oracle.com/en-us/iaas/api/#/en/loadbalancer/20170115/BackendHealth/

**Comment by sreecharanm** [comment]
hi aditya-jalan , i need python solution not the rest-api , please provide me that you've any snippet to get the status of the Backend Health using PYTHON SDK, Please ... Please ... provide me any example you have thanks.

**Comment by adizohar** [comment]
You can take a look at my showoci script - https://github.com/oracle/oci-python-sdk/tree/master/examples/showoci

The function is - status = load_balancer.get_backend_set_health(load_balancer_id, bs.name).data.status

The check is @ https://github.com/oracle/oci-python-sdk/blob/master/examples/showoci/showoci_service.py, line 4340

**Comment by sreecharanm** [comment]
Super adizohar, it worked , Thanks a lot
