### ISSUE TITLE
Help with example script for Monitoring

### ISSUE THREAD

**Issue by pulivenu** [oracle/oci-python-sdk#214]
Could you please help with some example script in the monitoring space, 
getting metric data ,
an example using SummarizeMetricsDataDetails 

thank you

**Comment by jodoglevy** [comment]
Hi - we'll route this to the Monitoring team to provide an answer here

**Comment by adizohar** [comment]
Here is workable example

import oci

signer = oci.auth.signers.InstancePrincipalsSecurityTokenSigner()
config = {'region': signer.region, 'tenancy': signer.tenancy_id}

metric_client = oci.monitoring.MonitoringClient(config, signer=signer)

metric_detail = oci.monitoring.models.SummarizeMetricsDataDetails()
metric_detail.query = 'CPUUtilization[60m]{resourceId = "ocid1.instance.oc1.iad.abuwcljsd27ddpfvlq3boailo2cgrd27bgat7v4e53mk4d5zb4z2d33loohq"}.max()'
metric_detail.start_time = "2020-05-01T00:00:00.000Z"
metric_detail.end_time = "2020-05-10T00:00:00.000Z"
metric_detail.resolution = "1h"
metric_detail.namespace = "oci_computeagent"
compartment_id = "ocid1.compartment.oc1..aaaaaaaa24b3mfwu6aulib33oan3eqicwm4az65cog7o7ql5sluqtaahn76q"

metric_client.summarize_metrics_data(compartment_id, metric_detail).data

**Comment by jodoglevy** [comment]
@pulivenu does @adizohar 's response resolve your issue? Haven't heard from you in a while. If we don't hear from you in another week or so, I'll assume your issue is resolved and close this

**Comment by jodoglevy** [comment]
@pulivenu since we haven't heard from you in a couple weeks, I'm going to close this ticket. Feel free to reopen it if you're still having issues
