### ISSUE TITLE
compute_client.list_vnic_attachments returns VNIC's in random order

### ISSUE THREAD

**Issue by tyskjohan** [oracle/oci-python-sdk#215]
It would be desirable to be able to determine through the API what is the "primary" VNIC of an instance. Either through a separate API call, a field on the response object, or by always returning the primary VNIC as the first item of the list.

**Comment by jodoglevy** [comment]
Hi - we'll route this to the Compute team to provide an answer here

**Comment by tyskjohan** [comment]
Any update here?

**Comment by jodoglevy** [comment]
We'll ping the owning team for an update

**Comment by fahdabidi** [comment]
"list vnic" can tell you if a vnic is primary:

cmd# oci compute instance list-vnics --instance-id ocid1.instance.oc1.phx.XXXXXXXXXXXXXXXXXX
{
  "data": [
    {
      "availability-domain": "Qhab:PHX-AD-1",
      "compartment-id": "ocid1.tenancy.oc1..XXXXXXXXXXXXXXXXXXXXX",
      "defined-tags": {},
      "display-name": "instance-20200207-1732",
      "freeform-tags": {},
      "hostname-label": null,
      "id": "ocid1.vnic.oc1.phx.XXXXXXXXXXXXXXXXXXXXXXXXXXXx",
      **"is-primary": true,**
      "lifecycle-state": "AVAILABLE",
      "mac-address": "00:00:17:00:BB:6C",
      "nsg-ids": [],
      "private-ip": "10.0.0.12",
      "public-ip": "129.146.100.62",
      "skip-source-dest-check": false,
      "subnet-id": "ocid1.subnet.oc1.phx.aaaaaaaakfatqp7tvzkitl2mryctwmre3ock45nzl3vrxvlf2o334uafczhq",
      "time-created": "2020-02-08T01:32:44.547000+00:00"
    }
  ]
}

**Comment by tyskjohan** [comment]
Thanks @fahdabidi - unfortunately, it seems the Python API does not expose this in [`ComputeClient.list_vnic_attachments`](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.VnicAttachment.html#oci.core.models.VnicAttachment) - maybe I'm looking in the wrong place?

**Comment by jodoglevy** [comment]
@tyskjohan the (CLI) operation @fahdabidi is referring to, `list-vnics`, uses a combination of the `ComputeClient.list_vnic_attachments` and `VirtualNetworkClient.get_vnic` calls, combining the information before returning it to the user. You'll want to use these two calls together to get the same information in the Python SDK
