### ISSUE TITLE
How to get the List OF Network Security Groups for the specific Load balancer

### ISSUE THREAD

**Issue by sreecharanm** [oracle/oci-python-sdk#216]
Hi Team, Will you please provide the method to get the list of Network Security Groups for the Specific Load Balancer.  i found only update_Network_security_Group . Please provide me the method to  get_Network_Security_Group List.

**Comment by jodoglevy** [comment]
Hi - we'll route this to the Load Balancing team to provide an answer here

**Comment by sreecharanm** [comment]
please let me know the method to get the list of NSG related to the load_balancer

**Comment by sreecharanm** [comment]
@jodoglevy, will you please let me know the status of this, as we are not able to list the NSG related to the load_balancer.

**Comment by jodoglevy** [comment]
I will ping the Load Balancing team

**Comment by adizohar** [comment]
Here how to do it:

load_balancer = load_balancer_client.get_load_balancer(load_balancer_ocid).data
for nsg in load_balancer.network_security_group_ids:
    print (nsg)

**Comment by jodoglevy** [comment]
@sreecharanm does @adizohar 's response resolve your issue? Haven't heard from you in a while. If we don't hear from you in another week or so, I'll assume your issue is resolved and close this

**Comment by jodoglevy** [comment]
@sreecharanm since we haven't heard from you in a couple weeks, I'm going to close this ticket. Feel free to reopen it if you're still having issues
