### ISSUE TITLE
showoic.py does not capture the VM.Standard2.x entries in the Limits Section

### ISSUE THREAD

**Issue by NullARC** [oracle/oci-python-sdk#219]
When running showpic.py (2.10.2), it does not pull all of the limits that are available via the OCI UI - It appears to be missing the VM.Standard2.x entries

############################################################
#                        showoci.py                        #
############################################################
Authentication : Config File
Config File    : ~/.oci/config
Config Profile : DEFAULT
Version        : 20.1.29
Date/Time      : 2020-02-04 13:37:57
Comand Line    : -a -rg us-ashburn-1 -csv xxxxxxxx.csv
OCI SDK Ver    : 2.10.2

##############################
#         Limits > 0         #
##############################
--> api-gateway         gateway-count                         = 10         Used =             Available = 10          SCOPE=REGION
--> auto-scaling        config-count                          = 200        Used =             Available =             SCOPE=REGION
--> block-storage       backup-count                          = 4005       Used = 885         Available = 3120        SCOPE=REGION
--> block-storage       free-backup-count                     = 5          Used =             Available = 5           SCOPE=REGION
--> block-storage       total-free-storage-gb                 = 100        Used = 100         Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> block-storage       total-storage-gb                      = 102500     Used = 39854       Available = 62646       SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> block-storage       total-storage-gb                      = 102400     Used = 1424        Available = 100976      SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> block-storage       total-storage-gb                      = 102400     Used =             Available = 102400      SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> block-storage       volume-count                          = 10000      Used = 65          Available = 9935        SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> block-storage       volume-count                          = 10000      Used = 4           Available = 9996        SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> block-storage       volume-count                          = 10000      Used =             Available = 10000       SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> block-storage       volumes-per-group                     = 32         Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> block-storage       volumes-per-group                     = 32         Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> block-storage       volumes-per-group                     = 32         Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compartments        compartment-count                     = 200        Used = 3           Available = 197         SCOPE=REGION
--> compute             bm-dense-io2-52-count                 = 2          Used =             Available = 2           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             bm-dense-io2-52-count                 = 2          Used =             Available = 2           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             bm-dense-io2-52-count                 = 2          Used =             Available = 2           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             bm-gpu2-2-count                       = 1          Used =             Available = 1           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             bm-gpu3-8-count                       = 2          Used =             Available = 2           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             bm-gpu3-8-count                       = 2          Used =             Available = 2           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             bm-hpc2-36-count                      = 2          Used =             Available = 2           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             bm-standard-b1-44-count               = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             bm-standard-b1-44-count               = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             bm-standard-b1-44-count               = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             bm-standard-e2-64-count               = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             bm-standard-e2-64-count               = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             bm-standard-e2-64-count               = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             bm-standard1-36-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             bm-standard1-36-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             bm-standard1-36-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             bm-standard2-52-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             bm-standard2-52-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             bm-standard2-52-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             custom-image-count                    = 100        Used =             Available = 100         SCOPE=REGION
--> compute             dvh-standard2-52-count                = 1          Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             dvh-standard2-52-count                = 1          Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             dvh-standard2-52-count                = 1          Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-dense-io2-16-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-dense-io2-16-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-dense-io2-16-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-dense-io2-24-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-dense-io2-24-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-dense-io2-24-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-dense-io2-8-count                  = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-dense-io2-8-count                  = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-dense-io2-8-count                  = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-gpu2-1-count                       = 10         Used =             Available = 10          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-gpu3-1-count                       = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-gpu3-1-count                       = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-gpu3-2-count                       = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-gpu3-2-count                       = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-gpu3-4-count                       = 4          Used =             Available = 4           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-gpu3-4-count                       = 4          Used =             Available = 4           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard-b1-1                      = 40         Used =             Available = 40          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-b1-1                      = 40         Used =             Available = 40          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard-b1-1                      = 40         Used =             Available = 40          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard-b1-16                     = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-b1-16                     = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard-b1-16                     = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard-b1-2                      = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-b1-2                      = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard-b1-2                      = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard-b1-4                      = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-b1-4                      = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard-b1-4                      = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard-b1-8                      = 10         Used =             Available = 10          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-b1-8                      = 10         Used =             Available = 10          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard-b1-8                      = 10         Used =             Available = 10          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard-e2-1-count                = 40         Used =             Available = 40          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-e2-1-count                = 40         Used =             Available = 40          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard-e2-1-count                = 40         Used =             Available = 40          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard-e2-1-micro-count          = 2          Used =             Available = 2           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-e2-2-count                = 30         Used = 2           Available = 28          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-e2-2-count                = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard-e2-2-count                = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard-e2-4-count                = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-e2-4-count                = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard-e2-4-count                = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard-e2-8-count                = 10         Used = 2           Available = 8           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard-e2-8-count                = 10         Used =             Available = 10          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard-e2-8-count                = 10         Used =             Available = 10          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard1-1-count                  = 40         Used =             Available = 40          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard1-1-count                  = 40         Used =             Available = 40          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard1-1-count                  = 40         Used =             Available = 40          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard1-16-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard1-16-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard1-16-count                 = 5          Used =             Available = 5           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute             vm-standard1-2-count                  = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> compute             vm-standard1-2-count                  = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> compute             vm-standard1-2-count                  = 30         Used =             Available = 30          SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> compute-management  config-count                          = 200        Used =             Available =             SCOPE=REGION
--> compute-management  pool-count                            = 50         Used =             Available =             SCOPE=REGION
--> container-engine    cluster-count                         = 3          Used =             Available =             SCOPE=REGION
--> container-engine    node-count                            = 1000       Used =             Available =             SCOPE=REGION
--> data-science        model-count                           = 1000       Used =             Available = 1000        SCOPE=REGION
--> data-science        notebook-session-count                = 30         Used =             Available = 30          SCOPE=REGION
--> data-science        project-count                         = 1000       Used =             Available = 1000        SCOPE=REGION
--> data-transfer       active-appliance-count                = 4          Used =             Available =             SCOPE=REGION
--> data-transfer       appliance-count                       = 1          Used =             Available =             SCOPE=REGION
--> data-transfer       job-count                             = 1          Used =             Available =             SCOPE=REGION
--> database            adb-free-count                        = 2          Used =             Available =             SCOPE=REGION
--> database            adw-ocpu-count                        = 128        Used =             Available =             SCOPE=REGION
--> database            adw-total-storage-tb                  = 128        Used =             Available =             SCOPE=REGION
--> database            atp-ocpu-count                        = 128        Used =             Available =             SCOPE=REGION
--> database            atp-total-storage-tb                  = 128        Used =             Available =             SCOPE=REGION
--> database            bm-dense-io2-52-count                 = 1          Used =             Available = 1           SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> database            bm-dense-io2-52-count                 = 1          Used =             Available = 1           SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> database            bm-dense-io2-52-count                 = 1          Used =             Available = 1           SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> database            vm-block-storage-gb                   = 20480      Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> database            vm-block-storage-gb                   = 20480      Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> database            vm-block-storage-gb                   = 20480      Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> database            vm-standard2-ocpu-count               = 100        Used =             Available = 100         SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> database            vm-standard2-ocpu-count               = 100        Used =             Available = 100         SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> database            vm-standard2-ocpu-count               = 100        Used =             Available = 100         SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> dns                 global-zone-count                     = 1000       Used =             Available =             SCOPE=REGION
--> dns                 steering-policy-attachment-count      = 1000       Used =             Available =             SCOPE=REGION
--> dns                 steering-policy-count                 = 100        Used =             Available =             SCOPE=REGION
--> dns                 tsig-key-count                        = 1000       Used =             Available =             SCOPE=REGION
--> email-delivery      approved-sender-count                 = 10000      Used =             Available = 10000       SCOPE=REGION
--> events              rule-count                            = 50         Used =             Available = 50          SCOPE=REGION
--> faas                application-count                     = 10         Used =             Available =             SCOPE=REGION
--> faas                function-count                        = 20         Used =             Available =             SCOPE=REGION
--> fast-connect        remote-peering-connection-count       = 10         Used =             Available = 10          SCOPE=REGION
--> fast-connect        virtual-circuit-count                 = 10         Used =             Available = 10          SCOPE=REGION
--> filesystem          file-system-count                     = 100        Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> filesystem          file-system-count                     = 100        Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> filesystem          file-system-count                     = 100        Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> filesystem          mount-target-count                    = 2          Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-1
--> filesystem          mount-target-count                    = 2          Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-2
--> filesystem          mount-target-count                    = 2          Used =             Available =             SCOPE=AD     xxxxx:US-ASHBURN-AD-3
--> health-checks       monitor-basic-count                   = 500        Used =             Available =             SCOPE=REGION
--> health-checks       monitor-premium-count                 = 500        Used =             Available =             SCOPE=REGION
--> load-balancer       lb-100mbps-count                      = 15         Used =             Available =             SCOPE=REGION
--> load-balancer       lb-10mbps-micro-count                 = 1          Used =             Available =             SCOPE=REGION
--> load-balancer       lb-400mbps-count                      = 10         Used =             Available =             SCOPE=REGION
--> nosql               read-unit-count                       = 100000     Used =             Available = 100000      SCOPE=REGION
--> nosql               table-size-gb                         = 5000       Used =             Available = 5000        SCOPE=REGION
--> nosql               write-unit-count                      = 40000      Used =             Available = 40000       SCOPE=REGION
--> notifications       subscription-count                    = 10         Used =             Available =             SCOPE=REGION
--> notifications       topic-count                           = 100        Used =             Available =             SCOPE=REGION
--> object-storage      storage-bytes                         = 9223372036854775807 Used =             Available = 9223372036854775807          SCOPE=REGION
--> resource-manager    concurrent-job-count                  = 5          Used =             Available = 5           SCOPE=REGION
--> resource-manager    stack-count                           = 100        Used =             Available = 100         SCOPE=REGION
--> streaming           connect-harness-count                 = 1          Used =             Available =             SCOPE=REGION
--> streaming           partition-count                       = 1          Used =             Available =             SCOPE=REGION
--> vcn                 dhcp-option-count                     = 300        Used =             Available =             SCOPE=REGION
--> vcn                 flow-log-config-count                 = 100        Used =             Available =             SCOPE=GLOBAL
--> vcn                 internet-gateway-count                = 1          Used =             Available =             SCOPE=REGION
--> vcn                 nat-gateway-count                     = 1          Used =             Available =             SCOPE=REGION
--> vcn                 reserved-public-ip-count              = 50         Used =             Available =             SCOPE=REGION
--> vcn                 route-table-count                     = 300        Used =             Available =             SCOPE=REGION
--> vcn                 security-list-count                   = 300        Used =             Available =             SCOPE=REGION
--> vcn                 subnet-count                          = 300        Used =             Available =             SCOPE=REGION
--> vcn                 vcn-count                             = 50         Used = 4           Available = 46          SCOPE=REGION
--> vpn                 cpe-count                             = 10         Used =             Available =             SCOPE=REGION
--> vpn                 ipsec-connection-count                = 4          Used =             Available =             SCOPE=REGION
--> waas                waas-policy-count                     = 50         Used =             Available = 50          SCOPE=REGION

**Comment by adizohar** [comment]
Hi Nullarc, 
I am checking it

**Comment by adizohar** [comment]
I had it fixed deployed on next version
If you want to fix manually
showoci_myservices.py -> __load_limits -> 
Added the pagination:
                        limits = oci.pagination.list_call_get_all_results(limits_client.list_limit_values, tenancy_id, service_name=service.name, sort_by="name").data

**Comment by adizohar** [comment]
It has been fixed and deployed

**Comment by adizohar** [comment]
This issue has been fixed and can be closed
