### ISSUE TITLE
Change the shape 

### ISSUE THREAD

**Issue by fcostabr78** [oracle/oci-python-sdk#224]
Hi Team, will you please provide the method to change the shape of an instance at running?

**Comment by jodoglevy** [comment]
Hi - we'll route this to the Compute team to provide an answer here

**Comment by fcostabr78** [comment]
i will appreciate your help. thanks a lot.

**Comment by fcostabr78** [comment]
@jodoglevy i will appreciate your help. thanks a lot.

**Comment by fcostabr78** [comment]
@jodoglevy any news?

**Comment by jodoglevy** [comment]
@fcostabr78 i'll ping the service team again

**Comment by joekr** [comment]
@fcostabr78 based on the documentation https://docs.cloud.oracle.com/en-us/iaas/Content/Compute/Tasks/resizinginstances.htm#ChangingtheShapeofanInstance it looks like you might want [`UpdateInstance`](https://docs.cloud.oracle.com/en-us/iaas/api/#/en/iaas/20160918/Instance/UpdateInstance)

Based on the python docs here is the model: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.UpdateInstanceDetails.html#oci.core.models.UpdateInstanceDetails and then use https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/client/oci.core.ComputeClient.html#oci.core.ComputeClient.update_instance to update the instance details.

Let me know if that helps. I haven't personally tested it.

**Comment by leorosen** [comment]
https://docs.cloud.oracle.com/en-us/iaas/Content/Compute/Tasks/resizinginstances.htm

**Comment by jpoon** [comment]
One way is [update_instance_and_wait_for_state](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/client/oci.core.ComputeClientCompositeOperations.html#oci.core.ComputeClientCompositeOperations.update_instance_and_wait_for_state) which accepts a [UpdateInstanceDetails](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.UpdateInstanceDetails.html)

**Comment by adizohar** [comment]
Here is a sample code to change shape:

import oci

signer = oci.auth.signers.InstancePrincipalsSecurityTokenSigner()
config = {'region': signer.region, 'tenancy': signer.tenancy_id}

compute_client = oci.core.ComputeClient(config, signer=signer)

update_instance_details = oci.core.models.UpdateInstanceDetails ()
update_instance_details.shape = 'VM.Standard2.2'

instance_id = 'ocid1.instance.oc1.iad.anuwcljsafha7wicby3vav3ewms73qnaeyz5yahlb62pgde2gz6qyvbnsf2a'
compute_client.update_instance(instance_id, update_instance_details)

**Comment by adizohar** [comment]
It has been tested and works, ticket solved
