### ISSUE TITLE
Unable to get "Available" and "Used" data for  "File System Count", "Mount Target Count"  on OCI "File storage" service.

### ISSUE THREAD

**Issue by nadeem-taj73** [oracle/oci-python-sdk#226]
Hi Team, In OCI Console I am unable to get data "Available" and "Used" on  "File System Count", "Mount Target Count"  for OCI "File storage" service. Even the Python SDK is failing to get data. Can anyone let me know where the bug can be raised?

**Comment by amullendore** [comment]
On 3 March 2020 this problem was resolved by the OCI Limits team. The fix applies to both the oci-python-sdk and the OCI Console.
