### ISSUE TITLE
Retry with default back-off strategy throws 'user rate limit exceeded' response

### ISSUE THREAD

**Issue by iavladu** [oracle/oci-python-sdk#227]
sometimes when running API calls using the default retry strategy
`compute_client.list_instances(c.id, retry_strategy=oci.retry.DEFAULT_RETRY_STRATEGY).data`

I get an error like this:
`
oci.exceptions.ServiceError: {'opc-request-id': 'CDDED7A780C1442A9D954E4E1485DF48/FE974EA2D1513FD4D4D9089503F941E9/FB8E409262DD24894EDB035B33E56B87', 'code': 'TooManyRequests', 'message': 'User-rate limit exceeded.', 'status': 429}
`

**Comment by bhagwatvyas** [comment]
Hi @iavladu, the default strategy is just the default, it will not cover all the cases. You can customize the retry strategy via `oci.retry.RetryStrategyBuilder` for your specific case. There is more information about retries in the documentation [here](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/sdk_behaviors/retries.html) and an example to create custom retry strategy [here](https://github.com/oracle/oci-python-sdk/blob/master/examples/retries.py). Please respond here if you have any more questions.

**Comment by iavladu** [comment]
Hi @bhagwatvyas, I thought that it handled all 429 exceptions. 
Yes, in the meantime I have created my custom retry strategy and it seems to be working just fine.
Thanks for the reply.
