### ISSUE TITLE
showoci.py does not handle the case where a user's identitiy provider does not exist

### ISSUE THREAD

**Issue by leoyuen** [oracle/oci-python-sdk#235]
In showoci_service.py:

suggested fix:

                # identity provider
                identity_provider_name = ""
                try:
                    if user.identity_provider_id:
                        identity_provider_name = next(
                            item for item in identity_providers if item.id == user.identity_provider_id).name
                except:
                    identity_provider_name = 'unknown'

**Comment by adizohar** [comment]
Thank you for the suggestions, I added it to the code and will push on next release

**Comment by adizohar** [comment]
Already fixed and deployed, case solved
