### ISSUE TITLE
we need to fetch the Database list based on db_node_id

### ISSUE THREAD

**Issue by kapdevl** [oracle/oci-python-sdk#238]
HI Team
We need to fetch the Database list based on the db_node_id
we got the DB node details using list_db_nodes python sdk  Methods
Based on that db_node_id we want to fetch database details.

Thanks

**Comment by adizohar** [comment]
There are few options, I would recommend the below:

dbnodes = database_client.list_db_nodes(.).data
for dbnode in dbnodes:
....db_system_id = dbnode.db_system_id
....db_node_id = dbnode.id
....compartment_id = dbnode.compartment_id
    
....db_homes = database_client.list_db_homes(compartment_id, db_system_id=db_system_id).data
....for dbh in db_homes:

........databases = database_client.list_databases(compartment_id, db_homes_id=db_homes.id).data
........for db in databases:

**Comment by jodoglevy** [comment]
@kapdevl  does @adizohar 's response resolve your issue? Haven't heard from you in a while. If we don't hear from you in another week or so, I'll assume your issue is resolved and close this

**Comment by kapdevl** [comment]
@jodoglevy 
its work for me
I am closing this ticket
