### ISSUE TITLE
cant able to fetch data showoci.py throwing error

### ISSUE THREAD

**Issue by csetarun2** [oracle/oci-python-sdk#239]
[opc@test1 showoci]$ python showoci.py -c -csv awcapr1

############################################################
#                        showoci.py                        #
############################################################
Authentication : Config File
Config File    : ~/.oci/config
Config Profile : DEFAULT
Version        : 20.3.31
Date/Time      : 2020-04-01 19:06:52
Comand Line    : -c -csv awcapr1
OCI SDK Ver    : 2.12.2

############################################################
#                 Load OCI data to Memory                  #
############################################################
Guide: '.' Compartment, '+' VCN, '-' Subnets, 'a' - auth/notfound

Identity...
--> Tenancy                  <--
Error in ShowOCIService:__load_identity_main: : Error in __load_identity_tenancy: ("Unknown format code 'd' for object of type 'float'",)

##############################
#    Region us-ashburn-1     #
##############################
Identity...
--> Availability Domains     <--
Error in ShowOCIService:__load_identity_availability_domains: Unknown format code 'd' for object of type 'float'
Network...

Error in ShowOCIService:__load_core_network_main: KeyError ('compartments',)

Error in ShowOCIService:__load_data_main: : KeyError ('compartments',)
Traceback (most recent call last):
  File "showoci.py", line 416, in <module>
    execute_extract()
  File "showoci.py", line 120, in execute_extract
    if not data.load_service_data():
  File "/home/opc/oci-python-sdk/examples/showoci/showoci_data.py", line 54, in load_service_data
    return self.service.load_service_data()
  File "/home/opc/oci-python-sdk/examples/showoci/showoci_service.py", line 419, in load_service_data
    return self.__load_data_main()
  File "/home/opc/oci-python-sdk/examples/showoci/showoci_service.py", line 726, in __load_data_main
    self.__load_oci_region_data(region_name)
  File "/home/opc/oci-python-sdk/examples/showoci/showoci_service.py", line 754, in __load_oci_region_data
    self.__load_core_network_main()
  File "/home/opc/oci-python-sdk/examples/showoci/showoci_service.py", line 1387, in __load_core_network_main
    compartments = self.data[self.C_IDENTITY][self.C_IDENTITY_COMPARTMENTS]
KeyError: 'compartments'

Im using oracle Linux 
[opc@test1 showoci]$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.7"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Oracle Linux Server 7.7"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:7:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"
ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.7
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.7

[opc@test1 showoci]$ python
Python 2.7.5 (default, Dec  4 2019, 17:34:13)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by adizohar** [comment]
Please use python3.

**Comment by adizohar** [comment]
Added check for Python3 which will be deployed on 4/13/2020

**Comment by adizohar** [comment]
It has been deployed, only support for python3 in the code
Ticket can be closed

**Comment by adizohar** [comment]
This issue has been resolved
