### ISSUE TITLE
User-rate limit exceeded

### ISSUE THREAD

**Issue by iavladu** [oracle/oci-python-sdk#240]
I have a python script that works a lot like showoci.py - it gets details about resources used in a tenancy.

Now, I have a tenancy where I have many Compartments (and subcompartments) and in most of the cases, I am executing the API calls for each compartment and for each region. 

I end up making many API calls against OCI, so I've created a retry strategy that looks like this:
```
retry_strategy_via_constructor = oci.retry.RetryStrategyBuilder(
   # Make up to 10 service calls
   max_attempts_check=True,
   max_attempts=10,

   # Don't exceed a total of 900 seconds for all service calls
   total_elapsed_time_check=True,
   total_elapsed_time_seconds=900,

   # Wait 100 seconds between attempts
   retry_max_wait_between_calls_seconds=100,

   # Use 2 seconds as the base number for doing sleep time calculations
   retry_base_sleep_time_seconds=2,

   # Retry on certain service errors:
   #
   #   - 5xx code received for the request
   #   - Any 429 (this is signified by the empty array in the retry config)
   #   - 400s where the code is QuotaExceeded or LimitExceeded
   service_error_check=True,
   service_error_retry_on_any_5xx=True,
   service_error_retry_config={
      400: ['QuotaExceeded', 'LimitExceeded', 'TooManyRequests'],
      429: []
   },

   # Use exponential backoff and retry with full jitter, but on throttles use
   # exponential backoff and retry with equal jitter
   backoff_type=oci.retry.BACKOFF_FULL_JITTER_EQUAL_ON_THROTTLE_VALUE
).get_retry_strategy()

```
The problem is that sometimes I still have TooManyRequests errors:
```
{'opc-request-id': '77D03E08C567473CA2AB5DDA665FB968/40713F142F6F8F526540DD82D976CD24/54182ADB8D6AA0F7F90036040C329D62', 'code': 'TooManyRequests', 'message': 'User-rate limit exceeded.', 'status': 429}
```

Is there something in the Retry Strategy Builder that I can improve, or is there a limit on the retry itself?  Should I increase the max_attempts and max_wait_time?

Thanks in advance for your help.

**Comment by adizohar** [comment]
Hi iavladu
I use the showoci script daily to extract big tenancies (with over 200 compartments each on over 8 regions), I use the default retry policy and it works well
Please let me know if you still get errors and on which API ? 
Thank you 
Adi.

**Comment by iavladu** [comment]
Hi @adizohar 
The reason I still had errors, even with the default retry policy or a custom one, was because I was using Threading to try to speed up the process. 
I think that was generating way too many API calls (for big tenancies) for the rate limiter of OCI :)
Without the threading, it works just fine.

**Comment by adizohar** [comment]
@iavladu 
OCI has Denial of service mechanism to prevent attackers
If you are using threads try to run different APIs on each thread

I don't see it as Python or Service issue

**Comment by iavladu** [comment]
thanks, @adizohar - I will try running different APIs on each thread. 
Until now I executed a new thread for each compartment inside every resource - so I was executing the same API basically in multiple threads.
