### ISSUE TITLE
showoci.py does not capture WAF services configuration

### ISSUE THREAD

**Issue by NullARC** [oracle/oci-python-sdk#244]
Latest version 2.12.3 has not switch to capture WAF specific configuration data. It doesn't appear in the JSON output file either.

[opc@pkmjtoolsvm showoci]$ ./showoci.py -a -rg us-ashburn-1 -csv test_ash_8Apr2020 -jf test_ash_8Apr2020.json

############################################################
#                        showoci.py                        #
############################################################
Authentication : Config File
Config File    : ~/.oci/config
Config Profile : DEFAULT
Version        : 20.04.07
Date/Time      : 2020-04-08 09:22:52
Comand Line    : -a -rg us-ashburn-1 -csv test_ash_8Apr2020 -jf test_ash_8Apr2020.json
OCI SDK Ver    : 2.12.3

############################################################
#                 Load OCI data to Memory                  #
############################################################
Guide: '.' Compartment, '+' VCN, '-' Subnets, 'a' - auth/notfound
Filtered by Region      = us-ashburn-1

Identity...
--> Tenancy                  <--  (1) - 00:00:01
--> Compartments             <--  (27) - 00:00:00
--> Users and Groups         <--  (16) - 00:00:04
--> Dynamic Groups           <--  (0) - 00:00:00
--> Policies                 <--  (16) - 00:00:06
--> Providers                <--  (0) - 00:00:00
--> Cost Tracking Tags       <--  (0) - 00:00:00

Announcements...
--> Announcement Items       <-- . (13) - 00:00:01

##############################
#    Region us-ashburn-1     #
##############################
Identity...
--> Availability Domains     <--  (3) - 00:00:01

Network...
--> Virtual Cloud Networks   <-- ........................... (3) - 00:00:04
--> Subnets                  <-- +++ (13) - 00:00:08
--> Network Security Groups  <-- ........................... (11) - 00:00:03
--> Local Peer GWs           <-- +++ (0) - 00:00:09
--> Service Gateways         <-- ........................... (1) - 00:00:06
--> NAT Gateways             <-- ........................... (1) - 00:00:04
--> Dynamic Routing GWs      <-- ........................... (2) - 00:00:03
--> Dynamic Routing GW Attch <-- ........................... (2) - 00:00:02
--> Customer Prem Equipments <-- ........................... (2) - 00:00:03
--> IPSEC tunnels            <-- ........................... (2) - 00:00:04
--> Remote Peer Conns        <-- ........................... (1) - 00:00:03
--> Virtual Circuits         <-- ........................... (0) - 00:00:03
--> Internet Gateways        <-- +++ (3) - 00:00:00
--> Security Lists           <-- +++ (12) - 00:00:08
--> DHCP Options             <-- +++ (4) - 00:00:07
--> Route Tables             <-- +++ (12) - 00:00:08
--> Routed Private IPs       <--  (0) - 00:00:00

Compute...
--> Instances                <-- ........................... (10) - 00:00:14
--> Images                   <-- ........................... (1) - 00:00:07
--> Boot Volumes Attached    <-- ........................... (10) - 00:00:09
--> Volumes Attached         <-- ........................... (10) - 00:00:06
--> Vnics Attached           <-- ........................... (10) - 00:00:10
--> Instance Configurations  <-- ........................... (0) - 00:00:03
--> Instance Pools           <-- ........................... (0) - 00:00:03
--> Autoscaling              <-- ........................... (0) - 00:00:03

Block Storage...
--> Block Volume Groups      <-- ........................... (0) - 00:00:05
--> Boot Volumes             <-- ........................... (14) - 00:00:10
--> Boot Volumes Backups     <-- ........................... (39) - 00:00:03
--> Block Volumes            <-- ........................... (12) - 00:00:07
--> Block Volumes Backups    <--  (83) - 00:00:02

Database...
--> DB Systems               <-- ........................... (11) - 00:00:43
--> Autonomous Databases     <-- ........................... (0) - 00:00:10
--> NOSQL Databases          <-- ........................... (0) - 00:00:04

Load Balancer...
--> Load Balancers           <-- ........................... (1) - 00:00:03
--> Backend Sets             <-- L (2) - 00:00:00

Object Storage...
--> Buckets                  <-- ........................... (49) - 00:00:14

File Storage...
--> File Systems             <-- ........................... (0) - 00:00:45
--> Exports                  <-- ........................... (0) - 00:00:03
--> Mount Targets            <-- ........................... (0) - 00:00:43

Containers...
--> Clusters                 <-- ........................... (0) - 00:00:04
--> Node Pools               <-- ........................... (0) - 00:00:04

Resource Management...
--> Stacks                   <-- ........................... (0) - 00:00:04

Streams...
--> Streams                  <-- ........................... (0) - 00:00:05

Budgets...
--> Budgets                  <-- . (0) - 00:00:01

Monitoring, Notifications and Events...
--> Alarms                   <-- ........................... (5) - 00:00:05
--> Events                   <-- ........................... (0) - 00:00:04
--> Topics                   <-- ........................... (1) - 00:00:06
--> Subscriptions            <-- ........................... (4) - 00:00:04

Edge Services...
--> Healthcheck Ping         <-- ........................... (0) - 00:00:09
--> Healthcheck HTTP         <-- ........................... (0) - 00:00:09
--> DNS Zones                <-- ........................... (0) - 00:01:39
--> DNS Steering Policies    <-- ........................... (0) - 00:00:33

Email Notifications...
--> Senders                  <-- ........................... (0) - 00:00:41
--> Suppressions             <-- ........................... (0) - 00:00:02

Limits and Quotas...
--> Limits                   <-- .................................... (212) - 00:00:30
--> Quotas                   <-- ........................... (0) - 00:00:03

PaaS Native Services...
--> OIC Native               <-- ........................... (0) - 00:00:03
--> OCE Native               <-- ........................... (0) - 00:00:03

Data and AI Services...
--> Data Catalog             <-- ........................... (0) - 00:00:03
--> Data Flow                <-- ........................... (0) - 00:00:02
--> Data Science             <-- ........................... (0) - 00:00:04
--> Data Assistant           <-- ........................... (0) - 00:00:04
--> Big Data Services        <-- ........................... (0) - 00:00:03

API Gateways...
--> API Gateways             <-- ........................... (0) - 00:00:10

Functions...
--> Applications             <-- ........................... (0) - 00:00:06

*** Elapsed Region 'us-ashburn-1' - 00:10:23 ***

**Comment by adizohar** [comment]
I added it to future feature

**Comment by adizohar** [comment]
I implemented it and pushed to internal repository, should be on github next week

**Comment by adizohar** [comment]
Deployed to GitHub (Solved)
