### ISSUE TITLE
AnnouncementSummary does not contain ocid of the Announcement

### ISSUE THREAD

**Issue by BradyWiseman** [oracle/oci-python-sdk#252]
oci.__version__  = '2.14.2'

Using AnnouncementClient.list_announcements() I get a list of AnnouncementSummary.

AnnouncementSummary does not contain the ocid of the actual announcement.

I need the Announcement.affected_resources.  What is the path from list_announcements() to retrieving an Announcement (not AnnouncementSummary) by announcement ocid?

Is there another way of finding the Announcment ocid, so I can retrieve the Announcement directly?

**Comment by adizohar** [comment]
AnnouncementClient.list_announcements 
returns
	oci.announcements_service.models.AnnouncementsCollection
	oci.announcements_service.models.AnnouncementSummary

oci.announcements_service.models.AnnouncementSummary has id

https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/announcements_service/models/oci.announcements_service.models.AnnouncementSummary.html#oci.announcements_service.models.AnnouncementSummary
