### ISSUE TITLE
Usage, Availability data are missing for service LbaaS, prd_fa_pod_app ompartment

### ISSUE THREAD

**Issue by aswinisubra** [oracle/oci-python-sdk#257]
![Screen Shot 2020-05-19 at 3 42 22 PM](https://user-images.githubusercontent.com/5045351/82385826-d64bac00-99e7-11ea-8f3e-0e6840a4f885.png)

Usage, Availability data are missing for service LbaaS, prd_fa_pod_app ompartment across all regions. Please observe the attached image for Frankfurt region. 
The same behavior is observed when using limits client API as well, the values are null.

**Comment by jodoglevy** [comment]
Thanks for reporting, we'll ask the Load Balancing team to take a look

**Comment by adizohar** [comment]
It has been fixed, please let us know if works for you.

**Comment by jodoglevy** [comment]
@aswinisubra since we haven't heard back from you in a while, and @adizohar posted that this is fixed, I'm going to close this. If you are still facing issues please feel free to reopen
