### ISSUE TITLE
Add an option to turn off logging of Request method and request URL

### ISSUE THREAD

**Issue by DanGolding** [oracle/oci-python-sdk#259]
At present, even if `log_requests` is set to `False` in the config, the request method and URL are still logged at the info level. It would be great to allow users to turn this off as it can get quite verbose and ends up cluttering the application side INFO level logs. It seems like it would be a matter of wrapping https://github.com/oracle/oci-python-sdk/blob/master/src/oci/base_client.py#L328 in another if statement.

Also, I could be wrong, but as far as I can tell, the oci package doesn't respect the log level set by the application calling it. So using a [context manager](https://docs.python.org/3/howto/logging-cookbook.html#using-a-context-manager-for-selective-logging) to temporarily set the log lever higher when calling oci functions doesn't stop the INFO level request logs.

**Comment by pelliu** [comment]
Hi @DanGolding , thanks for letting us know the issue, we recently fixed the issue, and provided document [here](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/logging.html) for how to disable the logging, hope this can help, thanks!

**Comment by DanGolding** [comment]
Thanks @pelliu! 

Can I ask from which versions this would work now? Also are you able to link to the PR with the changes for this fix?

**Comment by pelliu** [comment]
Hi @DanGolding , we fixed last week, you can get it from the latest version [2.17.1](https://github.com/oracle/oci-python-sdk/releases/tag/v2.17.1)
