### ISSUE TITLE
OCI API returns LBaaS capacity for lb-8000mbps-count as -1 for OCI regions  ap-sydney-1, ap-osaka-1, ap-melbourne-1, eu-amsterdam-1, ap-tokyo-1, ap-mumbai-1, ca-montreal-1

### ISSUE THREAD

**Issue by nadeem-taj73** [oracle/oci-python-sdk#260]
OCI API returns LBaaS capacity for lb-8000mbps-count as -1 for OCI regions  ap-sydney-1, ap-osaka-1, ap-melbourne-1, eu-amsterdam-1, ap-tokyo-1, ap-mumbai-1, ca-montreal-1. 

The value(total) returned is 2, used is 3 and  available is -1(2-3) as shown below for ap-mumbai-1 region 

# oci limits resource-availability get -c ocid1.tenancy.oc1..xxxxxxxxxxxx --service-name load-balancer  --limit-name lb-8000mbps-count --region ap-mumbai-1
**{
  "data": {
    "available": -1,
    "used": 3
  }
}**

# oci limits value list -c ocid1.tenancy.oc1..xxxxxxxxxxxxxxxxxxxxxxx --service-name load-balancer  --region ap-mumbai-1
{
  "data": [
    {
      "availability-domain": null,
      "name": "lb-100mbps-count",
      "scope-type": "REGION",
      "value": 127
    },
    {
      "availability-domain": null,
      "name": "lb-10mbps-micro-count",
      "scope-type": "REGION",
      "value": 0
    },
    {
      "availability-domain": null,
      "name": "lb-400mbps-count",
      "scope-type": "REGION",
      "value": 10
    },
    **{
      "availability-domain": null,
      "name": "lb-8000mbps-count",
      "scope-type": "REGION",
      "value": 2
    }**
  ]
}

**Comment by lukaszoci** [comment]
Hi all,

The behavior is expected.

The Limit is the limit value set for a particular resource in that tenancy. The Usage is the number of resources actually getting used. And hence, the availability is 'limit - usage'.

When we say availability may be affected by Quotas, it means that if you have a quota policy defined on a particular compartment, then it will limit the availability of resources in that compartment further.

Example:

Consider the values, limit = 2, usage = 3, quota = 1

Then availability would be (total allowed - total used) i. e. ( min(2,1) - 3 ) = -2

Note: This calculation is merely for example purpose. The actual evaluation has to account for quotas and usages from all compartments in the lineage.

The availability MAY be affected by quotas if you have quota policies defined. So even if you don't have them, service limits will still affect your availability.

Please do not confuse "limits" with "total count" of the resources. Limits are set by our CAM team (or the service team themselves) and are allowed to be set BELOW the current usage. That means, when the limits (or even quota policies) are being updated, we do not check if they are BELOW the current usage.

So it is absolutely possible that the limit is lower than the usage. May be in that case, the limit was earlier higher, you created many resources and then the limit was updated to something lower than the current count.

However, it will never be possible that you are allowed to CREATE resources if either the "limit" or the "quota" has already been hit.

**Comment by jodoglevy** [comment]
@nadeem-taj73 I think the above response should answer your question / issue, so I'm closing this. Feel free to reopen if you still have questions on this
