### ISSUE TITLE
Usage2ADW fail with spanish characters

### ISSUE THREAD

**Issue by mgutierr22abr** [oracle/oci-python-sdk#267]
Python 

https://github.com/oracle/oci-python-sdk/blob/master/examples/usage_reports_to_adw/usage2adw.py

Fail if csv file contain spanish character like í 

Error message:
   Processing file reports/usage-csv/0001000000015123.csv.gz - 185468 bytes, 2019-04-02 02:44
   Completed  file reports/usage-csv/0001000000015123.csv.gz - 3529 Rows Inserted
   Total 2 Tags Merged.
   Processing file reports/usage-csv/0001000000015383.csv.gz - 179976 bytes, 2019-04-03 02:45

load_usage_file() - Error Download Usage and insert to database - 'ascii' codec can't decode byte 0xc3 in position 7692: ordinal not in range(128)

**Comment by adizohar** [comment]
Hi Martin, 

Did you use the latest version ? 
can you please share csv file with 2 lines as an example in order to test and fix the code ?

I will add flag to ignore tags

Thank you

**Comment by mgutierr22abr** [comment]
Thanks, and yes, i used the latest version. Sample file sent.

**Comment by adizohar** [comment]
I tested the sample file and it worked properly on my VM.

**Comment by mgutierr22abr** [comment]
It was something on my laptop, i tested on a brand new machine on cloud and on a docker container, both worked.
Thanks Adi.
