### ISSUE TITLE
Unable to pull DB info for dataguarded DB with showoci.py script

### ISSUE THREAD

**Issue by kennymu** [oracle/oci-python-sdk#270]
When I run the showoci.py script it is unable to get DB info for the one DB we have that is in a dataguard relationship.

Error in ShowOCIService:__load_database_dbsystems: {'opc-request-id': '46DDE89FBF1B45158329B6EB3171CE30/4807B228DCEBF3E66664AE64C26894ED/B175E746E22E35FBF7F12F661615DFDA', 'code': 'InvalidParameter', 'message': 'Expected region phx but found region iad', 'status': 400}

I'm not sure if it's because the DBs have the same name or the fact that there is a dataguard relationship.

**Comment by adizohar** [comment]
Hi Kenny
Let me check it and I will revert back with as fix

**Comment by adizohar** [comment]
I fixed the issue, and already commit , it will deployed to OCI Github next tuesday
I uploaded for you temporary to https://github.com/adizohar/showoci
Please let me know if working
Thank you

**Comment by kennymu** [comment]
I had to upgrade the oci package for python3 to version 2.18, but it is now working.  When I run python3 showoci.py -d it is able to successfully pull info for the 2 dataguarded DBs.

Thank you for the quick response and fix!  I’m using this to pull an inventory of everything we have in OCI for reporting purposes.  I briefly looked at trying to fix it myself, but my python skills aren’t as good as my bash or perl or powershell skills.

Thanks!
Kenny

Kenny Mulkearns
Systems Engineer III, Storage, Cloud
T: (757) 223-6897

**Comment by adizohar** [comment]
Welcome Kenny

Do we need to leave this ticket open if all fixed ?

**Comment by kennymu** [comment]
Nope, feel free to close.  Thanks for the help and quick fix.

-Kenny

Kenny Mulkearns
Systems Engineer III, Storage, Cloud
T: (757) 223-6897

**Comment by jodoglevy** [comment]
Closing per discussion above
