### ISSUE TITLE
Virtual network client list_subnets signature incompatible

### ISSUE THREAD

**Issue by EpicWink** [oracle/oci-python-sdk#271]
Calling `oci.core.virtual_network_client.VirtualNetworkClient.list_subnets` in v2.18 raises a TypeError due to an incompatible change to the signature of `list_subnets`, where it now only takes [exactly 1](https://github.com/oracle/oci-python-sdk/blob/1358ba2759b9b61adee1395be6b33150bc268d8e/src/oci/core/virtual_network_client.py#L11796) positional argument instead of [exactly 2](https://github.com/oracle/oci-python-sdk/blob/2fdccece8c6d946b068e6e1434c71050a9655339/oraclebmc/core/virtual_network_client.py#L1870) in v2.17. Our systems assume OCI follows semantic versioning, where incompatible changes are only made between major releases (eg v3), so right now we have to pin to v2.17.

Our intermediate solution is to change our `vcn_id` argument to be passed by keyword, but I suspect that other functions have also changed their signature in the minor release.

The ideal fix for this specific issue is to make the signature become:
```python
def list_subnets(self, compartment_id, vcn_id=missing, **kwargs):
   ...
```

**Comment by jodoglevy** [comment]
Hi @EpicWink - if you look at the [changelog](https://github.com/oracle/oci-python-sdk/blob/master/CHANGELOG.rst#2180---2020-07-14) for the v2.18.0 release you will see this breaking change is mentioned.

The OCI Python SDK follows this versioning pattern:
- If no breaking change is made in a new version, the patch version number is incremented
- If a minor breaking change is made in a new version, the minor version number is incremented
- If a major breaking change is made in a new version, the major version number is incremented

I would suggest reviewing the changelog for any major or minor version bump to know in advance of upgrading your OCI Python SDK package if there are any breaking changes that will affect you.
