### ISSUE TITLE
Unable to process JSON input

### ISSUE THREAD

**Issue by fcostabr78** [oracle/oci-python-sdk#273]
Hi,

im try to use the follow code:

end_at = str(datetime.now()) + "T00:00:00.000Z"
start_at = str(datetime.now() - timedelta(days=20)) + "T00:00:00.000Z"

usage_client = UsageapiClient(config)

usage_detail = RequestSummarizedUsagesDetails()
usage_detail.tenant_id = 'ocid1.tenancy.oc1..aaaaaaaaqqzek25x6oc72....zcual27......jopna'
usage_detail.time_usage_ended = end_at
usage_detail.time_usage_started = start_at
usage_detail.granularity  = "DAILY"

response = usage_client.request_summarized_usages(usage_detail)

but i get : oci.exceptions.ServiceError: {'opc-request-id': '096A141A88944C9AA7B0CFC703B89855/8A4CB3FA4D9D63B18F91CDAD562D530F/FB9366A51D77638033C6E1AEA011C20B', 'code': 'InvalidParameter', 'message': 'Unable to process JSON input', 'status': 400}

i can fix?

**Comment by fcostabr78** [comment]
fixed!

**Comment by Sushanth-CCNSDev** [comment]
Hello @fcostabr78 we are trying out the above code snippet but still getting error, is this an issue that still exists and any workaround available for making this API work.
