### ISSUE TITLE
No filters on AuditClient API

### ISSUE THREAD

**Issue by kk-hiraskar** [oracle/oci-python-sdk#277]
AuditClient list_events API, gives huge data, seems no option to apply filter at source request to get only required data.

When called with pagination, takes lot of time to list just 1 days data, as it includes many events, and goes through 100s of pages.

Please provide filter on type, 
and also limit option also not available as of now to control the results.

**Comment by adizohar** [comment]
Hi kk-hiraskar
you should use the logging search method which replace the audit, below an example
```
import oci

config_file="~/.oci/config"
config = oci.config.from_file(config_file,"DEFAULT")

client = oci.loggingsearch.LogSearchClient(config)
# search language = https://docs.oracle.com/en-us/iaas/Content/Logging/Reference/query_language_specification.htm
search_objects = oci.loggingsearch.models.SearchLogsDetails(
    time_start="2020-12-29T00:00:00.00Z",
    time_end="2020-12-29T03:00:00.00Z",
    search_query="search \"ocid1.compartment.oc1..aaaaaaaa24bxxxremoved/_Audit\" | (data.request.action='POST' or data.request.action='GET') and (type='com.oraclecloud.ComputeApi.ListInstances') | sort by datetime desc"
)

data=client.search_logs(search_logs_details=search_objects).data
for i in data.results:
    print (i.data['logContent']['id'])
```

**Comment by kk-hiraskar** [comment]
Thanks for the info.. I will try this logging search method.
