### ISSUE TITLE
upgrade cryptography to 2.0.3

### ISSUE THREAD

**Issue by ajoyac** [oracle/oci-python-sdk#28]
Is it possible to upgrade the library  cryptography 1.8.2 to cryptography 2.0.3 this since the updated version have installation support from many Linux devices and it would made easier to install in different environments easier.

AJ

**Comment by mross22** [comment]
Thanks for calling this out, that does look like a useful change for us to pick up.  Give me a little time to investigate the exact implications of upgrading and I'll get back to you on this one (for example it looks like we would be dropping support for macOS 10.7 & 10.8 by upgrading).

In the meantime we just added a script that should simplify the install process across operating systems. We will be adding formal documentation next week but in the meantime you can just run the following bash command to install the CLI (it will handle installing platform specific dependencies required for building cryptography among other things):

```bash
curl -L "https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh" | bash
```

**Comment by nathan-vu** [comment]
Just looping back on this - the SDK now has a dependency on cryptography 2.1.3
