### ISSUE TITLE
Update loadbalancer listener is not working as expected

### ISSUE THREAD

**Issue by Pramodnair84** [oracle/oci-python-sdk#285]
In below document it is mentioned that we need to pass the update attributes for LBR listener.
https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/load_balancer/models/oci.load_balancer.models.SSLConfigurationDetails.html#oci.load_balancer.models.SSLConfigurationDetails

In oci.load_balancer.models.UpdateListenerDetails, i am getting below error for using "certificate_name". My requirement is to read the LBR metadata  and update attributes as per my requirement but here due to change from pascal_case in metadata to camelCase in Post is causing failure in updates. This is no where mentioned in the read me document or in example script. 

Failed to update listener with my_ruleset, {'status': 400, 'message': u'Unrecognized field "certificate_name" (class com.oracle.pic.lb.v20170115.model.SSLConfigurationDetails$Builder), not marked as ignorable (6 known properties: "certificateName", "serverOrderPreference", "cipherSuiteName", "verifyDepth", "protocols", "verifyPeerCertificate"])\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 221] (through reference chain: com.oracle.pic.lb.v20170115.model.UpdateListenerDetails$Builder["sslConfiguration"]->com.oracle.pic.lb.v20170115.model.SSLConfigurationDetails$Builder["certificate_name"])', 'code': u'InvalidParameter', 'opc-request-id': 'Bfasdfsafa'}

**Comment by adizohar** [comment]
Hi Pramodnair84

Can you please provide the code you are using
You need to generate ssl configuration modal and then listener update modal.

Please check the documentation - https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/load_balancer/client/oci.load_balancer.LoadBalancerClient.html#oci.load_balancer.LoadBalancerClient.update_listener
And the loadbalancer listener update modal - https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/load_balancer/models/oci.load_balancer.models.UpdateListenerDetails.html#oci.load_balancer.models.UpdateListenerDetails
and the ssl info - https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/load_balancer/models/oci.load_balancer.models.SSLConfigurationDetails.html#oci.load_balancer.models.SSLConfigurationDetails

**Comment by Pramodnair84** [comment]
To workaround this issue, i had to copy the attibute_value from pascal_case attibute to CamelCase and then delete it and passed the updated config to UpdateListenerDetails api. Please let me know if there's better way to do it.
```
    def _update_lbr_listner_ruleset(self, lbr):
        listeners = lbr.listeners # get listener details from lbr metadata
        for listener in listeners:
            listener = json.loads(repr(listeners[listener]))
            try:
                # WORKAROUND
                # remove 'name' from the listener dict
                if 'name' in listener:
                    del listener['name']

                # rename key: idle_timeout to idleTimeout in connection_configuration
                if listener['connection_configuration']['idle_timeout']:
                    time_out = listener['connection_configuration']['idle_timeout']
                    del listener['connection_configuration']['idle_timeout']
                    listener['connection_configuration']['idleTimeout'] = time_out

                # ssl_configuration attributes in lbr metadata is in pascal_case but UpdateListenerDetails
                # method expects attributes in camelCase
                for attr in listener['ssl_configuration']:
                    if attr in config_file['listener_certs_attributes']:
                        listner_post_att = config_file['listener_certs_attributes'][attr] # i have stored attributes in config file for attribute lookup
                        listener['ssl_configuration'][listner_post_att] = listener['ssl_configuration'][attr]
                        del listener['ssl_configuration'][attr]
                listener['rule_set_names'].append('NEW_RULE_SET_NAME')
                self.load_balancer_client_composite_ops.update_listener_and_wait_for_state(
                        oci.load_balancer.models.UpdateListenerDetails(**(listener)),
                        lbr.id, listener, wait_for_states=[oci.load_balancer.models.WorkRequest.LIFECYCLE_STATE_SUCCEEDED]
                )
                
            except Exception as e:
                logger.error("{0}: Failed to update listener with NEW ruleset, {1}".format(
                    lbr.display_name, e))

```

**Comment by adizohar** [comment]
Hi, you did well, the alternative is to specify manually all the parameters 
Happy new year.

**Comment by KartikShrikantHegde** [comment]
Hi @Pramodnair84 ,

I will be closing this issue for now based on your workaround and Adi's response. If you are still hitting the problem, please feel free to reopen this.

Thanks.
