### ISSUE TITLE
missing util from tests.integ 

### ISSUE THREAD

**Issue by linqing2004** [oracle/oci-python-sdk#29]
in the tests/conftest.py, it requires:
from tests.integ import util
from tests.util import get_resource_path

But there is no such file under tests/integ.  Please add the missing file.

Thanks,
Qing

**Comment by mross22** [comment]
Thanks for reporting, I will add this in as part of our next release.

**Comment by nathan-vu** [comment]
We've added the missing files in our latest release, and we've also updated our testing instructions: https://github.com/oracle/oci-python-sdk#running-tests
