### ISSUE TITLE
Kubernetes_version returning the avilable latest version only not the actual cluster version. 

### ISSUE THREAD

**Issue by rajibmitra** [oracle/oci-python-sdk#296]
when we do `get_kubernetes_version` from container_engine module , we are getting the available latest version not the actual cluster master version.

**Comment by xmattstrongx** [comment]
@rajibmitra 
That function is meant to list back all of the available versions as you are seeing
https://github.com/oracle/oci-python-sdk/blob/master/examples/container_engine.py#L243-L247
Under the hood it is hitting this API and filtering out on the available versions.
https://docs.cloud.oracle.com/en-us/iaas/api/#/en/containerengine/20180222/ClusterOptions/
A use case for this is if someone wants to script cluster creation and always specify the latest version..

It sounds like you want to get the specific kubernetes master version of your cluster. 
What you will want to use is `get_cluster`
https://github.com/oracle/oci-python-sdk/blob/master/src/oci/container_engine/container_engine_client.py#L541
This will hit this API
https://docs.cloud.oracle.com/en-us/iaas/api/#/en/containerengine/20180222/Cluster/GetCluster
and return this model
https://docs.cloud.oracle.com/en-us/iaas/api/#/en/containerengine/20180222/Cluster/

You can use some python similar to the `get_cluster_version` function to grab the `kubernetesVersion` from the `get_cluster` function.

Hope this helps!

**Comment by jodoglevy** [comment]
Hi @rajibmitra - it seems like this question has been answered. Are you ok if I close this?

**Comment by rajibmitra** [comment]
yes, please go ahead and close this. Thank you.
