### ISSUE TITLE
Which module/method can provide OCPU/ list ShapeConfig and Memory for VM.Standard.E3.Flex

### ISSUE THREAD

**Issue by vburamdo** [oracle/oci-python-sdk#305]
Hello Team,

We were unable to find required `method`  in below documentation <https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/> to Fetch ShapeConfig/OCPU/Memory allocated to VM.Standard.E3.Flex Shapes.

please do let us know how we can fetch these details.

Thanks.

**Comment by adizohar** [comment]
Please use get_instance 
Modal - https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.Instance.html#oci.core.models.Instance

Then check the attribute shape_config

You can check showoci in the example

For your info

**Comment by vburamdo** [comment]
i tried the following, but it didn't displayed the shape_config details.

>>ComputeClient.get_instance(instance_id="ocid1.instance.oc1.iad.xxxxxxxxxxxx").data

**Comment by vburamdo** [comment]
`>>> ComputeClient.get_instance(instance_id="ocid1.instance.oc1.iad.xxxxxxxxx").data
{
  "agent_config": {
    "is_management_disabled": false,
    "is_monitoring_disabled": false
  },
  "availability_domain": "sBOY:US-ASHBURN-AD-1",
  "compartment_id": "xxxxxxxxxx",
  "dedicated_vm_host_id": null,
  "defined_tags": {
    "xxxxx": {
      "APP": "TEST",
      "LCM": "Implementation",
      "MANAGED": "True",
      "TIER": "NONPROD",
      "TYPE": "PvtMT"
    },
    "Oracle-Tags": {
      "CreatedBy": "xxxxxxxxxx",
      "CreatedOn": "2020-09-14T09:31:56.859Z"
    }
  },
  "display_name": "xxxxxxxx",
  "extended_metadata": {},
  "fault_domain": "FAULT-DOMAIN-3",
  "freeform_tags": {},
  "id": "xxxxxxxxx",
  "image_id": "xxxxxxxxx",
  "ipxe_script": null,
  "launch_mode": "NATIVE",
  "launch_options": {
    "boot_volume_type": "PARAVIRTUALIZED",
    "firmware": "UEFI_64",
    "is_consistent_volume_naming_enabled": true,
    "is_pv_encryption_in_transit_enabled": false,
    "network_type": "VFIO",
    "remote_data_volume_type": "PARAVIRTUALIZED"
  },
  "lifecycle_state": "RUNNING",
  "metadata": {
    "ssh_authorized_keys": "xxxxxxxxxx"
  },
  "region": "iad",
  "shape": "VM.Standard.E3.Flex",
  "source_details": {
    "boot_volume_size_in_gbs": null,
    "image_id": "ocid1.image.oc1.iad.xxxxxxxxxx",
    "kms_key_id": null,
    "source_type": "image"
  },
  "system_tags": {},
  "time_created": "2020-09-14T09:31:57.721000+00:00",
  "time_maintenance_reboot_due": null
}`

**Comment by adizohar** [comment]
Please update the oci version

python3 -m pip upgrade oci

**Comment by vburamdo** [comment]
thanks, after upgrading oci able to get shape_config details.

**Comment by jodoglevy** [comment]
Seems like this issue is resolved, so closing this
