### ISSUE TITLE
Unable to list all the files in a folder

### ISSUE THREAD

**Issue by ftrojan** [oracle/oci-python-sdk#307]
I am using the `list_objects` function to get list of all files in a folder (https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/object_storage/client/oci.object_storage.ObjectStorageClient.html#oci.object_storage.ObjectStorageClient.list_objects). I know there are more than 1000 files there, but I always get only 1000 elements in the list. There is a parameter `limit`(the maximum number of items to return), but if I set it to more than 1000, I get an error saying that the maximum value of this parameter is 1000.

How can I get the list of all the files in my folder?

**Comment by adizohar** [comment]
There are few options, but the easiest is to use the pagination

objects = oci.pagination.list_call_get_all_results(object_client.list_objects, ...)

**Comment by jodoglevy** [comment]
Pagination is the right answer here. Closing this ticket. Please let us know if you are still having issues
