### ISSUE TITLE
Missing unit from tests/unit

### ISSUE THREAD

**Issue by kaslin** [oracle/oci-python-sdk#31]
After copying the util.py file into tests/integ, I encountered this error which indicates that a file called "unit" is missing from "tests":

============================================================================ test session starts ============================================================================
platform darwin -- Python 2.7.13, pytest-3.0.2, py-1.4.34, pluggy-0.3.1
rootdir: /Users/kfields/oci-python-sdk, inifile: 
plugins: catchlog-1.2.2

======================================================================= no tests ran in 0.00 seconds ========================================================================
ERROR: file not found: tests/unit
ERROR: InvocationError: '/Users/kfields/oci-python-sdk/.tox/py27/bin/py.test tests/unit tests/integ -s'
__________________________________________________________________________________ summary __________________________________________________________________________________
ERROR:   py27: commands failed

**Comment by nathan-vu** [comment]
Sorry for not ack-ing this earlier. 

The missing files have been added in our latest release and we also updated our testing instructions: https://github.com/oracle/oci-python-sdk#running-tests
