### ISSUE TITLE
SDK returns error when creating a global resource outside of home region

### ISSUE THREAD

**Issue by kaslin** [oracle/oci-python-sdk#32]
In the UI, the console detects your home region and automatically runs the command through your home region.  The SDK acknowledges your home region, and fails with a message that you should run the command in your home region. Even though the resource (a user deployed with the user_crud.py example) will be populated globally.

I expect the sdk to behave in the same way as the console and run the command through my home region for me.

python user_crud.py 
Creating a new user 'python-sdk-example-user' in compartment u'ocid1.tenancy.oc1..aaaaaaaaiqvbw46md3vnh3luutu5uyxar2xwb3z3ybaozlnnoervfbl57p2q'
Traceback (most recent call last):
  File "user_crud.py", line 24, in <module>
    user = identity.create_user(request)
  File "/Users/kfields/oci-python-sdk/src/oci/identity/identity_client.py", line 724, in create_user
    response_type="User")
  File "/Users/kfields/oci-python-sdk/src/oci/base_client.py", line 139, in call_api
    return self.request(request)
  File "/Users/kfields/oci-python-sdk/src/oci/base_client.py", line 165, in request
    self.raise_service_error(response)
  File "/Users/kfields/oci-python-sdk/src/oci/base_client.py", line 245, in raise_service_error
    message)
oci.exceptions.ServiceError: {'status': 403, 'message': u'Please go to your home region PHX to execute CREATE, UPDATE and DELETE operations.', 'code': u'NotAllowed', 'opc-request-id': '97AD7E6B313647AA922ED6C7FE080766/F7E7AE847FDC8CDDD67CCD70C3171C63/220AE55995EF48E4859F157E1F6B979F'}

**Comment by jodoglevy** [comment]
Thanks, we'll look into this and get back to you.

**Comment by arthall** [comment]
The user_crud.py example has been updated to run all the user operations in the home region.  The example shows how to find the home region and set the identity client to use the home region.
