### ISSUE TITLE
list_vnic_attachments does not include primary vnic of compute instances in compartment.

### ISSUE THREAD

**Issue by bathax** [oracle/oci-python-sdk#327]
I'm attempting to parse all vnics in a compartment and match them to the respective compute instance list so:

```
for instance in instances:
            print("Processing instance %s" % instance.display_name)
            vnics = []
            subnet_name = ""
            for vnic_attachment in vnic_attachments:
                if vnic_attachment.instance_id == instance.id:
                    private_ips, public_ips = self.get_ips(
                        vnic_attachment,
                        private_ips_list,
                        public_ips_list)

                    vnics.append({
                        'private_ips': list(set(private_ips)),
                        'public_ips': list(set(public_ips))
                    })
```
However list_vnic_attachments does not include the primary vnic of the compute instance.  Is there a better way to do this or is this a bug?

**Comment by adizohar** [comment]
Hi Bathax
vnic_attachments has all the vnics, it could be your vnic is in different compartment
Please take a look at my code https://github.com/oracle/oci-python-sdk/tree/master/examples/showoci
I extract all vnics and load to json cache, then search when needed
For your info
Adi.

**Comment by bathax** [comment]
Hey Adi,

I think I'm having issues with https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/client/oci.core.VirtualNetworkClient.html#oci.core.VirtualNetworkClient.list_public_ips

I have some compartments that only have regional subnets but also have ephmeral AD IPs (public ips attached to private ips).  I was originally iterating through my subnets to get the ADs, but I can't do that if I only have regional subnets.  I'm trying to figure out the format for them but I'm getting errors however I try.
