### ISSUE TITLE
approximate_size in get_bucket is null 

### ISSUE THREAD

**Issue by rajibmitra** [oracle/oci-python-sdk#330]
When checking the get_buckets method I am seeing 
 "approximate_count": null,
  "approximate_size": null which is not expected behaviour.

**Comment by adizohar** [comment]
When querying the bucket you need to specify the fields
 bucket = object_storage.get_bucket(namespace_name, bucket_name, fields=['approximateCount', 'approximateSize']).data

**Comment by jodoglevy** [comment]
@rajibmitra what @adizohar commented above is correct - have you tried doing that, and if so has it resolved your issue? Wondering if this issue can be closed.

**Comment by jodoglevy** [comment]
Closing this issue due to lack of response, and answer provided above

**Comment by kk-hiraskar** [comment]
Is it possible to include this info also in document itself?
