### ISSUE TITLE
OptimizerClient.list_recommendations name not matching as shown in OCI concole

### ISSUE THREAD

**Issue by kk-hiraskar** [oracle/oci-python-sdk#336]
Hi,
`OptimizerClient.list_recommendations` are showing names different than as shown in OCI console's Cloud Advisor page.

> ![image](https://user-images.githubusercontent.com/19647561/113871439-88db5780-97d0-11eb-95a1-4f346c31b2fc.png)

**___few examples:___**
| as from **`list_recommendations` > `name`** | as in **OCI console Cloud Advisor page** |
| -- | -- |
| cost-management-autonomous-database-underutilized-name | Downsize underutilized ADW and ATP databases |
| cost-management-object-storage-enable-olm-name | Enable object lifecycle management |
| cost-management-block-volume-attachment-name | Delete unattached block volumes |
| cost-management-compute-host-underutilized-name | Downsize underutilized compute instances |

**can we fetch these mappings from any other way ?**

**Comment by yifnfan** [comment]
Hi @kk-hiraskar  - Thanks for the information.

Actually, the names on SDK and console are similar. The only difference which may raise your confusion is that the SDK name contains a category name as a prefix, but on console, we have an extra line to show the category name and the recommendation name on the console doesn't attach the category name with it. For example, one of our category names is cost management. From the suffix, the name is similar on SDK and console and users can easily identify the recommendation the name represents.

Hope that can resolve your concern~
