### ISSUE TITLE
Update pyOpenSSL dependency

### ISSUE THREAD

**Issue by ilian** [oracle/oci-python-sdk#339]
I am wondering if the version constraint of `pyOpenSSL` is still required:
https://github.com/oracle/oci-python-sdk/blob/d7e2881e9c9ca10682d4140fcb3c18132592793c/setup.py#L35-L36

The constraint was added in 3ffac62aeebecd8b9b9beb8408bcebd5e5da924f back when  `cryptography` was pinned at version 2.8:
https://github.com/oracle/oci-python-sdk/blob/3ffac62aeebecd8b9b9beb8408bcebd5e5da924f/setup.py#L35-L36

Now that the `cryptography` package has been updated to at least version 3.2.0, the breaking change of `pyOpenSSL` version 20.0.0 listed in its changelog ("The minimum cryptography version is now 3.2.") does no longer conflict with the version of `cryptography` used by `oci`.

Is there any other reason why the version of `pyOpenSSL` remains pinned or can we unpin the version constraint?

**Comment by bhagwatvyas** [comment]
Thanks for pointing this out @ilian. We're running tests from our end for with the new versions.

**Comment by jhult** [comment]
@bhagwatvyas, any updates on this?

**Comment by pabs3** [comment]
@bhagwatvyas: `pyOpenSSL` is now at version 22 and cryptography is up to 37.0.2, has there been any more work on this issue? Please unpin the `pyOpenSSL` version constraint and expand the versions for `cryptography`.

**Comment by pabs3** [comment]
BTW, I filed #419 about widening the `cryptography` version range.

**Comment by github-anurag** [comment]
@jhult 
We have picked this task up and are evaluating on removing the upper-bound for `pyOpenSSL` in OCI Python SDK. We will update you soon on its progress.

**Comment by github-anurag** [comment]
@jhult we increased the upper bound for pyOpenSSL. Will evaluate a bit more on removing it in future release
