### ISSUE TITLE
not update 1.3.8 docs

### ISSUE THREAD

**Issue by ajoyac** [oracle/oci-python-sdk#34]
the documentation has not been updated  example: database services client documentation is missing at docs site

**Comment by jodoglevy** [comment]
Is this what you're looking for: http://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/index.html#database ?

**Comment by ajoyac** [comment]
yes, exactly, that was not available 5 days ago, but its good to finally appear.
Regards
