### ISSUE TITLE
Compute :-Capacity Reservation  :- under this we need to fetch the Capacity Configurations Details

### ISSUE THREAD

**Issue by kapdevl** [oracle/oci-python-sdk#340]
Hi 
I am using this method to find Capacity Reservation:-
list_compute_capacity_reservations_response = core_client.list_compute_capacity_reservations(tenancy)

After this i need to  get the details of capacity configuration.
how we can get Capacity Configurations Details is there any method/API available to fetch the details

**Comment by adizohar** [comment]
hi 
For each item you should call - get_compute_capacity_reservation(capacity_reservation_id, **kwargs)

It will have:
	instance_reservation_configs (list[oci.core.models.InstanceReservationConfig])

**Comment by kapdevl** [comment]
Thanks
i got the details
