### ISSUE TITLE
Use ranges in `setup.py` dependencies

### ISSUE THREAD

**Issue by vkomarov-r7** [oracle/oci-python-sdk#343]
In the `setup.py` file, both configparser as well as cryptography are both pinned to absolute versions. This causes version conflicts when we use the `oci` library in our codebase. Would it be possible to move to using a minimum range instead?

e.g.: `cryptography>=3.3.2`

https://github.com/oracle/oci-python-sdk/blob/master/setup.py#L34-L35

**Comment by bhagwatvyas** [comment]
Hi @vkomarov-r7, the reason that the cryptography dependency is set to v3.3.2 is we have tested with, and have compliance and security approval to use v3.3.2. We are evaluating our use of configparser and may not use it in the future.

**Comment by vkomarov-r7** [comment]
Hey @bhagwatvyas: Thanks for your response.

Please be aware that pinning versions in this manner _is_ itself a security vulnerability. By pinning the version of cryptography to a particular version, users of this library are unable to upgrade their `cryptography` versions until you do.

For example, the currently released version of `cryptography` is `3.4.7` which comes bundled with [OpenSSL 1.1.1k](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#347---2021-03-25), which includes [security updates](https://www.openssl.org/news/changelog.html#openssl-111) that users cannot take as a result of this explicit pinning.

If possible, please reconsider your policy on this. Here's a list of how other popular OSS packages use the `cryptography` package:

* [paramiko](https://github.com/paramiko/paramiko/blob/33daa8e541cb91cdee01a085c368e1b388472e6a/setup.py#L91)
* [pyOpenSSL](https://github.com/pyca/pyopenssl/blob/d531c6a6d9affe63a91a38cfe6d8b8535de28cbd/setup.py#L99)
* [azure-identity](https://github.com/Azure/azure-sdk-for-python/blob/24eb609945a0f2cdcd31831e7ddf25ad939e591a/sdk/identity/azure-identity/setup.py#L77)

**Comment by bhagwatvyas** [comment]
Hi @vkomarov-r7, the latest version of the OCI Python SDK, v 2.40.1, allows a range for cryptography versions, starting from 3.2.1 up to 3.4.7.

**Comment by pabs3** [comment]
Looks like this issue can be closed now, all the dependencies in setup.py have version ranges.
