### ISSUE TITLE
More descriptive parameter documentation and detailed examples

### ISSUE THREAD

**Issue by ajaravin** [oracle/oci-python-sdk#348]
For example in the [documentation](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/data_science/client/oci.data_science.DataScienceClient.html#oci.data_science.DataScienceClient.create_model_artifact) for create_model_artifact, the parameter content_disposition has description

```md
content_disposition (str) – (optional) The content disposition of the body.
```

and in the [example](https://docs.oracle.com/en-us/iaas/tools/python-sdk-examples/2.38.2/datascience/create_model_artifact.py.html)

```python
create_model_artifact_response = data_science_client.create_model_artifact(
    model_id="ocid1.test.oc1..<unique_ID>EXAMPLE-modelId-Value",
    model_artifact=b"CeFxezDJd1FTtnsgRRSk",
    opc_request_id="TRPNVZ1CUP0DWIFBNNOS/OpcRequestIdExample/<unique_ID>",
    opc_retry_token="EXAMPLE-opcRetryToken-Value",
    content_disposition="EXAMPLE-contentDisposition-Value")
```

It is not very clear as in what format the content disposition should be specified. It'd be helpful if the documentation and examples are more descriptive.

**Comment by ajaravin** [comment]
Sure @jodoglevy , I'll create new issues with suitable descriptions.

Thanks @jrgauthier01

**Comment by jodoglevy** [comment]
@jrgauthier01 has informed me that the needed documentation improvements have been made, and examples added, for Data Science service, so closing this
