### ISSUE TITLE
showoci.py - filter region not working

### ISSUE THREAD

**Issue by martinberger-ch** [oracle/oci-python-sdk#352]
Hello

Can you write some filter examples in the README? I want to filter by region, for example eu-zurich-1 - but it's not working:

`[opc@tenant-usage-vm showoci]$ ./showoci.py -rg eu-zurich-1
usage: showoci.py [-h] [-a] [-ani] [-an] [-api] [-b] [-c] [-cn] [-d] [-e]
                  [-edge] [-f] [-fun] [-i] [-ic] [-isc] [-l] [-lq] [-m] [-n]
                  [-o] [-paas] [-dataai] [-rm] [-s] [-sec] [-nobackups] [-so]
                  [-mc] [-nr] [-ip] [-dt] [-t PROFILE] [-p PROXY] [-rg REGION]
                  [-cp COMPART] [-cpr COMPART_RECUR] [-cpath COMPARTPATH]
                  [-tenantid TENANTID] [-cf CONFIG] [-csv CSV] [-csv_nodate]
                  [-jf JOUTFILE] [-js] [-sjf SJOUTFILE] [-cachef SERVICEFILE]
                  [-caches] [--version]

optional arguments:
  -h, --help           show this help message and exit
  -a                   Print All Resources
  -ani                 Print All Resources but identity
  -an                  Print Announcements
  -api                 Print API Gateways
  -b                   Print Budgets
  -c                   Print Compute
  -cn                  Print Containers
  -d                   Print Database
  -e                   Print EMail
  -edge                Print Edge, DNS Services and WAAS policies
  -f                   Print File Storage
  -fun                 Print Functions
  -i                   Print Identity
  -ic                  Print Identity Compartments only
  -isc                 Skip Identity User Credential extract
  -l                   Print Load Balancer
  -lq                  Print Limits and Quotas
  -m                   Print Monitoring, Notifications and Events
  -n                   Print Network
  -o                   Print Object Storage
  -paas                Print PaaS Platform Services - OIC OAC OCE OCVS
  -dataai              Print - D.Science, D.Catalog, D.Flow, ODA and BDS
  -rm                  Print Resource management
  -s                   Print Streams
  -sec                 Print Security and Logging
  -nobackups           Do not process backups
  -so                  Print Summary Only
  -mc                  exclude ManagedCompartmentForPaaS
  -nr                  Not include root compartment
  -ip                  Use Instance Principals for Authentication
  -dt                  Use Delegation Token (Cloud shell)
  -t PROFILE           Config file section to use (tenancy profile)
  -p PROXY             Set Proxy (i.e. www-proxy-server.com:80)
  -rg REGION           Filter by Region
  -cp COMPART          Filter by Compartment Name or OCID
  -cpr COMPART_RECUR   Filter by Comp Name Recursive
  -cpath COMPARTPATH   Filter by Compartment path ,(i.e. -cpath "Adi / Sub"
  -tenantid TENANTID   Override confile file tenancy_id
  -cf CONFIG           Config File (~/.oci/config)
  -csv CSV             Output to CSV files, Input as file header
  -csv_nodate          Do not add date field to the csv
  -jf JOUTFILE         Output to file (JSON format)
  -js                  Output to screen (JSON format)
  -sjf SJOUTFILE       Output to screen (nice format) and JSON File
  -cachef SERVICEFILE  Output Cache to file (JSON format)
  -caches              Output Cache to screen (JSON format)
  --version            show program's version number and exit
******************************************************
***    You must choose at least one parameter!!    ***
******************************************************
`

Regards, Martin

**Comment by adizohar** [comment]
Hi Martin
Filter is working, you didn’t choose any services to report please add -ani or -a

**Comment by jodoglevy** [comment]
@martinberger-ch are you still having issues here, or did @adizohar 's comment help?

**Comment by jodoglevy** [comment]
@martinberger-ch since we haven't heard back from you on this, I'm going to close this issue. Please feel free to reopen if you are still hitting this problem
