### ISSUE TITLE
Invalid ratio of memory in GB to OCPUs

### ISSUE THREAD

**Issue by nbari** [oracle/oci-python-sdk#358]
I am trying to launch an instance using `InstanceShapeConfig` with something like:

    SHAPE = "VM.Standard.E3.Flex"
    DISPLAY_NAME = "Canonical-Ubuntu-20.04-2021.05.13-0"

    create_instance_details.shape_config = oci.core.models.LaunchInstanceShapeConfigDetails(
             memory_in_gbs=4,
             ocpus=2,
      )

But I am getting this error:

     'code': 'InvalidParameter',
     'message': 'Invalid ratio of memory in GB to OCPUs. Current ratio: 0.5. Valid ratio range: 1 - 64', 'status': 400`

The same image works via the web portal, any idea how to define the limits so that I could create images with custom mermoy/ocpus?

**Comment by adizohar** [comment]
Hi nbari, did you try to upgrade the SDK to latest version using pip3 install --upgrade oci ? 

Can you please check with 4.0 and 2.0 ?

**Comment by nbari** [comment]
Hi @adizohar, I am using the current latest `oci==2.39.1` (https://pypi.org/project/oci/)

**Comment by adizohar** [comment]
It works well for me:

```
##########################################################################
# instance.py
##########################################################################
import oci

config_file="~/.oci/config"
config = oci.config.from_file(config_file,"DEFAULT")

compartment_id="ocid1.xxxx"
availability_domain="DbTR:US-ASHBURN-AD-1"
image_id="ocid1.image.oc1.iad.aaaaaaaahz2dqo6g5piofgr7mvfyguqh4lhlhnza3aqoj3xrkn6csju7t2oa"
shape="VM.Standard.E3.Flex"
subnet_id="ocid1.subnet.xxx"

compute_client = oci.core.ComputeClient(config)
launch_instance_details=oci.core.models.LaunchInstanceDetails(
        availability_domain=availability_domain,
        compartment_id=compartment_id,
        shape=shape,
        create_vnic_details=oci.core.models.CreateVnicDetails(
            assign_public_ip=False,
            assign_private_dns_record=False,
            skip_source_dest_check=False,
            subnet_id=subnet_id),
        image_id=image_id,
        shape_config=oci.core.models.LaunchInstanceShapeConfigDetails(
            ocpus=2.0,
            memory_in_gbs=4.0,
            baseline_ocpu_utilization="BASELINE_1_2"),
        subnet_id=subnet_id)
compute_client.launch_instance(launch_instance_details)
```

**Comment by nbari** [comment]
Thanks, I used ` baseline_ocpu_utilization="BASELINE_1_8"` and did the trick, allowing me to create both:

    ocpus:2.0, memory_in_gbs=4.0

and 

    ocpus:2.0, memory_in_gbs=8.0

is ok to keep a wide baseline `BASELINE_1_8`, to manage more cases?

**Comment by adizohar** [comment]
This parameter is mainly for burstable VMs
Please see below from the doc:

baseline_ocpu_utilization - (Optional) (Updatable) The baseline OCPU utilization for a subcore burstable VM instance. Leave this attribute blank for a non-burstable instance, or explicitly specify non-burstable with BASELINE_1_1.

The following values are supported:

BASELINE_1_8 - baseline usage is 1/8 of an OCPU.
BASELINE_1_2 - baseline usage is 1/2 of an OCPU.
BASELINE_1_1 - baseline usage is an entire OCPU. This represents a non-burstable instance.
