### ISSUE TITLE
oci.streaming.models.CreateCursorDetails requires string not datetime for "time" parameter (as module docs say)

### ISSUE THREAD

**Issue by jeliker** [oracle/oci-python-sdk#362]
## Summary
Following returns error

```
d = datetime.datetime.utcnow() - datetime.timedelta(hours=0, minutes=2)
cursor_details = oci.streaming.models.CreateCursorDetails(
  partition=partition,
  time=d,
  type=oci.streaming.models.CreateCursorDetails.TYPE_AT_TIME)

  response = client.create_cursor(stream_id, cursor_details)
```

Help for `oci.streaming.models.CreateCursorDetails` says `time` requires `datetime` type.  If instead of above I use this it works:

```
d = datetime.datetime.utcnow() - datetime.timedelta(hours=0, minutes=2)
cursor_details = oci.streaming.models.CreateCursorDetails(
  partition=partition,
  time=d.isoformat(sep='T', timespec='milliseconds')+'Z',
  type=oci.streaming.models.CreateCursorDetails.TYPE_AT_TIME)

  response = client.create_cursor(stream_id, cursor_details)
```

Note constraint to `milliseconds` as only three fractional second digits are accepted (not more).

## Expected Behavior
* For oci.streaming.models.CreateCursorDetails I expect `time` parameter should accept `datetime` type then converted to suitable string for backend API method

## Actual Behavior
* For oci.streaming.models.CreateCursorDetails the `time` parameter does not accept Python `date time` type but rather requires string in RFC-3339 format _and_ with only three fractional second precision.
  * For example, this string is valid `2021-06-23T17:46:54.414Z` but this string is not `2021-06-23T17:46:54.41444Z`

**Comment by KartikShrikantHegde** [comment]
Hi @jeliker ,

Streaming had applied a fix for this issue. Could you please check on your end if it works as expected? If so can you please close the ticket?

Thanks.

**Comment by KartikShrikantHegde** [comment]
Hi @jeliker , I am closing this issue since we haven't heard from you in a while. Please feel free to re-open if you still have issues.

Thanks.
