### ISSUE TITLE
document location of openapi yaml specs

### ISSUE THREAD

**Issue by kapilt** [oracle/oci-python-sdk#364]
it would be helpful to understand the upstream model source of the sdks, rather than just consuming mostly generated outputs.

**Comment by jodoglevy** [comment]
@kapilt thanks for filing this request - I am not sure OCI publishes publicly the OpenAPI specs for its services, but will look into it

**Comment by ajkaanbal** [comment]
Hi @jodoglevy, I'm also curious if it's possible to check the OpenAPI YAML specs

**Comment by kapilt** [comment]
they are published/public just not documented, I think this should go into the readme, https://docs.oracle.com/en-us/iaas/api/specs/index.json
