### ISSUE TITLE
Support for bulk delete Object storage objects in python sdk

### ISSUE THREAD

**Issue by rohitagl91** [oracle/oci-python-sdk#373]
Currently, there is no way we can delete a bucket or delete all objects in the bucket with a single function call. This means when we want to delete a bucket using SDK we need to list objects and delete all objects 1 by 1 and then delete the bucket. if there are millions of objects in a bucket it takes hours to days to do so. on the other hand, oci-cli has the capability to bulk delete all objects, and also recently they have released --empty flag when deleting bucket which will automatically take care of deleting all objects and bucket and this is done within a minute. can we have the same support in python sdk? thanks!

**Comment by jodoglevy** [comment]
Thanks for the feedback. We'll route this request to the Object Storage team

**Comment by adizohar** [comment]
Rohit, 
I write script to help with bulk delete, it support millions of files
https://github.com/oracle/oci-python-sdk/blob/master/examples/object_storage/object_storage_bulk_delete.py
Please let me know if this help
Thank you

**Comment by adizohar** [comment]
Hi Oby1, I would open new issue, for the delete part, I provided you example
For upload, you can use object_storage.UploadManager module

**Comment by jodoglevy** [comment]
Since the original issue is resolved, I'm closing this - please feel free to open a new github issue for the second issue mentioned
