### ISSUE TITLE
Custom root disk size

### ISSUE THREAD

**Issue by smarlowucf** [oracle/oci-python-sdk#376]
Is it possible to set a non-default root disk size for an instance when launching? I don't see any reference to the disks as part of the launch instance configs in docs https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.LaunchInstanceDetails.html.

**Comment by jodoglevy** [comment]
@smarlowucf we'll route this question to the OCI Compute service folks to take a look at

**Comment by smarlowucf** [comment]
Thanks @jodoglevy

**Comment by jodoglevy** [comment]
@smarlowucf to do what you are asking, you'd want to use the LaunchInstanceDetails' [source_details](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.LaunchInstanceDetails.html#oci.core.models.LaunchInstanceDetails.source_details) param, pick the source_type to be [InstanceSourceViaImageDetails](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.InstanceSourceViaImageDetails.html#oci.core.models.InstanceSourceViaImageDetails), and on that model you can set the [boot_volume_size_in_gbs](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/models/oci.core.models.InstanceSourceViaImageDetails.html#oci.core.models.InstanceSourceViaImageDetails.boot_volume_size_in_gbs).
