### ISSUE TITLE
Listing all subnets in compartment

### ISSUE THREAD

**Issue by kk-hiraskar** [oracle/oci-python-sdk#382]
[`vnCl.list_subnets`](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/core/client/oci.core.VirtualNetworkClient.html#oci.core.VirtualNetworkClient.list_subnets) lists subnets for all VCN's in that compartment.

I have situation, where VCN is moved to different compartment, and subnets created their also.
So the situation is for same VCN now subnets are existing in 2 different compartments, and with instances are attached.

_is their any way to list all subnets of VCN, irrespective of in which compartment, subnets present ?_
OR
_if possible to list all subnets of compartments, irrespective VCN belongs to same compartment or not ?_

**Comment by adizohar** [comment]
Hi KK-HIRASKAR

You have 2 options
1. Use the Search API and use one query:
query subnet resources where vcnid="ocid1.vcn.oc1.iad.xxx"
2. Loop on all the compartments and use the list_subnets api

For your info

**Comment by kk-hiraskar** [comment]
2nd option I am currently using, however it is only listing subnets if VCN also belongs to same compartment.  
As document also says "list includes the subnets from all VCNs in the specified compartment" 

However let me try the 1st suggestion of Search API, if it can list multiple subnets spread across different Compartments for an VCN, as explained in question.

Thanks @adizohar I will try and update here.

**Comment by adizohar** [comment]
I am using the below which works well

```
result = []
for compartment in compartments:
    subnets = []
    try:
        subnets = oci.pagination.list_call_get_all_results(
            virtual_network.list_subnets,
            compartment['id'],
            vcn_id="ocid...",
            lifecycle_state=oci.core.models.Subnet.LIFECYCLE_STATE_AVAILABLE,
            sort_by="DISPLAYNAME",
            retry_strategy=oci.retry.DEFAULT_RETRY_STRATEGY
        ).data

    except oci.exceptions.ServiceError as e:
        ...

    for subnet in subnets:
        result.append(subnet)
```
