### ISSUE TITLE
importing oci is very slow

### ISSUE THREAD

**Issue by yoav-orca** [oracle/oci-python-sdk#386]
Loading the oci SDK is very slow, on my linux machine it's about 1.8 seconds just to import the module.

Version: OCI 2.44.1
OS: Linux Ubuntu 20.04
Python: python3.9 amd64

```
$ hyperfine 'python -c "import oci"'
Benchmark #1: python -c "import oci"
  Time (mean ± σ):      1.793 s ±  0.082 s    [User: 1.571 s, System: 0.207 s]
  Range (min … max):    1.722 s …  1.955 s    10 runs
```

This is a by the worst performance from all cloud sdks (boto3, azure SDK, google-cloud-*).
I suggest adding the ability to lazy loads parts of the sdk

**Comment by adizohar** [comment]
Oracle linux 8 with Python 3.9 Intel and OCI 2.44.1: 0.9 second
```
> time python3.9 -c "import oci"

real	0m0.906s
user	0m0.778s
sys	0m0.117s
```

**Comment by dhoogfr** [comment]
Seems to be very different between Python version


```
:~$ python --version
Python 2.7.18

:~$ time python -c "import oci"

real	0m0,562s
user	0m0,445s
sys	0m0,114s

:~$ python3 --version
Python 3.8.10

:~$ time python3 -c "import oci"

real	0m1,291s
user	0m1,171s
sys	0m0,120s

```

I don't have 3.9 to test with

**Comment by yoav-orca** [comment]
@adizohar I'm seeing very different results, as much as x2 as you are seeing.
But ~900ms is a very big hit for a python module without the ability to choose which parts of the SDK I want.

Just to verify this, I ran the following command
```PYTHONPROFILEIMPORTTIME=1 python -c 'import oci' 2>imports.txt``` 
and opened using [tuna](https://pypi.org/project/tuna/), there's no specific one module that is bad, it's just death by a thousand cuts.

![image](https://user-images.githubusercontent.com/65133955/134817446-548d41a4-2e31-4faa-b21d-f34dcbabca8d.png)

And I also tested on Oracle Linux and found it's actually a bit worse:
```
[root@9fd75743d86b /]# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.4"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:4:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.4
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.4
[root@9fd75743d86b /]# time python3 -c 'import oci'

real	0m2.206s
user	0m1.919s
sys	0m0.287s
```

**Comment by adizohar** [comment]
Hi Yoav

I tried on oracle cloud, it runs for 1 second, but I agree, there are 5300 objects under the OCI tree that imported
specifying single module imports the lot i.e. import oci.core.compute_client

I will consult with the SDK team and advise

Thank you for the feedback, appreciate it.

**Comment by jodoglevy** [comment]
@dhoogfr as mentioned [here](https://docs.oracle.com/en-us/iaas/tools/python/2.45.1/index.html#oracle-cloud-infrastructure-python-sdk-ocisdkversion), Python 2 is not supported for the OCI Python SDK anymore, please use Python 3

**Comment by yoav-orca** [comment]
I would appreciate a workaround if it's possible, it's a very big hit to our test suite, while we are evaluating oci. It's basically non starter for us

**Comment by bhagwatvyas** [comment]
Hey @yoav-orca you can disable importing all the services by setting the following environment variable:
`export OCI_PYTHON_SDK_NO_SERVICE_IMPORTS=1`

Then you can import individual services and modules that you need in place of the `import oci` line. For example, the script here https://github.com/oracle/oci-python-sdk#about can be modified to:

```
from oci import identity
from oci import config

config = config.from_file()

identity_client = identity.IdentityClient(config)

user = identity_client.get_user(config["user"]).data

print(user)
```

**Comment by adizohar** [comment]
Thank you Vyas, this works well, Yoav please let us know if this works for you

```
adiwrk::/home/opc> export OCI_PYTHON_SDK_NO_SERVICE_IMPORTS=1
adiwrk::/home/opc> time python3.9 -c "from oci.core import ComputeClient; from oci import config"

real	0m0.219s
user	0m0.193s
sys	0m0.024s
```

**Comment by github-anurag** [comment]
@yoav-orca 
The solution provided by @bhagwatvyas resolves the issue, so we will be closing this ticket. Please feel free to re-open the issue if you still face slowdowns.
