### ISSUE TITLE
No support for OAUTH 2.0 in IdentityClient e.g. Application Authorized via Client Credentials?

### ISSUE THREAD

**Issue by SimSama** [oracle/oci-python-sdk#390]
Hi Team,

I authorized an application as Audit Administrator, and obtained credentials (not using signing requests, but client credentials), so I have a client ID and client secret. 

I noticed there is very little documentation on communicating with the APIs this way, and Signing Requests using key,fingerprint, user seems to be the preferred way.

The init section of IdentityClient(config), doesn't seem to support a config option for specifing client id and client secret as opposed to key based. 

I can implement in my own implementation, but my question is, is OAUTH2.0 on the way out for Oracle OCI? 

This is for system-to-system communication, no user involved so Client Credentials auth flow (similar to azure, aws, etc) seemed the way to go. Am I on my own to build my own client, or will this be supported in SDK? 

Thanks,

**Comment by jodoglevy** [comment]
Hi @SimSama  - please see https://github.com/oracle/oci-java-sdk/issues/35

**Comment by adizohar** [comment]
SimSama
You can grant permission to compute to authenticate using instance principle , dynamic groups and policies
Please check this blog - https://blogs.oracle.com/developers/post/accessing-the-oracle-cloud-infrastructure-api-using-instance-principals
There are several examples in the examples section how to authenticate
For your info.

**Comment by SimSama** [comment]
That wont work for us, the service using the API does not reside within OCI, it is a remote daemon for log ingestion via (ideally streams) api. Instance principals only work for systems running on OCI compute yes? 

It looks like IAM users don't require an email, but now I'm researching discussions of (why choose IDCS over IAM). As my last question, any downsides to choosing IAM for API access? AWS uses IAM, Azure app registrations, Google Service accounts. Why is IDCS different? 

Thanks for the info.
