### ISSUE TITLE
It could be bug - OCI SDK with Python Kubernetes library

### ISSUE THREAD

**Issue by RahulMR42** [oracle/oci-python-sdk#399]
Hi ,

While using kubernetes clients for python with oci sdk (python version) ,we could see its failing with below error
```
"- root - ERROR - [Errno 2] No such file or directory: 'oci'"
```

This is happening right after create_kubeconfig method and at the step to load the same to kubernetes python client

Ref # https://github.com/RahulMR42/oci-functions-with-oke/blob/main/oke.py#L36

To give some context to this situation:
If we create a ContainerEngineClient providing a custom config (either from a file or variable), this config is not reused when we create a kubeconfig file.

In kubeconfig file, generated oci command required to get a kubernetes token doesn't have as argument the custom config file provided when we created the client. By default, oci cli is looking for it in ~/.oci/config and if none is found, it will go into an endless loop.

This can be reproduced by trying to interact with an OKE cluster from a docker container where oci-cli was installed and was not configured (no config file is present in ~/.oci/) using the approach described in Rahul's link.

Original issue raised # https://github.com/oracle/oci-cli/issues/481

**Comment by bhagwatvyas** [comment]
Hi @RahulMR42, thanks for creating this issue. I have a few questions.

> generated oci command required to get a kubernetes token
what is this command? Is it an OCI CLI command? If it is CLI, can you try using one of the ways mentioned here to point to the custom config file? https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliconfigure.htm#CLIconfigfile

**Comment by RahulMR42** [comment]
Hi @bhagwatvyas 
the full context is we are trying to apply something on OKE Kube cluster.To do so ,we build a python environment with OCI SDK - python and using sdk commands got the kubeconfig file ,while loading the same to python module (https://github.com/kubernetes-client/python) its fails with the mentioned error.We can reproduce it easily as mentioned earlier

**Comment by RahulMR42** [comment]
Specific to your question @bhagwatvyas 
these are the execution behind SDK ,not sure about the actual OCI CLI command.

**Comment by RahulMR42** [comment]
https://github.com/RahulMR42/oci-functions-oke/blob/main/func.py#L35 - We got a way forward ! I think we can close
