### ISSUE TITLE
allow for a generic method to call an enpoint

### ISSUE THREAD

**Issue by drewncrew** [oracle/oci-python-sdk#40]
Would like to have the ability to directly call rest methods. 

client.call( 'rest method', 'service', 'uri', json, **args )
    json is optional, used for put operations

client.call( 'GET', 'compute', '/instances/', retrieve_all=true )
   *allow option to retrieve paged data  

This  allows developers  to use methods that have not been added to the sdk

**Comment by jodoglevy** [comment]
Hi @drewncrew -- I think we support what you're looking for already. Take a look [here](http://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/raw-requests.html). Does that solve your need?

**Comment by drewncrew** [comment]
Just what I was looking for. I did not realize that was available. 

Thank you very much.

**Comment by jodoglevy** [comment]
Awesome. Closing this one.
