### ISSUE TITLE
OCI Streaming - get_messages from StreamClient incredibly slow

### ISSUE THREAD

**Issue by SimSama** [oracle/oci-python-sdk#401]
I had timed the request below to an Oracle stream, and in many cases, it takes 5-10 seconds for some message pulls
get_response = client.get_messages(streamId, cursor, limit=500)

In most cases it never fills the queue, so if the limit is 500, it may only process 30 messages, 60, 200, but never the max.
I've tinkered with various limits 20,50,100,500,1000 . Doesn't seem to change.

If it matters, I was using the stream_example.py, using consumer groups as my base code, with TRIM_HORIZON as the type. I noticed the slowness issue, because my stream was populating a relatively trivial number of messages, and my consumer script simply could not keep up. No network or compute issues, just the api response times are periodically slow.

I'm not sure if this is a bug in the SDK, or the actual response from the API endpoint is slow. I multi-threaded, to where I spawn one consumer thread for every partition on the stream. Each thread shares the same consumer group as it should, and each thread uses a unique instance name. That certainly helps, but it doesn't remove the core issue, per consumer processing is just plain slow. 

For the record I'm not getting any throttles, or failures on consume or put, by observing Oracle Stream metrics. 

Has anyone seen this? How do customers ingest larger volumes of data via a stream? Right now I'm forwarding _Audit events and have a Rule forwarding all Events from all compartments to the stream. Event rate is really low, PUT events delivered is 1700 events per minute, which is very little. A single consumer / single partition should have no problem grabbing this volume.

**Comment by SimSama** [comment]
As some added detail. I'm only consuming. Oracle systems (Events rule forward to stream and _Audit log forwarding to stream using a service connector) are the only ones publishing data in the stream.

**Comment by jodoglevy** [comment]
Hi @SimSama thanks for reporting this - given the service is returning a lot less than what your specify in the limit parameter, I tend to think this is a service bug rather than an SDK bug -- let me ask the Streaming team to take a look at this.

**Comment by SimSama** [comment]
Thanks I appreciate. I was planning to test with raw signing but haven't got around to it yet. Hoping they can identify the issue.

**Comment by ness2u** [comment]
Hi @SimSama,
I'd love to get more specific details about how you're using the sdk. Is it possible to include your code as a repro? and if you can provide the stream ocid, we can take a more detailed look.

Regarding the limit, while consuming messages... the limit is the maximum number of messages you can receive, not a guaranteed number. In general, the service operates on buffers sized in bytes, while limits are requested in terms of messages. We do our best to estimate average message sizes, but with low-traffic streams its hard to keep up to date. Additionally, several operations regarding group operations, like rebalancing, are iterative and require a few get-requests to complete... some of those iterative requests may not return messages even though they are on the stream. Continuously polling messages is the suggested way to go here.

Regarding throughput, 5-10 seconds is definitely not expected; our P99 consume-latency is double-digit milliseconds across all regions, so there must be something interesting going on.

Thanks,
Jon

**Comment by SimSama** [comment]
Can you provide me your email? I didn't want to post stream details here. If you are formally with Oracle support I'll even provide you a set of api keys and a stripped down version of the script I use. 

I basically call this function every minute, and it runs until no more messages available. I've timed with timestamp just before and after  calling client.get_messages from the StreamClient. When pulling data from a partition, it can be extremely slow. Sometimes 1 second (only a few messages processed), sometimes 5 seconds, sometimes 10+ seconds. 

```
    def getMessages(self,client, streamId, initialCursor):
        #print("Getting messages")
        cursor = initialCursor


        startTime = datetime.now()
        numTries = 1
        max_messages = 500
        while True:
            events = []
            get_response = None
            if numTries > 3:
                print("System tried unsuccessfully 3 times to recover from Oracle OCI polling error")
                exit(1)
            try:
                get_response = client.get_messages(streamId, cursor, limit=max_messages)
                if get_response is None:
                    break
                elif not get_response.data:
                    break
            except oci_exceptions.ServiceError as e:
                print("Oracle OCI Get Message Error for stream:",e)
                if e.status == 400:
                    if e.message == 'The cursor is outside the retention period and is now invalid.':
```
I'm only consuming data, the only data being published to the queue is _Audit events from logging service connector. The event size varies, but is on the larger side for many events (7K-8K) bytes each.

I eventually expanded the script to multi-thread, this function run in a thread per partition count. Each use a cursor that correctly uses a unique instance name. That helps with throughput, but per consumer throughput is slow.

**Comment by ness2u** [comment]
> Can you provide me your email? 

You can reach out to jon.harkness@oracle.com for a more formal introduction.

> If you are formally with Oracle support 

I'm an engineer on the Streaming team.

> I'll even provide you a set of api keys and a stripped down version of the script I use.

I would love to see your script, however, please do not share api keys.

**Comment by ness2u** [comment]
@SimSama A gentle reminder to drop me an email when you get a chance.
Thanks.

**Comment by SimSama** [comment]
Just sent to you, thanks for the reminder, I've been swamped.

**Comment by SimSama** [comment]
I sent you an email, did you receive it? I put the issue # 401 in the subject line.

Thanks,

**Comment by SimSama** [comment]
I haven’t had time to reproduce this, our workaround of using multiple threads / calls seems to be working okay for now. I haven’t had time to recreate and do some performance profiling of running a single call in a loop.
 
We can close this for now.
