### ISSUE TITLE
Help in getting maximum security zone data

### ISSUE THREAD

**Issue by dralquinta** [oracle/oci-python-sdk#406]
I'm trying to use the SDK to get the Maximum Security Zone data, however I can't find any suitable client to get the job done. 

Can anyone give some guidance in how to achieve this? (If supported?)

Thanks, 

Denny.

**Comment by dralquinta** [comment]
Could anyone kindly give me some hints or feedback on this one?

**Comment by jodoglevy** [comment]
Hi @dralquinta  - what OCI service is that functionality a part of? That will help me better direct you

**Comment by dralquinta** [comment]
Thank you @jodoglevy for your follow up. Well, indeed that's my question. I can not find any suitable client that offers the chance to get the data related to Maximum Security Zones. Technically speaking I should have some API exposing the contents of the following screenshot: 

![image](https://user-images.githubusercontent.com/51421891/145881330-ca8d3777-f7d2-450d-ae2d-0dd20bca0081.png)

However unfortunately I can't really find anything that resembles this on the API. Any pointers are appreciated.

**Comment by adizohar** [comment]
Hi Denny,
We are working with the service team to find the API that expose the recipes
We will update you once we have more info.
For your info

**Comment by dralquinta** [comment]
Oh, that's great @adizohar I thought I was just not finding it 👍 

I'll put my work on hold then until this one is resolved. Do you happen to have any kind of ETA (a rough estimate I can work with?)

**Comment by adizohar** [comment]
Hi Denny

The list of policies is constant and immutable. If the compartment has the security zone flag it will have the full list of policies listed here:
[List of the policies: https://docs.oracle.com/en-us/iaas/security-zone/using/security-zone-policies.htm]
There is no API for this, as the result going to be the same for everyone
Regards compartment with enabled security zone, I am working with the team to provide the API

**Comment by dralquinta** [comment]
Hi Adi, 

I see. However the data coming from the IdentityClient won't return the policies related to the security zones associated, so I'm unable to get that data. I'll wait for further updates. 

Thanks!

Denny.

**Comment by adizohar** [comment]
HI Denny,
Our service team is working to add the isMaximumSecurityZone flag into the compartment
This can take some time due to the holiday period
Below workaround how to query compartment with the flag
``
import oci

#################################################
# get_msz_compartment
#################################################
def get_msz_compartment(identity_client, compartment_id):

    path_params = {
        "compartmentId": compartment_id
    }
    header_params = {
        "accept": "application/json",
        "content-type": "application/json"
    }
    return identity_client.base_client.call_api(
        resource_path="/compartments/{compartmentId}?verboseLevel=securityZone",
        method="GET",
        path_params=path_params,
        header_params=header_params,
        response_type="json")

#################################################
# main
#################################################
config = oci.config.from_file("~/.oci/config", "DEFAULT")

compartment_id="ocid1.compartment.oc1..xxxxxx"
identity_client = oci.identity.IdentityClient(config)
compartment = get_msz_compartment(identity_client,compartment_id)
print(compartment.data)

# output:
{
   "compartmentId":"ocid1.compartment.oc1..xxx",
   "id":"ocid1.compartment.oc1..xxx",
   "name":"DemoMSZ",
   "description":"DemoMSZ",
   "timeCreated":"2021-12-16T16:33:07.862Z",
   "freeformTags":{},
   "definedTags":{},
   "isAccessible":true,
   "isMaximumSecurityZone":true,
   "lifecycleState":"ACTIVE"
}
``

Regards the policies, it is static policy and no API, when the option become updatable API will be available
Hope this help

**Comment by dralquinta** [comment]
Hi Adi, 

Nice catch there. It almost looks like what the API update will do to get it done 😀 

One follow up question. The output just shows the zone it self and if the compartment contains the parameter `isMaximumSecurityZone` in true or false. In the code I'm working on, I actually need to check the content of the policy and apply some criterias. Would that mean that whenever this gets implemented I'll be able to get those? 

There is no rush, as holidays are also impacting our side so we have plenty breathing room still

**Comment by dralquinta** [comment]
FWIW, I think I can take the workaround just to check if the compartment has or not the `isMaximumSecurityZone`and mark it as successful anyways because if enabled, then a policy needs to be present and for practical purposes that's what I need to check.

**Comment by adizohar** [comment]
Hi Denny

The policy is static (only one policy exist) if the MST=True the compartment will be assigned to the compartment.

For your info and hope it helped

**Comment by dralquinta** [comment]
Gotcha. This helps!

**Comment by dralquinta** [comment]
Workaround works great. I'm closing this one. 

This is what I did to make it work on my end: 

```python
def get_max_security_zone_data(identity_client, compartment_id):
    path_params = {
        "compartmentId": compartment_id
    }
    header_params = {
        "accept": "application/json",
        "content-type": "application/json"
    }
    return identity_client.base_client.call_api(
        resource_path="/compartments/{compartmentId}?verboseLevel=securityZone",
        method="GET",
        path_params=path_params,
        header_params=header_params,
        response_type="json").data
```


Then on the callout: 

```python
        for comp in compartments:
            comp_max_sec_zone = get_max_security_zone_data(self.__identity, comp.id)            
            if "isMaximumSecurityZone" not in comp_max_sec_zone:                
                self.__max_sec_zone.append(comp_max_sec_zone)
```

In here I had to add a clause to check if the keyword `isMaximumSecurityZone` was present or not on the payload, as a compartment that does not contain any definition simply returns this as null.
