### ISSUE TITLE
CONTRIBUTING.rst: broken URL (404), should be https://oca.opensource.oracle.com/

### ISSUE THREAD

**Issue by pabs3** [oracle/oci-python-sdk#409]
The link "The Oracle Contributor Agreement" to https://www.oracle.com/technetwork/community/oca-486395.html in CONTRIBUTING.rst is broken (404), please update it to the new URL https://oca.opensource.oracle.com/ instead.

**Comment by jodoglevy** [comment]
Thanks for reporting, we'll get this fixed

**Comment by waruwaruwaru** [comment]
@pabs3 thank you for bringing this up. The link is now fixed to using https://oca.opensource.oracle.com. Please feel free to reopen this issue if there are any other problems or concern.

**Comment by pabs3** [comment]
@jodoglevy @waruwaruwaru thanks for fixing this. My employer has tasked me with packaging oci-python-sdk for Debian. I would appreciate it if you could prioritise fixing these other issues that will affect the package.

Firstly there is a mail I sent about oci-python-sdk to the Oracle security team. It received tracking number S1583762.

Secondly the development practices for this project around git commits and releases seem to be suboptimal:

https://github.com/oracle/oci-python-sdk/issues/415

Thirdly the cryptography dependency needs updating:

https://github.com/oracle/oci-python-sdk/issues/419

oci-python-sdk triggers some deprecation warnings:

https://github.com/oracle/oci-python-sdk/issues/416
https://github.com/oracle/oci-python-sdk/issues/417

The test suite fails when run outside of virtualenv:

https://github.com/oracle/oci-python-sdk/pull/253
https://github.com/oracle/oci-python-sdk/issues/164

There is a minor issue with incorrect executable permissions:

https://github.com/oracle/oci-python-sdk/issues/418

**Comment by jodoglevy** [comment]
@pabs3 thanks we will review the mail you sent / github issues you filed
