### ISSUE TITLE
Help wanted with retrieving default compute limits in tenancy

### ISSUE THREAD

**Issue by Matt-Mcl** [oracle/oci-python-sdk#413]
Hello,

I've been working on an implementation for retrieving all the limits for computes within a tenancy. I want to be able to check if these limits have been changed from their default values from when the tenancy was created. 

The issue is, only the current values appear to be retrievable.

I'm working with the [Limits Client](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/limits/client/oci.limits.LimitsClient.html#oci.limits.LimitsClient) and have tried all the methods there to get what I'm looking for.

[list_limit_values](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/limits/client/oci.limits.LimitsClient.html#oci.limits.LimitsClient.list_limit_values) Only gives the following data (1 value example): 
```shell
{
  "availability_domain": "oDQF:US-ASHBURN-AD-1",
  "name": "gpu3-core-count-reservable",
  "scope_type": "AD",
  "value": 100
}
```

[get_resource_availability](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/limits/client/oci.limits.LimitsClient.html#oci.limits.LimitsClient.get_resource_availability) Only gives the following data (1 value example):
```shell
{
  "available": 14983,
  "effective_quota_value": null,
  "fractional_availability": 14983.0,
  "fractional_usage": 17.0,
  "used": 17
}
```
Both only return the current values/availability of remaining resources.

[list_limit_definitions](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/limits/client/oci.limits.LimitsClient.html#oci.limits.LimitsClient.list_limit_definitions) Only gives the following data (1 value example):
```shell
{
  "are_quotas_supported": true,
  "description": "Cores for DVH.Standard.E2.64 Instances",
  "is_deprecated": false,
  "is_dynamic": false,
  "is_eligible_for_limit_increase": true,
  "is_resource_availability_supported": true,
  "name": "dvh-standard-e2-core-count",
  "scope_type": "AD",
  "service_name": "compute"
}
```

Is there any way to retrieve the default compute limits for a tenancy? Am I missing anything in these returned data?

Thanks in advance!

Matt

**Comment by adizohar** [comment]
Hi Matt, limits returns only the current limit and usage, there is no "default" , some customers provisioned with higher limits than other, depends on the contract
You can check the tenant limit by checking the root compartments or per specific compartment
I wrote script to help doing it at https://github.com/oracle/oci-python-sdk/tree/master/examples/list_resources_in_tenancy
For your info

**Comment by Matt-Mcl** [comment]
Ah okay. I was afraid this was the case. Thanks for the quick reply.
