### ISSUE TITLE
Pagination does not support "Wrapped List" style of return for new API calls

### ISSUE THREAD

**Issue by jearls** [oracle/oci-python-sdk#414]
New API calls are using a "Wrapped List" style of return for pagination purposes.  See for example, the `list_` return types for the artifacts client and the network load balancer client.

The `pagination` utility functions do not support this style except for a few special cases.

Please update the `pagination` utility functions to work with the "Wrapped List" style of list API call return values.

**Comment by jodoglevy** [comment]
Thanks @jearls for reporting, we'll take a look

**Comment by jearls** [comment]
More specifically, it appears that the `oci.pagination.list_call_get_all_results_generator` function is the only one that does _not_ support the `.items` style of wrapped list result; the other functions do have support for this.

**Comment by bhagwatvyas** [comment]
This has been fixed in the latest OCI Python SDK (v2.55.1).
