### ISSUE TITLE
replace `license-files` with `license_files` in setup.cfg (dash-separated version is deprecated)

### ISSUE THREAD

**Issue by pabs3** [oracle/oci-python-sdk#416]
When I try to build oci-python-sdk from source I get a warning because of a deprecated field in setup.cfg:

```
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'license-files' will not be supported in future versions. Please use the underscore name 'license_files' instead
```

**Comment by waruwaruwaru** [comment]
Hi @pabs3, I will be looking into this issue, what python version and what command did you run to build the oci-python-sdk? I tried to reproduce it on my end but I was not able to see the warning.

**Comment by pabs3** [comment]
It happens with both Python 3.9 and 3.10, but the message comes from
setuptools rather than Python itself. It happens with setuptools
versions 58.2.0-1 and 59.6.0-1.1 from Debian bookworm and sid.
Any use of the setup.py script causes the warning, for example:

python3 setup.py --help

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by waruwaruwaru** [comment]
@pabs3, the latest SDK should now have this issue fixed. Please feel free to re-open the issue if another problem comes up. Thank you for contributing to OCI Python SDK.
