### ISSUE TITLE
update cryptography to allow either 3.4.8 or 36.0.1 and earlier

### ISSUE THREAD

**Issue by pabs3** [oracle/oci-python-sdk#419]
There is a cryptography 3.4.8 that updates the OpenSSL version used, please update the dependencies to allow it.

Also, 36.0.1 is out that rewrites parts of the codebase in Rust, so it should be much safer, please look at allowing that version:

https://cryptography.io/en/latest/changelog/

**Comment by pabs3** [comment]
This is especially important since `cryptography` 35.0.0 added support for OpenSSL 3:

https://cryptography.io/en/latest/changelog/#v35-0-0

**Comment by github-anurag** [comment]
@pabs3 we increased the upper bound for cryptography. Will evaluate a bit more on removing in future release
