### ISSUE TITLE
Pulling all limit definitions, doesn't return all data

### ISSUE THREAD

**Issue by Matt-Mcl** [oracle/oci-python-sdk#422]
Hi,

I've been using this method: [list_limit_definitions](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/limits/client/oci.limits.LimitsClient.html#oci.limits.LimitsClient.list_limit_definitions) to retrieve all of the limits in the root compartment, by providing the tenancy id as `compartment_id` and no service name.

The issue is, it doesn't appear to return all of the limits when doing so.

I'll be looking specifically at compute in this example.

This:
```python
limit_definitions = limits_client.list_limit_definitions(compartment_id=tenancy.id).data

temparray = []

for limit_definition in limit_definitions:
    if limit_definition.is_deprecated and limit_definition.service_name == "compute":
        testtemp.append(limit_definition)

print(temparray)
```
Returns: https://pastebin.com/A9G1AjEu

Which is not an exhaustive list of all of the compute limits. - Also I'm aware I'm just looking at depreciated limits here. This is intentional as I want `vm-gpu2-1-count` for example, which isn't being returned here.

This: (notice the service_name now being passed in)
```python
limit_definitions = limits_client.list_limit_definitions(compartment_id=tenancy.id, service_name="compute").data

temparray = []

for limit_definition in limit_definitions:
    if limit_definition.is_deprecated and limit_definition.service_name == "compute":
        testtemp.append(limit_definition)

print(temparray)
```

Returns: https://pastebin.com/mzSSJ7ch

Now I understand that I can just use the service name if I want all the compute definitions. However, I want to be able to get ALL of the definitions which I assumed was the point for not specifying a service name, but this clearly isn't the case. 

Can you help me with this?

Thanks,
Matt

**Comment by jodoglevy** [comment]
@Matt-Mcl  thanks for reporting - we'll ask the Limits service team to take a look

**Comment by Matt-Mcl** [comment]
Thanks Joe - keep me updated

**Comment by Matt-Mcl** [comment]
@jodoglevy I honestly thought I had tried that. All calls are paginated in the project for this reason. I didn't put it in this example for simplicity but this was in fact the problem. 

Thanks very much!
