### ISSUE TITLE
Get_Networking_Topology() results in error when running on Cloud Shell.  Reference #425

### ISSUE THREAD

**Issue by GrzegorzWysopal** [oracle/oci-python-sdk#429]
The problem in issue #425 - was solved with the workaround below:
```
network_client = get_virtual_network_client(self.config, self.signer)
network_client.base_client.endpoint = 'https://vnca-api.' + region_name + '.oci.oraclecloud.com'

network_client.get_networking_topology(tenancy.id).data

```
The problem arises when running workaround in the Cloud Shell environment which uses **delegation token** for authentication instead of the predefined config file:

```
oci.exceptions.TransientServiceError: {'opc-request-id': '8F9AE240E6984B86A4DD7E0B69802D90/E0C542FF29C5F37139CC385EF7582944/4E2422DCF6498345A2FE1B906A9236F6', 'code': 404, 'message': '(404, NotAuthorizedOrNotFound, false) Authorization failed or requested resource not found (opc-request-id: E7FA342C2258453F9C2DDBE1BEBBAB52/4CCBF8EA6A8718B198DE9C85E38A8EC3/45AE7B99C6E666055D8EBC98B2D0063E)', 'status': 500}
```

Keep in mind that I have run the same API calls in a Cloud Shell and Linux instance which are working normally, but only for a workaround the program will throw an error.

Please let me know what could possibly cause the problem and what would be the solution?

**Comment by GrzegorzWysopal** [comment]
This requires additional input, it will be reissued again.

**Comment by dralquinta** [comment]
@GrzegorzWysopal can you reopen this one? 

We were able to pin down the issue. It relates to the way the signer is created. When using a delegation token, then the workaroiund given on https://github.com/oracle/oci-python-sdk/issues/425 goes haywire as it finds a mismatch on the region and fails. 

We've prepared a test case, which is available on this repo, which isolates the problem. Ref: https://github.com/dralquinta/bug429

To reproduce: 

- Download the main branch from [here](https://github.com/dralquinta/bug429/archive/refs/heads/main.zip)
- Open a Cloud Shell and copy main.zip into the cloud shell
- Unzip the file main.zip
- Execute ./test.sh -dt
- Error will pop up after a while


We're making intensive use of similar stuff on other parts of our code, however as this is hitting directly the API endpoint, we suspect that fixing what's reported on https://github.com/oracle/oci-python-sdk/issues/425 will subsequently fix this as well.

**Comment by github-anurag** [comment]
@dralquinta @GrzegorzWysopal  
What region are you using in this environment? Also is the cloudshell opened in the region you are trying to connect?

**Comment by KartikShrikantHegde** [comment]
Hi @dralquinta and @GrzegorzWysopal , can you please provide the details @github-anurag asked for, so that one of our engineers can look into the issue? Thanks!

**Comment by KartikShrikantHegde** [comment]
Hi @dralquinta and @GrzegorzWysopal , we will close this ticket since we haven't heard from you in a while. Please let us know if you are still facing the issue. Thanks.
