### ISSUE TITLE
ObjectStorageClient list_work_requests method returns no data

### ISSUE THREAD

**Issue by Matt-Mcl** [oracle/oci-python-sdk#434]
I have tried running this method in multiple compartments each with buckets and completed work requests. All simply returned an empty list.

Does this method work?

Reference: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/object_storage/client/oci.object_storage.ObjectStorageClient.html?highlight=objectstorageclient#oci.object_storage.ObjectStorageClient.list_work_requests

**Comment by jodoglevy** [comment]
@Matt-Mcl thanks for reporting - I'll ping the Obj Storage team to take a look

**Comment by KartikShrikantHegde** [comment]
Hi @Matt-Mcl ,

Are you still facing the issue with this method?

Object Storage team confirmed that this method works fine both in SDK and CLI. Here is an example of how to use list_work_requests API - https://docs.cloud.oracle.com/en-us/iaas/tools/python-sdk-examples/latest/objectstorage/list_work_requests.py.html

Let us know if you are still having trouble.

**Comment by KartikShrikantHegde** [comment]
Hi @Matt-Mcl ,

Since we haven't heard from you, I will be closing this ticket for now. Please feel free to re-open if you run into issues.

Thanks.
