### ISSUE TITLE
Fusion Analytics Warehouse support?

### ISSUE THREAD

**Issue by bambamx** [oracle/oci-python-sdk#436]
Hi,
I was trying to fetch all the FAW's in a tenancy with no luck using the Analytics module, but seems like this is not supported since I don't get an OCID with the prefix 'faw'

```
analytics_client = oci.analytics.AnalyticsClient(config)
list_analytics_instances_response = analytics_client.list_analytics_instances(
    compartment_id="ocid1.compartment.XXX")
```

Thanks

**Comment by jodoglevy** [comment]
@bambamx  thanks for reporting, we'll ask the Analytics team to take a look

**Comment by adizohar** [comment]
In order to list the fusion analytics, you should use the class oci.fusion_apps.FusionApplicationsClient
And command - list_fusion_environments
Please let me know if this help.

**Comment by KartikShrikantHegde** [comment]
Hi @bambamx , did you try the workaround suggested by Adi? Let us know if you are still running into the issue. Thanks!

**Comment by bambamx** [comment]
Sure, I'll give it a try this week! when did this new feature got added? on which version? thanks

**Comment by bambamx** [comment]
its not working to retrieve any FAW's, I can see the FAW in the UI but I'm not getting anything with list_fusion_environments I specified the compartment as well but it seems like this feature is still not available?

**Comment by KartikShrikantHegde** [comment]
Hi @bambamx , Unfortunately, there is no SDK support for FAW(Fusion Analytics Warehouse). We provided a workaround from Adi using the Oracle Fusion apps example. We don't yet have any plans to add SDK support for FAW. Sorry for the inconvenience.

**Comment by KartikShrikantHegde** [comment]
Hi @bambamx , I am closing this ticket for now. I will let you know if the SDK support is added to FAW. Thanks.
