### ISSUE TITLE
Import takes over 1.5 seconds

### ISSUE THREAD

**Issue by brenns10** [oracle/oci-python-sdk#471]
Hello, as I write tooling which uses the SDK, I noticed that loading the SDK is _quite_ slow. From my laptop:

```
In [1]: %time import oci
CPU times: user 1.29 s, sys: 198 ms, total: 1.48 s
Wall time: 1.68 s
```

I think this has to do with the fact that the SDK seems to be composed of 8420 individual Python files (or the same number of .pyc files, which I guess are faster to load).

```
$ find ~/.local/lib/python3.10/site-packages/oci/ -name '*.py' | wc -l
8420
$ find ~/.local/lib/python3.10/site-packages/oci/ -name '*.pyc' | wc -l
8420
```

But the core issue isn't the size of the package; it's that importing the `oci` package imports _every single module within_! That's very unusual, and quite expensive. Most people aren't using every SDK service, but you're requiring them to load the code for them at startup.

My use case is making a quicker, more streamlined CLI for the compute service, and if importing the OCI package alone costs well over a second, I can't give users a snappy experience.

It's strange, because the oci-cli should have the same issues, but as far as I can see, it does not!

```
In [1]: import sys

In [2]: len(sys.modules.keys())
Out[2]: 682

In [3]: %time import boto3  # just for comparison :)
CPU times: user 133 ms, sys: 19.1 ms, total: 152 ms
Wall time: 217 ms

In [4]: len(sys.modules.keys())
Out[4]: 934

In [5]: %time import oci_cli.cli
CPU times: user 132 ms, sys: 37.3 ms, total: 169 ms
Wall time: 270 ms

In [6]: len(sys.modules.keys())
Out[6]: 1556

In [7]: %time import oci_cli.cli_root
CPU times: user 9 µs, sys: 0 ns, total: 9 µs
Wall time: 11.7 µs

In [8]: len(sys.modules.keys())
Out[8]: 1556

COMPARE TO

In [1]: import sys

In [2]: len(sys.modules.keys())
Out[2]: 681

In [3]: %time import oci
CPU times: user 1.45 s, sys: 306 ms, total: 1.76 s
Wall time: 2.84 s

In [4]: len(sys.modules.keys())
Out[4]: 9193
```

There's a whole bunch of imports in the OCI CLI, and I'm going through them now to understand. Maybe when you order the imports in a certain way, the behavior changes?

**Comment by github-anurag** [comment]
@brenns10 
Please see: https://docs.oracle.com/en-us/iaas/tools/python/2.79.0/sdk_behaviors/enable_selective_service_imports.html for enabling selective imports in Python SDK.
We are looking into making this behavior as default without breaking existing customers in the next Major release.

**Comment by brenns10** [comment]
Thanks for the quick response, I guess I forgot to do the Github issue search! Really appreciate the help :)

**Comment by github-anurag** [comment]
@brenns10 
We enabled the lazy imports when using Python 3.7+ in the v2.88.1 released today. We would appreciate it if you can check if improves the startup times for you.
PS: You will need to disable selective imports mentioned earlier to use this feature.

**Comment by bgiaccio** [comment]
Oh that is so much faster I was on 2.87.0 these 5 imports took 80 seconds,  with 2.90.4 it takes 0.8 seconds
```python
from oci.config import validate_config
from oci.exceptions import InvalidPrivateKey, ServiceError
from oci.object_storage import ObjectStorageClient
from oci.object_storage.models import ObjectSummary
from oci.pagination import list_call_get_all_results
```
