### ISSUE TITLE
Boot Volume 

### ISSUE THREAD

**Issue by davidedisa** [oracle/oci-python-sdk#473]
Hi

I am trying to get the boot volume size of my instances, however when I  execute this

list_instances_response = core_client.list_instances(
    compartment_id= compartment_id)
print (list_instances_response.data)

The output is "boot_volume_size_in_gbs": null,

  "source_details": {
    "boot_volume_size_in_gbs": null,
    "image_id": "¡¡",
    "kms_key_id": null,
    "source_type": "image"
  },
  "system_tags": {},
  "time_created": "2022-07-27T13:31:43.626000+00:00",
  "time_maintenance_reboot_due": null

Am i doing somthing wrong?

**Comment by adizohar** [comment]
you will need to use get_boot_volume in order to fetch boot volume size
you can utilize the showoci to extract all volumes into csv = https://github.com/oracle/oci-python-sdk/tree/master/examples/showoci

**Comment by davidedisa** [comment]
Hi

Perfect, i I will check it, thank you very much
