### ISSUE TITLE
Error oci-python-sdk/examples/usage_reports_to_adw/shell_scripts/

### ISSUE THREAD

**Issue by xjuarez** [oracle/oci-python-sdk#477]
When run_single_daily_usage2adw.sh is executed it returns an error
/home/opc/usage_reports_to_adw/shell_scripts/run_single_daily_usage2adw.sh: line 43: unexpected EOF while looking for matching `"'
/home/opc/usage_reports_to_adw/shell_scripts/run_single_daily_usage2adw.sh: line 45: syntax error: unexpected end of file

And to correct it add " on line 42 after TAG1_SPECIAL

**Comment by adizohar** [comment]
Thank you
I have fixed it and pushed it to next version 9/14/2022
Appreciate it
Adi

**Comment by adizohar** [comment]
I also published new version into the oci marketplace, version 22.09.02 will be available tomorrow
