### ISSUE TITLE
Split NotAuthorizedOrNotFound single error into NotAuthorized error and NotFound error

### ISSUE THREAD

**Issue by europ** [oracle/oci-python-sdk#480]
### Type

Feature Request

### Abstract

NotAuthorizedOrNotFound error is missleading, either it is an authorization error or a resource access error.

Different types of errors should not be merged into one. The more specific the error, the easier to investigate/resolve.

### Affected

* CLI for OCI
* Ansible Collection for OCI
* etc.

**Comment by jodoglevy** [comment]
Agreed, this is by design. OCI does not want to expose the existence of customer resources to folks who are not authorized to know if those resources exist or not.
