### ISSUE TITLE
oci.compute_instance_agent.ComputeInstanceAgentClient has mandatory config parameter

### ISSUE THREAD

**Issue by megashrieks** [oracle/oci-python-sdk#481]
when using resource principal or instance principal, we can provide a signer object to the client, in which case the config object should be optional. However the config object is mandatory and is strictly validated even when the signer object is provided

```python3
oci.compute_instance_agent.ComputeInstanceAgentClient(
    config={
        "region": "us-phoenix-1"
    },
    signer=self.signer
)

```

Output:
```
Traceback (most recent call last):
  File "...", line 72, in <module>
    instagentid = v.runcommand()
  File "...", line 20, in runcommand
    compute_client = oci.compute_instance_agent.ComputeInstanceAgentClient(
  File ".../oci_sdk/lib/python3.9/site-packages/oci/compute_instance_agent/compute_instance_agent_client.py", line 73, in __init__
    validate_config(config, signer=kwargs.get('signer'))
  File ".../oci_sdk/lib/python3.9/site-packages/oci/config.py", line 163, in validate_config
    raise InvalidConfig(errors)
oci.exceptions.InvalidConfig: {'tenancy': 'missing', 'key_file': 'missing', 'fingerprint': 'missing', 'user': 'missing'}
```

Please validate if this is the correct behaviour

python version : 3.9.14

**Comment by github-anurag** [comment]
@megashrieks 
Did you create the signer as demonstrated in the examples?

Refer:-
Instance Principals:-
https://github.com/oracle/oci-python-sdk/blob/master/examples/instance_principals_examples.py 

Resource Principals:-
https://github.com/oracle/oci-python-sdk/blob/master/examples/resource_principals_example.py

**Comment by megashrieks** [comment]
@github-anurag yes, I've created signer exactly like that but when the code is not running in a container, I'm creating a signer from the config file, and that is being used in the example above

**Comment by megashrieks** [comment]
the code for creating a signer

```python3
def getauth():
    '''get auth object'''
    if not in_container():
        config = from_file(profile_name='BOAT_OC1')
        return Signer(
            config['tenancy'],
            config['user'],
            config['fingerprint'],
            config['key_file']
        )
    return signers.get_resource_principals_signer()
```

I've tested the oci.compute_instance_agent.ComputeInstanceAgentClient with the signer from oci config file since I'm testing it locally

**Comment by github-anurag** [comment]
@megashrieks 
I am assuming when you say container you mean an OCI Instance. If that is the case, then you can't use either Instance Principals signer or Resource Principals signer. You will need to use Config based signer where you don't need to pass the signer object

Build config from file:-
https://docs.oracle.com/en-us/iaas/tools/python/2.81.0/configuration.html 

Use config based signer:-
https://github.com/oracle/oci-python-sdk/blob/master/examples/object_crud.py#L15-L17

**Comment by megashrieks** [comment]
so if I'm using the resource principal signer is the config optional?

**Comment by megashrieks** [comment]
great! I will test this out

**Comment by github-anurag** [comment]
@megashrieks 
If this issue is resolved can we close this ticket?
