### ISSUE TITLE
Model get_subtype function

### ISSUE THREAD

**Issue by jwrackware** [oracle/oci-python-sdk#482]
I have previously used the `oci.core.models.VolumeGroupSourceDetails` `get_subtype` method like this:

`subtype_name = oci.core.models.VolumeGroupSourceDetails.get_subtype(to_dict(volume_group.source_details))`

`to_dict` comes from `oci.util`. `volume_group` is an existing VolumeGroup object.

That worked well for me when I have a `VolumeGroupSourceDetails` and want to know whether it is a `VolumeGroupSourceFromVolumeGroupDetails` or a `VolumeGroupSourceFromVolumesDetails` or a `VolumeGroupSourceFromVolumeGroupBackupDetails`.

However, I have more recently tried the same thing with `InstanceSourceDetails`. but that fails because `InstanceSourceDetails.get_subtype()` looks for `sourceType` (The API name for the field) while the field in the dictionary returned by `to_dict` is `source_type` (The SDK name for the field).

My question is: Am I misusing `to_dict` or `get_subtype`? Or is `to_dict` populating the wrong keys? Or is `get_subtype` searching for the wrong key?

If my use of `to_dict` and/or `get_subtype` is wrong, perhaps the documentation could be updated with a use case or example to explain how those functions are intended to be used. If either `to_dict` or `get_subtype` is using the wrong key, this issue could be considered a bug report.

OCI SDK version 2.82.0, Python version 3.10

**Comment by KartikShrikantHegde** [comment]
Hi,

Thank you for reporting the issue. We will take a look and get back to you as soon as we can.

Thanks.

**Comment by bhagwatvyas** [comment]
Hi @jwrackware, we use `get_subtype` to deserialize the API response into the model class. `to_dict` is a util function used in our tests. We did not intend for these functions to be used in the way you are using. 

Can you please explain your use case when you're trying to get the subtype? Perhaps we may be able to offer another solution which works for you

**Comment by bhagwatvyas** [comment]
Thank you for your feedback, @jwrackware.
