### ISSUE TITLE
does not exist in the namespace 'bling' or you are not authorized to access it

### ISSUE THREAD

**Issue by dbafurushima** [oracle/oci-python-sdk#484]
hello, I'm having trouble running usage2adwvm

dynamic group is ok
Policy is OK

Apparently I can't get to the "bling" namespace

[opc@usage2adwvm setup]$ ./check_connectivity.py

   Connecting to Identity Service...
   Okay.

   Check Tenancy Details Access...
   Okay.

   Get List of Regions...
   Okay.

   Check running in home region...
   Home    Region = sa-saopaulo-1
   Current Region = sa-saopaulo-1
   Okay.

   Check Compartment List Access...
   Okay...

   Check Access to Cost and Usage Object Storage...
Error oci.exceptions.ServiceError
{'opc-request-id': 'gru-1:Pgbe2VEGndcwPCggBtIYuxiauu74ANvvCsbqJrIbVgB20d3oEkOZm_oeBmJzHH7V', 'code': 'BucketNotFound', 'message': "Either the bucket named 'ocid1.tenancy.oc1..aaaaaaaa5t6qrkbwsdb3lg63fhdhjdsffp2lqbuxx5i66nqtt4onadixezzq' does not exist in the namespace 'bling' or you are not authorized to access it", 'status': 404}

**Comment by dbafurushima** [comment]
[opc@usage2adwvm ~]$ oci os object list --namespace-name bling --auth instance_principal --bucket-name ocid1.tenancy.oc1..aaaaaaaa2m6zkjpv2kzqw7iwr5toerzt2i3v6qfurovnwvmcnpq5lizqsgzq
ServiceError:
{
    "code": "BucketNotFound",
    "message": "Either the bucket named 'ocid1.tenancy.oc1..aaaaaaaa2m6zkjpv2kzqw7iwr5toerzt2i3v6qfurovnwvmcnpq5lizqsgzq' does not exist in the namespace 'bling' or you are not authorized to access it. Please visit https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm to learn more about this error code",
    "opc-request-id": "gru-1:tRgTvTXtxfS9zlq9NlA4OfvbkAp-uIBvRDp-CChON7G8E6_XIaB7v18kASNqcvqk",
    "status": 404
}

**Comment by dbafurushima** [comment]
The tenancy mentioned in the command is not a child, it is a parent.
I believe that if it was a tenancy child, it wouldn't work.

**Comment by github-anurag** [comment]
Hi @dbafurushima 
This error is returned by Object Storage service, we can check with them to see why you get a 404 here. 

Also just to confirm do you have the correct Dynamic Group and policies in place so you may access this bucket via instance principals?

Read more here:
Dynamic Groups: https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/managingdynamicgroups.htm 
Policies: https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/managingpolicies.htm

**Comment by dbafurushima** [comment]
![Screenshot_1_EVIDENCIA](https://user-images.githubusercontent.com/31262671/192372966-19de2c1d-35f0-4e9c-b96d-df6e21dc6059.png)

**Comment by dbafurushima** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/31262671/192373283-cc8e14a5-17cf-4b5a-b308-9edcd0e4aba9.png)

**Comment by github-anurag** [comment]
@dbafurushima 
The error says the `bucket_name` not found.. It looks like you are providing the bucket `OCID` whereas the operation is expecting the `bucket_name`. Can you check if providing the bucket name here resolves the issue for you?

**Comment by dbafurushima** [comment]
[opc@usage2adwvm ~]$ oci os object list --namespace-name bling --auth instance_principal  --bucket-name billing
ServiceError:
{
    "code": "BucketNotFound",
    "message": "Either the bucket named 'billing' does not exist in the namespace 'bling' or you are not authorized to access it. Please visit https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm to learn more about this error code",
    "opc-request-id": "gru-1:Zponuq1biFu_UzXqHvbuFwzfB_fjxXLMSOsxo-S_V911HgaZ5mLk8S0BHMzaHf-E",
    "status": 404
}

**Comment by github-anurag** [comment]
@dbafurushima 
Thanks for checking. I just found out that this issue should be owned by the metering team. I will forward this issue to them internally.

**Comment by adizohar** [comment]
Hi Carlos, can you run this command (oci cli) using cloud shell ? or using user authentication on your compute
I would believe the issue is with dynamic group and access, please advise

**Comment by dbafurushima** [comment]
############ command run in cloud shell

oci_admint@cloudshell:~ (sa-saopaulo-1)$ oci os object list --namespace-name bling --bucket-name ocid1.tenancy.oc1..aaaaaaaa2m6zkjpv2kzqw7iwr5toerzt2i3v6qfurovnwvmcnpq5lizqsgzq
ServiceError:
{
    "client_version": "Oracle-PythonSDK/2.82.0, Oracle-PythonCLI/3.16.1",
    "code": "BucketNotFound",
    "logging_tips": "Please run the OCI CLI command using --debug flag to find more debug information.",
    "message": "Either the bucket named 'ocid1.tenancy.oc1..aaaaaaaa2m6zkjpv2kzqw7iwr5toerzt2i3v6qfurovnwvmcnpq5lizqsgzq' does not exist in the namespace 'bling' or you are not authorized to access it",
    "opc-request-id": "gru-1:qADpcBEb3yNECb742ZVs5XrjR16RGFKHb_G_je06hbkcTp_KF9f1GnEZvX_TW_5W",
    "operation_name": "list_objects",
    "request_endpoint": "GET https://objectstorage.sa-saopaulo-1.oraclecloud.com/n/bling/b/ocid1.tenancy.oc1..aaaaaaaa2m6zkjpv2kzqw7iwr5toerzt2i3v6qfurovnwvmcnpq5lizqsgzq/o",
    "status": 404,
    "target_service": "object_storage",
    "timestamp": "2022-09-26T22:06:03.748359+00:00",
    "troubleshooting_tips": "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_bucketnotfound for more information about resolving this error. If you are unable to resolve this issue, run this CLI command with --debug option and contact Oracle support and provide them the full error message."
}
oci_admint@cloudshell:~ (sa-saopaulo-1)$ 


#######################################################################

############ command run using user authentication

[root@gwfurushima ~]# oci os object list --namespace-name bling --bucket-name ocid1.tenancy.oc1..aaaaaaaa2m6zkjpv2kzqw7iwr5toerzt2i3v6qfurovnwvmcnpq5lizqsgzq
ServiceError:
{
    "client_version": "Oracle-PythonSDK/2.73.0, Oracle-PythonCLI/3.10.5",
    "code": "BucketNotFound",
    "logging_tips": "Please run the OCI CLI command using --debug flag to find more debug information.",
    "message": "Either the bucket named 'ocid1.tenancy.oc1..aaaaaaaa2m6zkjpv2kzqw7iwr5toerzt2i3v6qfurovnwvmcnpq5lizqsgzq' does not exist in the namespace 'bling' or you are not authorized to access it",
    "opc-request-id": "gru-1:PL5SrDBKrZPlrfDZF0q7H_u3tWTKD5jriCo2i1HgvCKEgNSdNeYY5gKWrHyW8WSt",
    "operation_name": "list_objects",
    "request_endpoint": "GET https://objectstorage.sa-saopaulo-1.oraclecloud.com/n/bling/b/ocid1.tenancy.oc1..aaaaaaaa2m6zkjpv2kzqw7iwr5toerzt2i3v6qfurovnwvmcnpq5lizqsgzq/o",
    "status": 404,
    "target_service": "object_storage",
    "timestamp": "2022-09-26T19:07:55.991963",
    "troubleshooting_tips": "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_bucketnotfound for more information about resolving this error. If you are unable to resolve this issue, run this CLI command with --debug option and contact Oracle support and provide them the full error message."
}




-----------------------------------------------------------------------------------------


### dynamic group and access
 #### Policy Detail - Usage2ADW
define tenancy usage-report as ocid1.tenancy.oc1..aaaaaaaaned4fkpkisbwjlr56u7cj63lf3wffbilvqknstgtvzub7vhqkggq	
endorse dynamic-group UsageDownloadGroup to read objects in tenancy usage-report	
Allow dynamic-group UsageDownloadGroup to inspect compartments in tenancy	
Allow dynamic-group UsageDownloadGroup to inspect tenancies in tenancy	


#### Dynamic group details - UsageDownloadGroup
Any {instance.id = 'ocid1.tenancy.oc1..aaaaaaaa5t6qrkbwsdb3lg63fhdhjdsffp2lqbuxx5i66nqtt4onadixezzq',instance.compartment.id = 'ocid1.tenancy.oc1..aaaaaaaa5t6qrkbwsdb3lg63fhdhjdsffp2lqbuxx5i66nqtt4onadixezzq'}

**Comment by adizohar** [comment]
Carlos, is your user federated user or local user on OCI ?

**Comment by dbafurushima** [comment]
Local User OCI

**Comment by adizohar** [comment]
Then we will need to take it with IAM team to check, something is not right with permission
I assume you are in administrators group local user and cloud shell throw same error above

**Comment by adizohar** [comment]
Happy to have zoom call tomorrow with you , send me e-mail and I will organize it - adi.zohar@oracle.com

**Comment by dbafurushima** [comment]
![935682f3-29db-4f05-a338-10d5508e9c3e](https://user-images.githubusercontent.com/31262671/192390879-1f7eb583-cbe3-43a9-991b-062c7a9cda54.jpg)

**Comment by adizohar** [comment]
Carlos, did it load any files ?

**Comment by adizohar** [comment]
Hi Carlos, as discussed, all worked well, can you please confirm it ?

**Comment by dbafurushima** [comment]
Sorry for the delay.

Can create usage2adw, doing the manual load, using usage2adw.py.

Using the check_connectivity.py script didn't work!

However, manually running usage2adw.py, so I understand that the access to the bling bucket is OK and the problem is possibly IAM.

**Comment by dbafurushima** [comment]
Not.
I appreciate your time.
Thank you for your help.
