### ISSUE TITLE
LaunchInstancePlatformConfig missing is_symmetric_multi_threading_enabled option

### ISSUE THREAD

**Issue by manorama-pidapa** [oracle/oci-python-sdk#490]
I am using OCI python SDK version 2.86.0. 

I was trying to launch an instance on a BM shape by disabling IOMMU and SMT. 
There are no is_symmetric_multi_threading_enabled or is_input_output_memory_management_unit_enabled parameters in LaunchInstancePlatformConfig which is part of LaunchInstanceDetails although they are present in InstanceConfigurationLaunchInstancePlatformConfig class. 

The platform_config parameter of LaunchInstanceDetails should be of type InstanceConfigurationLaunchInstancePlatformConfig instead of LaunchInstancePlatformConfig which it currently is to allow users to enable/disable certain bios parameters.

**Comment by KartikShrikantHegde** [comment]
Hi @manorama-pidapa ,

Our team will take a look, thanks for reporting it.

**Comment by KartikShrikantHegde** [comment]
Hi @manorama-pidapa ,

The two objects in question are:

1. https://docs.oracle.com/en-us/iaas/tools/python/2.94.0/api/core/models/oci.core.models.InstanceConfigurationLaunchInstancePlatformConfig.html

2. https://docs.oracle.com/en-us/iaas/tools/python/2.94.0/api/core/models/oci.core.models.LaunchInstancePlatformConfig.html

InstanceConfigurationLaunchInstancePlatformConfig and LaunchInstancePlatformConfig are used for two different ways of launching instances and are not interchangeable. LaunchInstancePlatformConfig is used in the most typical way of launching instances. InstanceConfigurationLaunchInstancePlatformConfig is used when launching an instance from an instance configuration: https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/launchinginstance.htm#instance-configuration.
 
is_symmetric_multi_threading_enabled and is_input_output_memory_management_unit_enabled are not present in either of the base objects listed above. They are only present in the individual child objects for individual architectures, for example they are present in both objects for Amd Rome BMs: 

https://docs.oracle.com/en-us/iaas/tools/python/2.94.0/api/core/models/oci.core.models.InstanceConfigurationAmdRomeBmLaunchInstancePlatformConfig.html#oci.core.models.InstanceConfigurationAmdRomeBmLaunchInstancePlatformConfig

https://docs.oracle.com/en-us/iaas/tools/python/2.94.0/api/core/models/oci.core.models.AmdRomeBmLaunchInstancePlatformConfig.html#oci.core.models.AmdRomeBmLaunchInstancePlatformConfig

**Comment by KartikShrikantHegde** [comment]
Hi @manorama-pidapa , I am closing this ticket for now, please re-open it if you run into issues. Thanks!
