### ISSUE TITLE
Can you help me on how to configure the subscription button in usage_reports_to_adw

### ISSUE THREAD

**Issue by xjuarez** [oracle/oci-python-sdk#497]

**Comment by adizohar** [comment]
Hi Xavier,
Subscription, Usage and billing information exist on the OCI Console, I am trying to not duplicate the functionality
If you would like to add subcription, you can add the code using the list_subscription method
You will need:
1. Add policy for read subscription information
2. Add Table subscription
3. Built subscription query in the python script and merge the information to the table
Doc = https://docs.oracle.com/en-us/iaas/tools/python/2.88.2/api/osub_subscription/client/oci.osub_subscription.SubscriptionClient.html#oci.osub_subscription.SubscriptionClient.list_subscriptions
Hope it helped.

**Comment by xjuarez** [comment]
Hi.
specifically want any table to be mailable
regards

**Comment by adizohar** [comment]
If you want to mail information from the console, you can create your own shell script , produce the report using oci cli and mail it, the usage2adw is only for loading usage to adw and generate reports
Example of oci-cli to generate subscriptions - oci organizations subscription list --compartment-id
OCI CLI doc = https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.20.3/oci_cli_docs/
Specific to subscriptions = https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.20.3/oci_cli_docs/cmdref/organizations/subscription/list.html

**Comment by xjuarez** [comment]
I mean the section in the apex application that I place in the image

![image](https://user-images.githubusercontent.com/7709679/203631454-7c8fe04b-3ae2-458a-af46-b00cabfbb0a6.png)

**Comment by adizohar** [comment]
1. Setup e-mail delivery and approved sender in OCI
   a) follow the link - https://docs.oracle.com/en-us/iaas/Content/Email/Reference/apex.htm
   b) Make sure you setup the smtp parameters using APEX_INSTANCE_ADMIN.SET_PARAMETER (sqlplus to admin@adw instance)
   c) test e-mail using sqlplus using apex_mail
2) Configure your apex application to use the approved sender (usually report@oracleemaildelivery.com approved)
   a) login to apex workspace
   b) Choose the application - 100
   c) Edit application definition
   d) In Property field - Application Email From Address - enter the approved sender name
Please bear in mind - default maximum size for an email sent from OCI using OCI Email Delivery is 2 Mb

I will create step by step how to set it up after the holidays

**Comment by xjuarez** [comment]
Thanks a lot

**Comment by adizohar** [comment]
I created new page in my personal github - https://github.com/adizohar/usage_reports_to_adw/blob/main/step_by_step_email_subscription.md

Will be published after the holidays to oracle sdk.

**Comment by xjuarez** [comment]
thanks is perfect

**Comment by xjuarez** [comment]
One question, is this possible with your own relay server?

**Comment by adizohar** [comment]
Yes you can

**Comment by xjuarez** [comment]
Hi Adizohar!, 

Are you going to republish the link that you placed at the top?

**Comment by adizohar** [comment]
Linked moved to new page - https://github.com/adizohar/usage_reports_to_adw/blob/main/step_by_step_howto.md#8-how-to-setup-e-mail-subscription

**Comment by xjuarez** [comment]
Oooo. thank's

**Comment by adizohar** [comment]
This is not SDK issue, please refer to OCI Documentation on e-mail delivery
You can open SR to Oracle Support for more info about e-mail delivery if you cannot set it up.
https://docs.oracle.com/en-us/iaas/Content/Email/Concepts/overview.htm

**Comment by KartikShrikantHegde** [comment]
@xjuarez I will be closing this issue, please follow the instructions specified by Adi, Thanks!
