### ISSUE TITLE
Can we rename Default route table in Oracle Cloud Infrastructure

### ISSUE THREAD

**Issue by ayushsrinet** [oracle/oci-python-sdk#498]
Can we rename Default route table in Oracle Cloud Infrastructure

**Comment by KartikShrikantHegde** [comment]
Hi @ayushsrinet , yes you can. Here is the API and Python skeleton code to do that.

API -> https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/RouteTable/UpdateRouteTable
Python Skeleton sample -> https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/RouteTable/UpdateRouteTable:~:text=Java%20SDK-,Python,-SDK

In the UpdateRouteTable API, specify the rt_id (ocid value) that was created in the default route table.

**Comment by KartikShrikantHegde** [comment]
Hi @ayushsrinet , I am closing this issue since we haven't heard back from you. Hope the above pointers helped solve the problem for you. Please feel free to reopen otherwise.
