### ISSUE TITLE
setup.cfg - universal = 1 should be removed as this project is not applicable for python2

### ISSUE THREAD

**Issue by jakegt1** [oracle/oci-python-sdk#504]
Currently the wheel produced suggests that it works with python2, which it does not.

While python2 is deprecated, it is probably helpful to legacy maintainers to find that if they `pip install oci` it doesn't install something not applicable for python2.

**Comment by jakegt1** [comment]
Technically it's probably late to help anybody with this problem as previous releases will still be broken and it will still download them, but seems illogical to have it setup this way anyway.

**Comment by github-anurag** [comment]
@jakegt1 
Thanks for bringing this up. We are aware about this inconsistency. We are currently evaluating if changing the wheel name could affect any internal services. Once we finish the evaluation and find no issues we will fix the wheel name

**Comment by github-anurag** [comment]
@jakegt1 
We have renamed the wheel to remove py2 from the name
