### ISSUE TITLE
Update examples/usage_reports_to_adw Python example to use python-oracledb

### ISSUE THREAD

**Issue by cjbj** [oracle/oci-python-sdk#509]
[usage_reports_to_adw/step_by_step_manual_installation.md](https://github.com/oracle/oci-python-sdk/blob/master/examples/usage_reports_to_adw/step_by_step_manual_installation.md) and [usage_reports_to_adw/usage2adw.py](https://github.com/oracle/oci-python-sdk/blob/master/examples/usage_reports_to_adw/usage2adw.py) use the deprecated cx_Oracle driver. The latest version of this driver is now called python-oracledb.  The example files need to be updated. For info about python-oracledb see the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a).

For the instructions MD file, change the pip install from "cx_Oracle" to "oracledb" and remove step 7 since Instant Client isn't needed.  You may want to keep the line setting `TNS_ADMIN=$HOME/ADWCUSG`

For the code, moving to oracledb should be a simple name change.  You'll also need to pass in the wallet location and wallet password in the [connection call](https://github.com/oracle/oci-python-sdk/blob/master/examples/usage_reports_to_adw/usage2adw.py#L1765). See the 'Thin mode' instructions in the [user documentation](https://python-oracledb.readthedocs.io/en/latest/user_guide/connection_handling.html#install-the-wallet-and-network-configuration-files).  While you're editing the Python  file, remove the calls to `prepare()` and instead just call `executemany(sql, data)`.  Also using triple quotes will simplify your multi-line SQL statements.

**Comment by adizohar** [comment]
Hi Christopher
Thank you and appreciate the suggestions , I will do the change, test and deploy as well to the marketplace
I use sqlplus to configure the apex application, I could use sqlcl, maybe in the future.

**Comment by cjbj** [comment]
You could probably use python-oracledb to do the configuration.

**Comment by adizohar** [comment]
I could do everything with python-oracledb but it will require effort to program it, additional it would be difficult to debug the database without sqlplus incase I have issues, I could use sqlcl which requires java.

Anyway, I did the changes and testing, I pushed the changes to my private git - https://github.com/adizohar/usage_reports_to_adw

Will push to oracle sdk on 2/7/2023
Appreciate. your help !

**Comment by cjbj** [comment]
With a python script you would have **much better** flow control and error handling than with SQL*Plus or SQLcl.    If you want to hack with ad-hoc queries, you might be able to use https://github.com/oracle/python-oracledb/blob/main/samples/sqlp.py (depending what SQL script features you want).  And why install a JRE or Instant Client to bloat the SDK?!  

Re the change, some small review comments: where is the `pip install oracledb` done?  The product is called SQL\*Plus, not SQLPLUS.  It's "Instant Client" with a capital C.   Thanks for making the changes.

**Comment by adizohar** [comment]
I hear you and will work on it in future release, I am trying to avoid too many changes for the marketplace image that works well. I really appreciate your feedback !
the pip install located in few places, setup/setup_packages.sh, step_by_step_manual_installation.md
And in the marketplace image I install myself

**Comment by adizohar** [comment]
Chris, the changes have been deployed to OCI SDK, for your info

**Comment by cjbj** [comment]
Thank you!

A couple of small comments: (i) no need to do `export LD_LIBRARY_PATH=$CLIENT_HOME/lib` since the RPMs already set the library search path (ii) typo 'thic' in the .py file

**Comment by adizohar** [comment]
Thank you Chris for the info, I fixed the thic->thick and removed the LD_LIBRARY_PATH from the shell scripts
Currently at https://github.com/adizohar/usage_reports_to_adw next week at OCI SDK
Appreciate it.

**Comment by cjbj** [comment]
Thank you
