### ISSUE TITLE
tag_resources_in_tenancy.py throwing errors for block volumes

### ISSUE THREAD

**Issue by revnav** [oracle/oci-python-sdk#512]
Getting this error for block volumes when running tag_resources_in_tenancy.py

Error in handle_object: Block Volumes ('list_volumes() takes 1 positional argument but 2 were given',)

**Comment by adizohar** [comment]
HI
Thank you very much for the info
I fixed the issue and will push to OCI SDK next week
In a meantime, you can take the new code from https://github.com/adizohar/tag_resources_in_tenancy

**Comment by revnav** [comment]
Thanks 🙏

On Feb 2, 2023, at 12:56 PM, Adi Zohar ***@***.***> wrote:

﻿

CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you validate the sender and know the content is safe. Please report via Phish Alert Button. If unable to, please attach this email and send to ***@***.******@***.***>***@***.***> if you believe this email is suspicious.

HI
Thank you very much for the info
I fixed the issue and will push to OCI SDK next week
In a meantime, you can take the new code from https://github.com/adizohar/tag_resources_in_tenancy<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadizohar%2Ftag_resources_in_tenancy&data=05%7C01%7Cnavdeep.saini%40centroid.com%7C5add6021ac614ed8c02e08db055fe1f7%7Cdf5a6910e0054af28d8e5e19c08b842d%7C0%7C0%7C638109681617800298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=guoGPDZot3%2Bj18WcmC3I23CRXWmoxY%2BZozJQPrDrusk%3D&reserved=0>

**Comment by adizohar** [comment]
Hi, The Changes have been deployed to OCI SDK, please let me know if additional info required.

**Comment by KartikShrikantHegde** [comment]
Hi @revnav , I will be closing this ticket for now. Please feel free to re-open if you run into a problem.
