### ISSUE TITLE
tag_resources_in_tenancy.py not tagging ExaCS

### ISSUE THREAD

**Issue by revnav** [oracle/oci-python-sdk#519]
tag_resources_in_tenancy.py does not tag ExaCS on OCI. It did not tag infrastructure, VM clusters, Oracle Homes and Oracle Databases on ExaCS.

**Comment by adizohar** [comment]
HI Revnav, the tag_resources_in_tenancy.py only tag certain services, on the database side, only DB System and DB Autonomous (Shared) currently supported, In the future I will add more services

**Comment by revnav** [comment]
Thanks.
