### ISSUE TITLE
Python oci monitoring script for Exadata Cloud@Customer ?

### ISSUE THREAD

**Issue by alessandratesta** [oracle/oci-python-sdk#522]
Hi, do you have perhaps
some example working on exadata Cloud@Costomer?

**Comment by adizohar** [comment]
I developed script to extract ExaCC information (Repo not Performance), please check showoci under the examples folder, can generate a nice output, JSON or CSV with the infrastructure, vm clusters and databases.

**Comment by KartikShrikantHegde** [comment]
Hi @alessandratesta , ExaCC team confirmed that Oracle Exadata Database collects metrics and posts them to the OCI Monitoring service.

1. https://docs.oracle.com/en/engineered-systems/exadata-cloud-service/ecscm/metrics-for-exadata-database-service-on-dedicated-infrastructure-in-the-monitoring-service.html#GUID-B82F2A9D-56C4-459A-9EEE-A3330741F31F
2. https://docs.oracle.com/en/engineered-systems/exadata-cloud-service/ecscm/metrics-for-exadata-cloud-infrastruture-in-the-database-management-service.html#GUID-1CA934B5-7191-4A6D-906A-E29B4A287729

These metrics can be retrieved from OCI Monitoring SummarizeMetricsData api:
https://docs.oracle.com/en-us/iaas/api/#/en/monitoring/20180401/MetricData/SummarizeMetricsData

An example is available on this page using Python SDK.

Please let us know if this addresses your question.

**Comment by KartikShrikantHegde** [comment]
Hi @alessandratesta , We haven't heard from you in a while. So closing this ticket, please feel free to re-open it if you are still facing the issue. Thanks.
