### ISSUE TITLE
How do I send user_data when launching an instance?

### ISSUE THREAD

**Issue by nathan-vu** [oracle/oci-python-sdk#54]
[LaunchInstanceDetails](https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/datatypes/LaunchInstanceDetails) supports providing `user_data`: base64-encoded data to be used by Cloud-Init to run custom scripts or provide custom Cloud-Init configuration.

When I try and send this through using the below code:

```
with open('/tmp/cinit.sh') as myfile:
    l_cinit=myfile.read()

l_cinit_b=base64.encodestring(l_cinit.encode('ascii'))

launch_instance_details = oci.core.models.LaunchInstanceDetails (
    display_name=p_instance_info['instance_name'],
    compartment_id=p_instance_info['compartment_id'],
    availability_domain=p_instance_info['availability_domain'],
    shape=p_target_shape,
    source_details=oci.core.models.InstanceSourceViaBootVolumeDetails(boot_volume_id=p_instance_info['boot_volume_id']),
    create_vnic_details=oci.core.models.CreateVnicDetails(
        subnet_id=p_instance_info['subnet_id'],
        private_ip=p_instance_info['priv_ip']
    ),
    metadata={
        "user_data":l_cinit_b
    }
)
launch_instance_response = p_compute_client.launch_instance(launch_instance_details)
```

I receive this error from the SDK:
```
TypeError: Field metadata.user_data with value b'<redacted>' was expected to be of type str but was of type bytes
```

If I do `"user_data":l_cinit_b` then I get this error instead:

```
oci.exceptions.ServiceError: {'opc-request-id': '<redacted>, 'code': 'InvalidParameter', 'message': 'user_data must be base64 encoded', 'status': 400}
```

How do I successfully send `user_data` via the Python SDK?

**Comment by nathan-vu** [comment]
`user_data` can be taken from a file as follows:

```
user_data_file=open('/tmp/cinit.sh’, ‘rb')
content=base64.b64encode(user_data_file.read()).decode('utf-8’)
```

We will also be adding a utility function in the next SDK release which will take in a file path and output a Base64-encoded string suitable for use as `user_data`

**Comment by nathan-vu** [comment]
The utility function has now been added to the SDK. An example of using it can be found [here](https://github.com/oracle/oci-python-sdk/blob/97e2c7fe55a6e516f6d22a03fcc2e89a59b73ccd/examples/launch_instance_example.py#L257)

**Comment by sufpro** [comment]
Hi Nathan, using the sample script you i am using user_data function based on the 

> The utility function has now been added to the SDK. An example of using it can be found [here](https://github.com/oracle/oci-python-sdk/blob/97e2c7fe55a6e516f6d22a03fcc2e89a59b73ccd/examples/launch_instance_example.py#L257)

Hi Nathan, using the sample py script, i am trying to run a shell script(.sh), containing yum -y update and install docker commands, these are quite time consuming commands(may take upto 4-5 minutes to finish), i can see the sample py file runs fine and compute instance gets created, but none of the command in shell script gets executed,  seems somehow the .sh file i am trying to run through do not run at all or fully, given below is an extract from the py file.
Appreciate any help, as i need to create compute instance along with few software installations using pyton

 print('*****Installing docker*****')
 print()
 instance_metadata['user_data'] = oci.util.file_content_as_launch_instance_user_data(
        './install-docker.sh'
    )
