### ISSUE TITLE
Formatting json ResourceSummaryCollection output to use the variable wit hpython

### ISSUE THREAD

**Issue by alessandratesta** [oracle/oci-python-sdk#540]
search_resources_response = resource_search_client.search_resources(
        search_details=oci.resource_search.models.FreeTextSearchDetails(
            #type="FreeText",
            text="<<PDB name>>")
            #matching_context_type="HIGHLIGHTS")
      )
    )
The output looks like:
{
  "items": [
    {
      "additional_details": {},
and so on 

How can I transfrom the json output in something I can use with python to extract and you the information?

**Comment by github-anurag** [comment]
@alessandratesta 
You can refer the example code mentioned here: https://github.com/oracle/oci-python-sdk/blob/master/examples/search_example.py#L78 

Please feel free to re-open this issue if you still have issues.
