### ISSUE TITLE
update_workspace_details needs 2 attributes instead of 1

### ISSUE THREAD

**Issue by Olygo** [oracle/oci-python-sdk#546]
Hi,

issue in :

- **oci.data_integration.DataIntegrationClient**
- **update_workspace(workspace_id,  update_workspace_details)**
- **oci.data_integration.models.UpdateWorkspaceDetails(update_workspace_details)**

Using the following should work:

- details = oci.data_integration.models.UpdateWorkspaceDetails(defined_tags=my_defined_tags_dict)
- error:
- _'data_integration', 'status': 500, 'code': 'InternalError', 'opc-request-id': '....', 'message': 'Internal error occurred', 'operation_name': 'update_workspace', 'timestamp': '...', 'client_version': 'Oracle-PythonSDK/2.104.1',_

in order to update a single attribute (e.g. defined_tags) we must update 2 attributes, such as :

- details = oci.data_integration.models.UpdateWorkspaceDetails(defined_tags=my_defined_tags_dict, freeform_tags=my_freeform_tags_dict)

could you please fix sdk accordingly ?
Regards
Florian

**Comment by KartikShrikantHegde** [comment]
Hi @Olygo , Can you please confirm the version of the data integration service you are using?

**Comment by Olygo** [comment]
HI @KartikShrikantHegde 
 I use 'Oracle-PythonSDK/2.104.1', I don't understand you question about DI service ?
While the issue is not related to DI but SDK.
BTW, I just created a DI service from OCI.

**Comment by Olygo** [comment]
HI @KartikShrikantHegde

tested with Version: 2.105.0 same issue.

Regards.

**Comment by Olygo** [comment]
waiting for fix.
