### ISSUE TITLE
add multiple tenants issue for child tenancy

### ISSUE THREAD

**Issue by edwjack** [oracle/oci-python-sdk#550]
Hi,

It works fine when add a tenancy with config profile.

`run_report tenant1 tagspecial1 tagspecial2`

however if a tenancy is a child, it shows error not found

```
Connecting to Object Storage Service...
   Connected

Handling Usage Report... started at 2023-06-22 13:10:42

Error appeared - {'target_service': 'object_storage', 'status': 404, 'code': 'BucketNotFound', 'opc-request-id': 'sin-1:PDTT63dl79EO8pXZ5nWsKaFDTtxIKmPu0RDsLqZO6JJaaziCRglvxeX6gOkIjsuq', 'message': "Either the bucket named 'ocid1.tenancy.oc1..aaaaaaaaXXXXXXXXXXXX' does not exist in the namespace 'bling' or you are not authorized to access it", 'operation_name': 'list_objects', 'timestamp': '2023-06-22T13:10:43.730351+00:00', 'client_version': 'Oracle-PythonSDK/2.104.3', 'request_endpoint': 'GET https://objectstorage.ap-singapore-1.oraclecloud.com/n/bling/b/ocid1.tenancy.oc1..aaaaaaaaXXXXXXXXXXXX/o', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_bucketnotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/objectstorage/20160918/Object/ListObjects for details on this operation's requirements. If you are unable to resolve this object_storage issue, please contact Oracle support and provide them this full error message."}
```

Could you please guide how to solve it?

**Comment by adizohar** [comment]
Only parent tenancy has the cost and usage files not child

**Comment by edwjack** [comment]
Thank you for your prompt answer.

I have checked parent cost and usage file but there was no other tenancy id (only parent id)
additionally in child tenancy, I can download cost and usage file and there was only child tenancy id in the file.

![image](https://github.com/oracle/oci-python-sdk/assets/85690869/822717ed-97a0-4dc3-bf7d-864a9b2ce762)

**Comment by adizohar** [comment]
Hi , Can you please share which script are you running ? 
Child can have cost and usage files up to the time it join the parent, from the time it joined the parent, the parent will report the child.
If you are using usage-api, it is different, you can run on child or on parent.

**Comment by edwjack** [comment]
got it. thanks!
I checked tenant id having all child (expected tenant name).
