### ISSUE TITLE
Emty line in function definition shouldn't be. There are two of them in this block

### ISSUE THREAD

**Issue by etyoma** [oracle/oci-python-sdk#552]
https://github.com/oracle/oci-python-sdk/blob/1b3d525e21896223bc3a02773215679d9baf87ed/examples/stream_example.py#L99

**Comment by adizohar** [comment]
Etyoma, Why single empty line not allowed inside function ?

Please check PEP 8 - [link](https://peps.python.org/pep-0008/#:~:text=Blank%20Lines,-Surround%20top%2Dlevel&text=Method%20definitions%20inside%20a%20class,a%20set%20of%20dummy%20implementations).)

**Comment by KartikShrikantHegde** [comment]
Hi @etyoma , did you get the answer from the above comment by Adi? Let us know so that we can close this issue. Thanks.

**Comment by KartikShrikantHegde** [comment]
Hi @etyoma , I am closing this ticket for now, please feel free to re-open if you run into issues again. thanks!
