### ISSUE TITLE
 Running ShowOCI_CSV2ADW  issue

### ISSUE THREAD

**Issue by xjuarez** [oracle/oci-python-sdk#555]
Version      : 23.04.11
OracleDB     : Thick Drivers

Connecting to database ADWCUSG_low...Connected

1.  OCI_SHOWOCI_COMPUTE                      compute.csv
DatabaseError at procedure: handle_table() - before executemany - ORA-12899: value too large for column "USAGE"."OCI_SHOWOCI_COMPUTE_TMP"."SECURITY_GROUPS" (actual: 2092, maximum: 1000)

DatabaseError at procedure: handle_table() - before executemany - ORA-12899: value too large for column "USAGE"."OCI_SHOWOCI_COMPUTE_TMP"."SECURITY_GROUPS" (actual: 2092, maximum: 1000)
Finish Tue Jun 27 23:10:30 GMT 2023 - local  with **** Errors ****
Completed at Tue Jun 27 23:10:30 GMT 2023..

**Comment by adizohar** [comment]
Hi Xavier

I will push new fix for next Tuesday
To have it fixed for you, please run the below commands:

```
alter table USAGE.OCI_SHOWOCI_COMPUTE modify (SECURITY_GROUPS varchar2(4000));
alter table USAGE.OCI_SHOWOCI_COMPUTE_TMP modify (SECURITY_GROUPS varchar2(4000));
```

**Comment by adizohar** [comment]
I created pull request internally to merge on 7.4.2023

**Comment by xjuarez** [comment]
Excellent, worked perfect
Thank you

**Comment by adizohar** [comment]
Hi Xavier, if issue solved, can you please close the ticket ? 
Appreciate it.
