### ISSUE TITLE
Bump python-dateutil to new version

### ISSUE THREAD

**Issue by nathan-vu** [oracle/oci-python-sdk#57]
See: https://github.com/oracle/oci-cli/pull/67

We probably need to update the SDK and CLI in lock-step so that our dependency closure doesn't run the risk of looking to weird (at least with regards to this dependency)

**Comment by arthall** [comment]
@riconnon, thank you for the PR.  I merged it with master and it will be part of the release tomorrow.

**Comment by arthall** [comment]
This is now part of 1.4.1 release
