### ISSUE TITLE
vcn_cidr value is not correct in network_subnet.csv file when the VCN has more than 1 CIDR

### ISSUE THREAD

**Issue by carlos-delgadocastano** [oracle/oci-python-sdk#574]
Hello,

I am executing the script to have all the information of the subnets in my tenant.

I have found that in the network_subnet.csv file, when a VCN has more than one CIDR block, all the subnets it has in his "vcn_cidr" field, the value of the first CIDR block of the VCN even if that is not the correct range in which the subnet is located.

Could you please take a look?

Thank you in advance,
Best Regards,

**Comment by adizohar** [comment]
vcn_cidr is deprecated, you should use the vcn_cidrs field instead
I emptied the vcn_cidr on all csv and outputs and will remove the column in the future
changes will be deployed at next deployment date

**Comment by KartikShrikantHegde** [comment]
Hi @carlos-delgadocastano , Please try the above step from Adi and let us know if you still face the issue. Thanks.

**Comment by adizohar** [comment]
from tomorrow (deplyment) vcn_cidr will be emptied in showoci and only vcn_cidrs will be populated
next month I will remove the vcn_cidr field.

**Comment by carlos-delgadocastano** [comment]
Thank you very much for the update. I am using vcn_cidrs field! :)

**Comment by KartikShrikantHegde** [comment]
Hi @carlos-delgadocastano , can we close this ticket for now?

**Comment by carlos-delgadocastano** [comment]
Sure, you can close, thank you!
