### ISSUE TITLE
Abnormally pinned setup.py dependencies

### ISSUE THREAD

**Issue by pakal** [oracle/oci-python-sdk#59]
Setup.py should not pin dependencies, else the package can't coexist with others. At worst, min (or max) versions should be specified.

But pytz should never be pinned, people need recent versions of it all the time.

**Comment by arthall** [comment]
@pakal, thank you for the feed back.  We are currently re-evaluating how we pin dependancies

**Comment by Kimamisa** [comment]
This is really bothering us too. When is the release planned ?

**Comment by arthall** [comment]
There are on going discussions about how to handle some of the requirements.  The concern  is that we are certifying oci-python-sdk has been verified with all versions of a requirement if it is unpinned.  We do not currently have testing in place to make that statement.  

For Pytz this doesn't appear to be an issue so we will be pinning it to a minimum version with no maximum.  That change is due out with with the next release on 6/28.

For the other dependencies we are working on tests and alerts to help us keep up with changes to the dependencies.  We are also looking into which dependencies we can vendor into the project so oci-python-sdk can rely on a particular version without imposing that version on consumers of the SDK.  As more details are decided on they will be shared.  

Other than pytz which pinned dependancies are causing issues?  Knowing that will help us plan.

**Comment by Kimamisa** [comment]
I understand the need of pinning versions for certification, but the certification can be done with the requirements proposed in the requirements.txt file, not in the setup.py. 

A better way (IMO) would be to do as you suggest, pin to a minimum without maximum, or, at least, allow minors, like you did with idna in your setup.py file.

I had conflicts on the following dependencies:
- cryptography
- PyJWT
- python-dateutil
- pytz
- requests

**Comment by arthall** [comment]
The pinning for Pytz and python-dateutils was updated with the 1.4.4 release.

```
python-dateutil>=2.5.3,<=2.7.3
pytz>=2016.10
```

There is work being done for requests, PyJWT and cryptography.  

@Kimamisa, Thank you for sharing your list of dependencies with conflicts.  That is helping with prioritization.

**Comment by pakal** [comment]
Thanks for the unpinning of these, it'll already help coexistence with most python packages.

Maybe a short tox config file would suffice to validate OCI against numerous combined versions of the other few dependencies ?

**Comment by jasonyin** [comment]
PyJWT and cryptography has been updated in [v1.4.5](https://github.com/oracle/oci-python-sdk/releases/tag/v1.4.5).

@pakal @kartikswami does this version works for you guys?

**Comment by zoza** [comment]
But why not to use virtualenv and create a sandbox for oci python sdk + deps only?

**Comment by pakal** [comment]
Thanks @jasonyin, yes for now we're doing it work by overridding some package versions in our own requirements.txt file when needed, but we run the risks of new conflicts when our dependency environment evolves (eg. pinning "requests==2.18.4" is a very strong rule, that a client like oci-python should not have to impose to the whole project).

@zoza yes we use virtualenvs, but our codebase which calls OCI has other dependencies, and these can conflict with the too strong requirements of OCI. Creating microservices just as workarounds to "dependency hells" is unnecessary workload: utilities and libraries should be able to coexist without problems across lots of different minor (=retrocompatible) versions.

**Comment by arthall** [comment]
In the v2.0.0 release we have vendored the requests and six packages.  Because of this oci-python-sdk no longer has a dependency on a pinned version of requests.  

Does latest version resolve this issue for you @pakal and @Kimamisa?

**Comment by pakal** [comment]
It helps a lot yes, only configparser has dependency has to be relaxed now it seems (it's a quite common and retrocompatible package, so relaxing this should be fine)

**Comment by arthall** [comment]
@pakal I'm sorry, I didn't realize that configparser was also causing a conflict.  I'll add a task for working on relaxing the pinning on that dependency for the next release.

**Comment by arthall** [comment]
@pakal I didn't get the changes in for configparser in this release.  I've tested back to 3.5.0b1.  Is there any need to go back further than that?

**Comment by arthall** [comment]
I tried to test with 3.3.0r2 and found that it would not work with Python 3.  Config parser is now pinned as "configparser>=3.5.0b1".  With the next release I will close this ticket if there are no objections.

**Comment by arthall** [comment]
Setup.py now allows anything over 3.5.0b1 for configparser.  I'm closing this issue now.  Please open a new issue if there are other dependencies which are causing problems.

**Comment by pakal** [comment]
Thanks
