### ISSUE TITLE
How to use session based authentication

### ISSUE THREAD

**Issue by fxcali** [oracle/oci-python-sdk#590]
I am trying to use sessions based authentication "oci session authenticate" with the SDK and I am looking for some examples of how to get this authentication method to work. I am able to run scripts using API key authentication but there is now a requirment to use sessions based authentication. When I exect the code against "VirtualNetworkClient" I get an error that 'user' is missing, which I shouldn't need since this is token based. When I provide the ocid for the user I then get an error that the user is not authenticated. Is their an example of how to do this?

thanks

**Comment by adizohar** [comment]
Please take a look at my code at showoci, I use session base authentication and resource base authentication
Check the procedure generate_signer_from_config_and_security_token
https://github.com/oracle/oci-python-sdk/blob/master/examples/showoci/showoci_service.py

**Comment by fxcali** [comment]
thanks you. I crabbed the config from that section and was very similar to what I had found but I still get stuck.
Traceback (most recent call last):

  File "script.py", line 48, in <module>
    core_client = oci.core.VirtualNetworkClient(config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\core\virtual_network_client.py", line 81, in __init__
    validate_config(config, signer=kwargs.get('signer'))
  File "venv\Lib\site-packages\oci\config.py", line 164, in validate_config
    raise InvalidConfig(errors)
oci.exceptions.InvalidConfig: {'user': 'missing'}

**Comment by adizohar** [comment]
Did you run the oci authenticate ? 

```
oci session authenticate --profile-name profile_name --region us-ashburn-1  --tenancy-name tenant_name
```
You will need to pass the config and the profile generated by the OCI authenticate

**Comment by fxcali** [comment]
looks like I was just missing "(config, signer=signer)"  in my code when calling the network portion. Thank you! I am able to get a response now.

**Comment by adizohar** [comment]
Perfect, if this solve your issue, please kindly close it.
Thank you

**Comment by jyotisaini** [comment]
HI @fxcali I am closing this issue. Feel free to reopen it if you run into issues.
