### ISSUE TITLE
DB Systems - Databases with Failed state aren't exported to report

### ISSUE THREAD

**Issue by eps-oci** [oracle/oci-python-sdk#595]
Hi,

We have realized that DB Systems databases in failed state aren't exported to report.

Regards,
Ernani

**Comment by adizohar** [comment]
Can you please elaborate a bit more, which report ?

**Comment by eps-oci** [comment]
When we run showoci.py -d, we have receiving a list of Oracle databases created, except databases with <failed state>. For example dba tried to do a reshape and failed, the database came up again but the state still in <Failed>, this database isn't exported to report.

**Comment by adizohar** [comment]
Currently showoci does not extract status failed, I will add it for next version for next week Tuesday.

**Comment by eps-oci** [comment]
Thank you!

**Comment by adizohar** [comment]
Hi, In order to have it fix quickly, you can edit the file showoci_service.py
Go to line 899 and change FAILED to FAILEDXXX (it is in procedure check_lifecycle_state_active)
Run again and let me know

**Comment by eps-oci** [comment]
I forwarded your suggestion, but I didn't receive a feedback yet.

**Comment by eps-oci** [comment]
Hello!! It's been working fine!!! Thank you!

**Comment by adizohar** [comment]
Great, it will be implemented next Tue, if you are happy, can you kindly close the ticket

**Comment by eps-oci** [comment]
Thanks for the quick correction and attention!
