### ISSUE TITLE
Blank column in compute report

### ISSUE THREAD

**Issue by carlos-delgadocastano** [oracle/oci-python-sdk#602]
Hi, 

We have detected that in the compute report, between columns "instance_id" and "extract_date" there are an empty column, without title and all the values are blank.

It has any meaning this behaviour?

Thank you in advance,
Best Regards,

**Comment by adizohar** [comment]
Code was amended and will be pushed next week Tuesday
Please let me know if the above solved the problem ?

**Comment by richachugh11** [comment]
@carlos-delgadocastano / @adizohar - what is the status of this ticket. Can this be closed ?

**Comment by adizohar** [comment]
It has been fixed and deployed, can be closed
