### ISSUE TITLE
scim_query not working correctly

### ISSUE THREAD

**Issue by bathax** [oracle/oci-python-sdk#603]
I'm getting a http 400 no matter what scim query I put in to any api call.  sample request id: 0D41184883584AB1A05830164DD7CF57/8417394DEBC27FEA318E992E4E7D77E5/83B59B3354A2A25B44750969FFA25083.

I'm simply querying: timeCreated ge '{start_time}'

**Comment by bathax** [comment]
I used the example in the docs, no luck.  I still get a 400 invalid parameter.

**Comment by bathax** [comment]
I'm still getting this, the timestamp looks correct:
```2023-12-04T17:35:58Z
Unexpected error when retrieving events: {'target_service': 'data_safe', 'status': 400, 'code': 'InvalidParameter', 'opc-request-id': '01B07720112740399769692644254868/CAB94E4B63A21B127B3058A608A97F91/5BB6738C6225BE0C814692BAA2DDB97A', 'message': 'Invalid Query', 'operation_name': 'list_alerts', 'timestamp': '2023-12-04T18:11:44.719842+00:00', 'client_version': 'Oracle-PythonSDK/2.117.0', 'request_endpoint': 'GET https://datasafe.eu-amsterdam-1.oci.oraclecloud.com/20181201/alerts', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_400__400_invalidparameter for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/data-safe/20181201/AlertSummary/ListAlerts for details on this operation's requirements. If you are unable to resolve this data_safe issue, please contact Oracle support and provide them this full error message."}```

**Comment by adizohar** [comment]
Please change your code as constant and run it
Use 
```
scim_query = 'timeCreated ge "2023-06-01T01:01:01Z"'
```
Please let me know if this works, if yes, you need to make the string exactly as above with " and the time as is
You change - to : on the time in your code, also you have ' and not " around the date+time

**Comment by bathax** [comment]
I tried `        alerts = datasafe_client.list_alerts(compartment.id, scim_query='query=timeCreated ge "2023-06-01T01:01:01Z"')` and got the same error.  The query might return nothing, should that return an error?

**Comment by adizohar** [comment]
no alerts will return with []
Please try the below (you had query = which not required)
```
alerts = datasafe_client.list_alerts(compartment.id, scim_query='timeCreated ge "2023-06-01T01:01:01Z"')
```

**Comment by adizohar** [comment]
Great, thank you !

**Comment by bathax** [comment]
@adizohar I'm getting this on audit_events now:
```Unexpected error when retrieving events: {'target_service': 'data_safe', 'status': 400, 'code': 'InvalidParameter', 'opc-request-id': 'BD6F257905A1484687489610616CF080/0FE4B6F1A442EEAB2C71DC6066C93E68/16DD6292BE1109905E6FC61A3329E24B', 'message': 'Invalid Query: Incorrect Attribute operationTime', 'operation_name': 'list_audit_events', 'timestamp': '2024-01-16T18:58:32.705317+00:00', 'client_version': 'Oracle-PythonSDK/2.117.0', 'request_endpoint': 'GET https://datasafe.us-ashburn-1.oci.oraclecloud.com/20181201/auditEvents', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_400__400_invalidparameter for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/data-safe/20181201/AuditEventSummary/ListAuditEvents for details on this operation's requirements. If you are unable to resolve this data_safe issue, please contact Oracle support and provide them this full error message."}```
this should be a valid attribute, right?

**Comment by adizohar** [comment]
We fixed the issue on datasafe_client.list_alerts, 
Can you send the full parameters for list_audit_event, it seems you don't pass the correct info for operationTime
Please follow the doc - https://docs.oracle.com/en-us/iaas/tools/python/2.118.1/api/data_safe/client/oci.data_safe.DataSafeClient.html#oci.data_safe.DataSafeClient.list_audit_events, please try:
```
scim_query='operationTime ge "2024-01-01T01:01:01Z"'
```

**Comment by bathax** [comment]
`        audit_events = datasafe_client.list_audit_events(compartment.id, scim_query= f'operationTime ge "2024-01-01T01:01:01Z"')` gives the same error.

**Comment by adizohar** [comment]
Please try:
```
scim_query = 'timeCollected ge "2023-06-01T01:01:01.000Z"'
alerts = datasafe_client.list_audit_events(compartment_id=compartment, scim_query=scim_query).data
```
