### ISSUE TITLE
resource level  billing type not gave api call  

### ISSUE THREAD

**Issue by Gopichand785** [oracle/oci-python-sdk#608]
resource level billing type not showing any  api call.
suppose , i have one instance it is capcity take on-demand -i need on-demand instance billing type appilicable (pay-as-you-go,byol ,universal credits ,anuval credits).
can you please let us know which api call provides this information

**Comment by Gopichand-Heeddata** [comment]
@richachugh11 @adizohar can you look into this provide appropriate  API calls

**Comment by adizohar** [comment]
Can you please explain what exactly you need ? we don't assign billing per specific resource, we assign billing per your tenant subscription those can be found using the subscription APIs

**Comment by Gopichand785** [comment]
Hi @adizohar ,


what i am looking is to get the billing type of the resource and the amount used for the allocated subscription level.


ok if we assign billing type for the tenant and if we want to check how much the particular resource used in the subscription amount how we can do it. is there an api call for the resource level, this is what i am looking for

**Comment by adizohar** [comment]
Gopi, on OCI, currently you cannot allocate different billing types per resources, you allocate the billing type per subscription (tenant) and you can check it using the subscription api or at the console the subscription button under the cost analysis.

**Comment by Gopichand-Heeddata** [comment]
Thank you for providing the information @adizohar

**Comment by bhagwatvyas** [comment]
Closing this issue, feel free to reopen if you need more assistance
