### ISSUE TITLE
how to get the resource state in the tenancy 

### ISSUE THREAD

**Issue by alvenkatesh** [oracle/oci-python-sdk#610]
Hi ,

i am trying to get the resource life cycle state of all the resources in the tenancy or compartments.

i have used the list_analytics_instances api call and the lifecycle_state values are ["ACTIVE", "CREATING", "DELETED", "DELETING", "FAILED", "INACTIVE", "UPDATING"]    but i am getting the response as empty. 

i have also noticed that the life cycle state in the cloud console is RUNNING but the api call does not accept the key word RUNNING.  

is there any mistake or i am going in the wrong way. please let me know.

and also is there an api call to get the active resources in a tenancy or compartment

**Comment by adizohar** [comment]
Hi, I am running as well and see "ACTIVE" or "INACTIVE" lifecycle_state
Please check https://github.com/oracle/oci-python-sdk/tree/master/examples/showoci

**Comment by alvenkatesh** [comment]
Hi @adizohar 

I have those examples, is there any kind of permissions need to be granted from the console account or the api should get us the response of the life cycle state of the resources.

any thing am i missing here.

**Comment by alvenkatesh** [comment]
Hi @adizohar,

i am using the resourcesearchclient to get all the resources and the code is:

search_resources_response = resource_search_client.search_resources(
    search_details=oci.resource_search.models.FreeTextSearchDetails(
        text=" lifecyclestate = 'Active' ",
     ),
    limit=5000,
    tenant_id="my_tenancy_id",
    )
   
in the above code i am using the lifecyclestate as Active, Inactive, and Stopped and for the limit value even if i have given as 5000, the response is 1000 resources only and i have found out that there is a limit for the response as 1000 resources only. and in tenant_id i am giving my_tenancy_id. 
    
in order to get all the resources in the tenancy which are more that 1000 resources. how can i use this api call, can i use pagination or are there any other methods what do you suggest?

**Comment by adizohar** [comment]
Here is the code:
`
import oci

config_file = "~/.oci/config"
config = oci.config.from_file(config_file, "DEFAULT")
query = "lifecyclestate = 'Active'"

search_client = oci.resource_search.ResourceSearchClient(config)

return_data = oci.pagination.list_call_get_all_results(
    search_client.search_resources,
    search_details=oci.resource_search.models.FreeTextSearchDetails(text=query)
).data

print(f"Total Items: {len(return_data)}")
`

**Comment by alvenkatesh** [comment]
@adizohar 

i understand the pagination and got the code as you mentioned above is there any better approaches better than using the pagination.

**Comment by adizohar** [comment]
No, one call returns up to 1000 items, you can use loop instead of the pagination, please check the pagination code.

**Comment by adizohar** [comment]
Hi , no problem, if the issue resolved, can you please close the ticket ? 
Thank you

**Comment by alvenkatesh** [comment]
closing this ticket as the issue is solved from my end.

**Comment by adizohar** [comment]
Thank you !
