### ISSUE TITLE
Generate bypass code with python OCI

### ISSUE THREAD

**Issue by THEBESTSZ** [oracle/oci-python-sdk#630]
Is it possible to remove the phone authenticator, create a bypass or generate an idcs to access https://idcs-(id).identity.oraclecloud.com via OCI command? I formatted my cell phone and lost my authenticator, but I have the credentials to access via OCI api through python, and I would like to know if it is possible, could anyone help me?

**Comment by adizohar** [comment]
I would recommend to use oci-cli
first query your user:
```
oci identity-domains user  get --user-id ocid1.user.oc1..xxxxxx --endpoint https://idcs-xxxxxxxx.identity.oraclecloud.com
```
MFA information located at urn-ietf-params-scim-schemas-oracle-idcs-extension-mfa-user

Please check the documentation - https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.38.0/oci_cli_docs/cmdref/identity-domains/user/patch.html

**Comment by jyotisaini** [comment]
Hi @THEBESTSZ Let us know if you need any further assistance with this.

**Comment by paihari** [comment]
@jyotisaini @adizohar 
I need some assistance here, i am in similar situation.

I can use python-sdk or OCI CLI, but I miss the code or command to generate bypass code

**Comment by paihari** [comment]
For reference 

[Reddit Post](https://www.reddit.com/r/oraclecloud/comments/1itil0g/recovering_oci_mfa_access_when_your_mobile/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
