### ISSUE TITLE
showoci stuck while running for all resources

### ISSUE THREAD

**Issue by undamn89** [oracle/oci-python-sdk#636]
Hi, i´m running showoci but it get stuck in this part. Alwayas after printing OCE Native.
Also get stuck with this parameters
python3 showoci.py -dt -ani
python3 showoci.py -dt -ani -csv CSV> rnpcsv.txt
python3 showoci.py -dt -paas

juan_unda@cloudshell:showoci (us-ashburn-1)$ python3 showoci.py -dt -paas

############################################################
#                        showoci.py                        #
############################################################
Author          : Adi Zohar
Contributors    : Olaf Heimburger
Disclaimer      : This is not an official Oracle application, it is not supported by Oracle. It should NOT be used for utilization calculation purposes.
                : If you run into issues using this, please file an issue at https://github.com/oracle/oci-python-sdk/issues rather than contacting support
Machine         : 8c6d7f0e6237 (aarch64)
Python Version  : 3.8.13
Authentication  : Instance Principals with Delegation Token
Config File     : /etc/oci/config
Config Profile  : us-ashburn-1
Date/Time       : 2024-04-03 22:22:56
API Conn Timeout: 150
API Read Timeout: 20
Command Line    : -dt -paas
Showoci Version : 24.04.02
OCI SDK Version : 2.125.0
Running Threads : True with 8 threads

############################################################
#                 Load OCI data to Memory                  #
############################################################
Guide: '.' Compartment, '+' VCN, '-' Subnets, 'a' - auth/notfound

Identity... (Main)
--> Tenancy                         <-- (1)     - 00:00:02
--> Compartments                    <-- (17)    - 00:00:00

Section Elapsed Time 00:00:02

########################################
#         Region us-ashburn-1          #
########################################
Identity...
--> Availability Domains            <-- (3)     - 00:00:00

Network...
--> Network Security Groups         <-- (2)     - 00:00:02
--> Virtual Cloud Networks          <-- (8)     - 00:00:02
--> Subnets                         <-- (18)    - 00:00:02
Section Elapsed Time 00:00:02

Native, Data and AI ...
--> OAC Native                      <-- (0)     - 00:00:01
--> Open Search Cluster             <-- (0)     - 00:00:01
--> OIC Native                      <-- (0)     - 00:00:01
--> Visual Builder                  <-- (0)     - 00:00:01
--> Data Catalog                    <-- (0)     - 00:00:01
--> OCVS Native - VMWare            <-- (0)     - 00:00:01
--> DevOps Project                  <-- (0)     - 00:00:02
--> Data Science                    <-- (0)     - 00:00:01
--> Big Data Service                <-- (0)     - 00:00:01
--> Data Assistant                  <-- (0)     - 00:00:01
--> Data Integration                <-- (0)     - 00:00:01
--> Data Flow                       <-- (0)     - 00:00:02
--> OCE Native                      <-- (0)     - 00:00:06

**Comment by adizohar** [comment]
Please use 
```
-exclude GENAI
```
I added fixed for next week deployment to disable GENAI for now
Please close the ticket if this works
Thank you

**Comment by undamn89** [comment]
Thanks ! 

It worked fine

###############################################################################################
#               Completed Successfully at 2024-04-04 02:09:03 - Elapsed 00:04:55              #
###############################################################################################
juan_unda@cloudshell:showoci (us-ashburn-1)$ python3 showoci.py -dt -ani -exclude GENAI -csv CSV >rnpcsv.txt

juan_unda@cloudshell:showoci (us-ashburn-1)$

**Comment by undamn89** [comment]
Thanks it Worked 

###############################################################################################
#               Completed Successfully at 2024-04-04 02:09:03 - Elapsed 00:04:55              #
###############################################################################################
juan_unda@cloudshell:showoci (us-ashburn-1)$ python3 showoci.py -dt -ani -exclude GENAI -csv CSV >rnpcsv.txt

juan_unda@cloudshell:showoci (us-ashburn-1)$

**Comment by adizohar** [comment]
Thank you !
