### ISSUE TITLE
Report with properties of PDBs

### ISSUE THREAD

**Issue by carlos-delgadocastano** [oracle/oci-python-sdk#649]
Hi again :),

We need to have a report with all the properties of PDBs. I have been checking all the database reports generated but it seems that there is only one line per container database, and we cannot have this information that we don't have.

There is any way to obtain the properties of PDBs?

Thank you in advance,
Best Regards,

**Comment by adizohar** [comment]
I added csv for pdbs for 5/17 deployment

**Comment by carlos-delgadocastano** [comment]
Thank you!

I will update the script on 5/17 and I will get back to you.

Thank you!

**Comment by adizohar** [comment]
[showoci.zip](https://github.com/oracle/oci-python-sdk/files/15261445/showoci.zip)

Attached the new version which will push next week
Please check and close if working.

**Comment by carlos-delgadocastano** [comment]
It works! :)

Thank you very much!
