### ISSUE TITLE
list_* by tags

### ISSUE THREAD

**Issue by chelin** [oracle/oci-python-sdk#65]
Hi 

It is wonderful that one is able to tag objects such as compute, compartment, vcn etc. Though it is slightly asymmetrical that one have no way of listing objects having a set of tags.

Sort of having the ability to do:

```
    def computes(self, compartment_ocid, freeform_tags=None):
        return self.compute_client.list_instances(compartment_ocid, freeform_tags=freeform_tags).data
```

**Comment by chelin** [comment]
To add to motivations on top of symmetry in the API is to avoid a linear scan on the client side.

**Comment by arthall** [comment]
There is a new service coming which allows for resource searches by tag.  I'll update this ticket again with a link to the API documentation when it is available.

**Comment by chelin** [comment]
Fantastic!

**Comment by arthall** [comment]
Search service is now available.  The documentation is here: https://docs.cloud.oracle.com/iaas/Content/Search/Concepts/queryoverview.htm?tocpath=Services%7CSearch%7C_____0.  The Python SDK docs for the service are here: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/resource_search.html

I'm closing this issue now.  Please reopen it if this does not meet your needs.

**Comment by chelin** [comment]
This is great.. though I would like to add that the search API at least in the python doc rather opaque how to use. Would it be possible to add an example how to use ResourceSearchClient in combination with custom and freeform tags?

**Comment by arthall** [comment]
Here is the link to the example for Search service: https://github.com/oracle/oci-python-sdk/blob/master/examples/search_example.py
