### ISSUE TITLE
Optimizer client api givinig wrong data(list resource action api)

### ISSUE THREAD

**Issue by Gopichand-Heeddata** [oracle/oci-python-sdk#687]
Hi @adizohar  am facing one challenge regarding the optimizer-client (list_resoucce actions ) API providing extra data. I am providing the API that I have used. 

In the API response we are getting 8 records where as in the console we have only 7 records Could you please help me on this mismatch. 

![Screenshot from 2024-07-30 12-34-26](https://github.com/user-attachments/assets/7305ee78-4ffe-4709-9e81-4af4d6d31410)
![Screenshot from 2024-07-30 12-35-15](https://github.com/user-attachments/assets/29ed5e34-d196-4db1-bfe7-ef6a6f794aa1)
![Screenshot from 2024-07-30 12-35-38](https://github.com/user-attachments/assets/c9de942c-38f0-4c15-bc8f-bc3e8c9f7d57)

```
import oci
from oci.pagination import list_call_get_all_results

# Load configuration from the default OCI config file
config = oci.config.from_file()

# Initialize the OptimizerClient
optimizer_client = oci.optimizer.OptimizerClient(config)

# Get the compartment ID from the config file
compartment_id = config['tenancy']
compartment_id_in_subtree = True

# List recommendations
list_recommendations_response = list_call_get_all_results(
    optimizer_client.list_recommendations,
    compartment_id=compartment_id,
    compartment_id_in_subtree=compartment_id_in_subtree
)

# Iterate over each recommendation
for recommendation in list_recommendations_response.data:
    # Print recommendation details (optional)
    # print(recommendation)

    # List resource actions for the recommendation
    list_resource_actions_response = list_call_get_all_results(
        optimizer_client.list_resource_actions,
        recommendation_id=recommendation.id,
        compartment_id=compartment_id,
        compartment_id_in_subtree=compartment_id_in_subtree,
        sort_by='TIMECREATED',
    )

    # Iterate over each resource action
    for resource_action in list_resource_actions_response.data:
        print(resource_action)
        # Get detailed information about the resource action
        resource_action_response = optimizer_client.get_recommendation(recommendation_id=resource_action.recommendation_id)
        resource_action_details = resource_action_response.data
```

**Comment by Gopichand-Heeddata** [comment]
@adizohar Could you please help me on this issue.

**Comment by adizohar** [comment]
Please run the below in order to compare
It could be you have additional filter on the console
```
import oci

# Load configuration from the default OCI config file
config = oci.config.from_file()

# Initialize the OptimizerClient
optimizer_client = oci.optimizer.OptimizerClient(config)

# Get the compartment ID from the config file
compartment_id = config['tenancy']
compartment_id_in_subtree = True

# List recommendations
list_recommendations_response = oci.pagination.list_call_get_all_results(
    optimizer_client.list_recommendations,
    compartment_id=compartment_id,
    compartment_id_in_subtree=compartment_id_in_subtree
)

# Iterate over each recommendation
for recommendation in list_recommendations_response.data:
    # Print recommendation details (optional)
    if recommendation.name != "cost-management-compute-enable-monitoring-name":
        continue

    # List resource actions for the recommendation
    list_resource_actions_response = oci.pagination.list_call_get_all_results(
        optimizer_client.list_resource_actions,
        recommendation_id=recommendation.id,
        compartment_id=compartment_id,
        compartment_id_in_subtree=compartment_id_in_subtree,
        sort_by='TIMECREATED',
    )

    # Iterate over each resource action
    for resource_action in list_resource_actions_response.data:
        rext = resource_action.extended_metadata
        print(rext['resourceOwningTenancyName'] + " - " + rext['region'] + " - " + resource_action.resource_id)
```

**Comment by Gopichand-Heeddata** [comment]
@adizohar After running this code also am still getting extra resources  **cost-management-compute-enable-monitoring-name**. My OCI console only has 7 but API fetches 8 records. 
![image000](https://github.com/user-attachments/assets/cc267b6e-ed9f-4612-9477-b37e2544183b)

API response:
  -ap-hyderabad-1 - ocid1.instance.oc1.ap-hyderabad-1.anuhsljr7zexxxxxxxxxxxxxqb4ksdfjx7czo4icya
  -ap-hyderabad-1 - ocid1.instance.oc1.ap-hyderabad-1.anuhsljrypiaxxxxxxxxxxxxxxe3f2rcckyeixmse5ua2ba
 - ap-mumbai-1 - ocid1.instance.oc1.ap-mumbai-1.anrg6ljr7qgdflycobmxxxxxxxxxxxxxxh333qmu7vpn7vq
 - ap-hyderabad-1 - ocid1.instance.oc1.ap-hyderabad-1.anuhsljr7qxxxxxxxxxxxxxgdflshrv7npzi4d6li7pq
 - ap-mumbai-1 - ocid1.instance.oc1.ap-mumbai-1.anrg6ljr7qgdflycxxxxxxxxxxxxxxxxx4q4wzi37tunv2bcggq
 - ap-mumbai-1 - ocid1.instance.oc1.ap-mumbai-1.anrg6ljr7qgdflyxxxxxxxxxxxxxxcumym35nzurcysq
 - ap-mumbai-1 - ocid1.instance.oc1.ap-mumbai-1.anrg6ljr7qgdflyxxxxxxxxxxxau477rdye2hfi6pasrq
 - ap-mumbai-1 - ocid1.instance.oc1.ap-mumbai-1.anrg6ljr7qgdflycxxxxxxxxxxytvqxlul7rwd6btzxja

**Comment by adizohar** [comment]
Gopi

I don’t see any issue with OCI SDK
This issue should go to Oracle support

Please open Oracle support ticket and the support will investigate and will redirect it to the console team.

Because it is not OCI SDK issue please kindly close this issue

Thank you

**Comment by Gopichand-Heeddata** [comment]
@adizohar I have one question :

1. is there any time span between the cloud console and API?

**Comment by adizohar** [comment]
No, The console uses the same APIs

**Comment by Gopichand-Heeddata** [comment]
Thank you adizohar

**Comment by Gopichand-Heeddata** [comment]
Thankyou for your support @adizohar
