### ISSUE TITLE
Upgrade to use python package cryptography 43

### ISSUE THREAD

**Issue by fmorriso** [oracle/oci-python-sdk#692]
Please upgrade your python SDK to use python package _cryptography_ >= 43.

Every time I upgrade packages for my Python project, I have to back-level cryptography to < 43 as shown below:

`pip install cryptography<43`

I would be nice if you would upgrade oci to use cryptography>=43 to alleviate me having to constantly downgrade to < 43.

**Comment by sodul** [comment]
The upper limits are counter productive for requirements, they should only be set if there are known compatibility issues.

**Comment by fmorriso** [comment]
sodul: when using some db packages like pymongo or sqlite, OCI chokes if cryptography >= 43.

**Comment by sodul** [comment]
Interesting, so the bug is that there are actual compatibility issues between OCI, pymongo and newer cryptography. Is this documented/tracked?

I noticed #681 but there is no mention of the problem there.

**Comment by gshamgar-r7** [comment]
This is a must due to this security issue: https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-7886970

**Comment by jyotisaini** [comment]
Thanks all for reporting this. My team is currently working on upgrading cryptography pkg and i'll update here once we have it updated and released.

**Comment by vmsilvamolina** [comment]
Hey @jyotisaini! I sent a PR about that a few weeks ago: https://github.com/oracle/oci-python-sdk/pull/699. Can you approve it? Thanks!

**Comment by jyotisaini** [comment]
Hi @vmsilvamolina thanks for the PR. This has been fixed internally and will be released on 01/8.

**Comment by vmsilvamolina** [comment]
Was it a typo? Could it be October 8? Thank you for your response!

**Comment by jyotisaini** [comment]
Sorry about that. I meant 10/8.

**Comment by bhagwatvyas** [comment]
This has been fixed in [v2.135.2](https://github.com/oracle/oci-python-sdk/releases/tag/v2.135.2)
