### ISSUE TITLE
Upgrade cryptography Version to >=43.0.1 Due to High Severity Security Vulnerability

### ISSUE THREAD

**Issue by gshamgar-r7** [oracle/oci-python-sdk#700]
High severity security vulnerability found: https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-7886970

**Comment by bhagwatvyas** [comment]
This has been fixed in [v2.135.2](https://github.com/oracle/oci-python-sdk/releases/tag/v2.135.2)
