### ISSUE TITLE
what method should be used to list Base Database DB Systems

### ISSUE THREAD

**Issue by kk-hiraskar** [oracle/oci-python-sdk#706]
I tried using "oci.database.DatabaseClient.list_db_systems" method, but this is not listing base DBs.
tried to see if any other methods, but not getting any kindly suggest.

I can view from web console
![image](https://github.com/user-attachments/assets/cddc7ef1-f7b9-4ae3-bba4-fac8bb829858)

**Comment by adizohar** [comment]
Can you please share your full code ? did you pass the compartment ? how do you authenticate ? which region are you authenticate to ? 
You can try to run the showoci which use same methods - https://github.com/oracle/oci-python-sdk/tree/master/examples/showoci

**Comment by kk-hiraskar** [comment]
Thanks @adizohar 
different account used for web console, and API.. might be permission/policy issue..
API is returning 404, NotAuthorized..

getting right permissions to recheck.
Thanks for the quick response.
