### ISSUE TITLE
 Python is_stateless returning False or None for Seclist

### ISSUE THREAD

**Issue by ToyotaGitRepo** [oracle/oci-python-sdk#75]
We are using oci sdk --version  2.4.32

When trying to read the security rules that are in a seclist – we seem to be hitting something odd…
When looking at “rule.is_stateless” – we expect “True” or “False” per the documentation.  However, we seem to be getting “None” or False.  Below are the functions we’re using.
 
ingressRules = vnc.get_security_list(seclist_id).data.ingress_security_rules
egressRules = vnc.get_security_list(seclist_id).data.egress_security_rules

for seclist_id in response.data.security_list_ids:
                     ingressRules = vnc.get_security_list(seclist_id).data.ingress_security_rules
                      for rule in ingressRules:
                                .
                                ..
                                .. ....
                               print (rule.is_stateless)        ----  returns false/none     {expecting true/false}

**Comment by arthall** [comment]
Thank you for filing the issue.

Does this happen for all security rules?  I can replicate the behavior with the default security list.  I'm not seeing it when I create security lists using the code in this example: https://github.com/oracle/oci-python-sdk/blob/master/examples/container_engine.py#L255.  When I get the rules for those security lists, the is_stateless attributes are True/False.  When I get the rules for the default security list I do see None values.  

I'm checking with service team to get more information.

**Comment by ToyotaGitRepo** [comment]
I saw this issues with  both default and other security lists 

 

Regards

**Comment by koenigdavidmj** [comment]
My name is David Koenig and I am a member of the service team that owns this API. We've rolled out an update that fixes this problem. No change to your API client version is necessary.
