### ISSUE TITLE
Can we add the option to use a proxy when making the request to OCI?

### ISSUE THREAD

**Issue by szhongren** [oracle/oci-python-sdk#81]
I'm in the Oracle VPN, and I can't hit the servers without setting the proxy in my env that I am running my process in.

Here's my traceback:
```
oci._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='objectstorage.us-phoenix-1.oraclecloud.com', port=443): Max retries exceeded with url: taken_out_because_this_is_public (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f094d392c88>: Failed to establish a new connection: [Errno 113] No route to host',))
```

Should I just make a PR? Or is there another solution to this you already know of?

**Comment by adizohar** [comment]
You can specify proxy to each client module: 
computeClient.base_client.session.proxies={ 'https': 'proxy_address:port' }
objectClient.base_client.session.proxies={ 'https': 'proxy_address:port' }

**Comment by szhongren** [comment]
That worked, thank you.

**Comment by arthall** [comment]
There is additional information concerning using a proxy server here: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/sdk-with-proxy.html

The page also details how to use a proxy with basic authentication.
