### ISSUE TITLE
list_boot_volumes in oci.core.BlockstorageClient insists on needing an availability_domain in addition to compartment_id

### ISSUE THREAD

**Issue by ramnathnayakpr** [oracle/oci-python-sdk#85]
`list_boot_volumes(availability_domain, compartment_id, **kwargs)` in `oci.core.BlockstorageClient` insists on needing a `availability_domain` in addition to `compartment_id`.

This is inconsistent with the other `list_*` functions which only need `compartment_id`. Please could this be fixed

**Comment by adizohar** [comment]
Ramnath, I will ask the service team, I also think it should be changed
When you press on the console block storage, you don't need to choose the AD

**Comment by arthall** [comment]
Reopening the ticket to give the service team an opportunity to comment.

**Comment by ramnathnayakpr** [comment]
The availability_domain should be optional, as this now forces us to look up and pass in the AD for each call.
 
The list_* functions for all other services do not require the AD to be passed in, for e.g.:
```
list_vcns(compartment)
list_cpes(compartment)
list_drgs(compartment)
list_ip_sec_connections(compartment)
list_cross_connects(compartment)
list_virtual_circuits(compartment)
list_load_balancers(compartment)
list_instances(compartment)
list_instance_configurations(compartment)
list_instance_pools(compartment)
list_images(compartment)
list_volumes(compartment)
list_volume_backups(compartment)
list_boot_volume_backups(compartment)
list_db_systems(compartment)
list_clusters(compartment)
list_node_pools(compartment)
list_zones(compartment)
list_service_gateways(compartment_id)
list_remote_peering_connections(compartment_id)
list_nat_gateways(compartment_id)
```
…..and many more
 
Similar inconsistency also exists in 
```
oci.file_storage.FileStorageClient:
list_file_systems(compartment_id, availability_domain, **kwargs)
list_mount_targets(compartment_id, availability_domain, **kwargs)
```

**Comment by maxverun-oci** [comment]
This is by design. We enforce AD as a required parameter so the results can be properly sorted. All other APIs will adhere to this design eventually. The reason we haven't started enforcing that for earlier APIs which currently have AD as optional is because it would be a breaking change to do so. This will be planned to take effect in phases.
