### ISSUE TITLE
~/.oci/config sample

### ISSUE THREAD

**Issue by mocai834809147** [oracle/oci-python-sdk#86]
Could you please give me a sample file of ~/.oci/config file?

**Comment by adizohar** [comment]
[DEFAULT]
user=ocid1.user.oc1..aaaaaaaancwnxcj6tygim3dgxxxxxxx
fingerprint=64:d0:44:4d:dd:85:1e:48:92:xxxxxx
key_file=~/.oci/oci_api_key.pem
tenancy=ocid1.tenancy.oc1..aaaaaaaab7glwqooiwt6fjdh7ua5hk7slrxxxxx
region=us-ashburn-1

**Comment by jodoglevy** [comment]
You can also find an example config file in our docs [here](https://docs.cloud.oracle.com/iaas/Content/API/Concepts/sdkconfig.htm)
