### ISSUE TITLE
Unable to validate_config when supplying "private_key_content" in dict

### ISSUE THREAD

**Issue by mm0** [oracle/oci-python-sdk#88]
According to the code for https://github.com/oracle/oci-python-sdk/blob/master/src/oci/identity/identity_client.py

It should be possible to create a config dict and supply the `private_key_content` within this dictionary.

However, when doing so, it is still required to provide a `key_file` parameter.  It cannot be omitted (gives error: `oci.exceptions.InvalidConfig: {'key_file': 'missing'}`, and when both are supplied, the validation continues to try to load the key_file and thus creates a problem if the file doesn't exist or contain the key file.  

config = {
    "user": user_ocid,
    "key_file": key_file,
    "fingerprint": calc_fingerprint(key_file),
    "tenancy": testrunner.tenancy,
    "private_key_content": "-------BEGIN RSA....",
    "region": testrunner.region
}

from oci.config import validate_config
validate_config(config)

**Comment by ramnathnayakpr** [comment]
The availability_domain should be optional, as this now forces us to look up and pass in the AD for each call.
 
The list_* functions for all other services do not require the AD to be passed in, for e.g.:
```
list_vcns(compartment)
list_cpes(compartment)
list_drgs(compartment)
list_ip_sec_connections(compartment)
list_cross_connects(compartment)
list_virtual_circuits(compartment)
list_load_balancers(compartment)
list_instances(compartment)
list_instance_configurations(compartment)
list_instance_pools(compartment)
list_images(compartment)
list_volumes(compartment)
list_volume_backups(compartment)
list_boot_volume_backups(compartment)
list_db_systems(compartment)
list_clusters(compartment)
list_node_pools(compartment)
list_zones(compartment)
list_service_gateways(compartment_id)
list_remote_peering_connections(compartment_id)
list_nat_gateways(compartment_id)
```
…..and many more
 
Similar inconsistency also exists in 
```
oci.file_storage.FileStorageClient:
list_file_systems(compartment_id, availability_domain, **kwargs)
list_mount_targets(compartment_id, availability_domain, **kwargs)
```

**Comment by arthall** [comment]
Try "key_content" instead of "private_key_content".  The identity client uses config.get("key_content") to set the private_key_content in the signer.  This happens here: https://github.com/oracle/oci-python-sdk/blob/master/src/oci/identity/identity_client.py#L69.

oci.config.validate_config() uses "key_content" as the fall back for "key_file".  As long as one of them is defined the config will be accepted as valid, as long as the other requirements are met.  

Note: You cannot use "key_content" in you config file.  Storing your private key in the config file is not supported.

**Comment by arthall** [comment]
@mm0 Have you had a chance to change "private_key_content" to "key_content" and verify that it works?  I'll close this issue after the next release on Thursday, unless you still have concerns.

**Comment by mm0** [comment]
@arthall Thank you for the clarification, it does appear as though using "key_content" instead of "private_key_content" works successfully.  Thank you.
