### ISSUE TITLE
objects size,time_created,md5 are showing null when using rest webserivce api

### ISSUE THREAD

**Issue by vipmike007** [oracle/oci-python-sdk#90]
Hi, Pls check following code 
    namespace = object_storage_client.get_namespace().data
    print object_storage_client.list_objects(namespace, buckets[2].name).data.objects

Here is my output:
[{
  "md5": null,
  "name": "1487902706.jpg",
  "size": null,
  "time_created": null
}, {
  "md5": null,
  "name": "48132889.jpg",
  "size": null,
  "time_created": null
}]

We can see md5, size ,time created are all none. I believe it is a bug in this api call. can you help to check this.

**Comment by jodoglevy** [comment]
This is the right answer, closing this one.

**Comment by vipmike007** [comment]
Excuse me , reopen this issue due to follow reason
 https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/object_storage/client/oci.object_storage.ObjectStorageClient.html#oci.object_storage.ObjectStorageClient.list_objects is the fun I used 


Returns: | A Response object with data of type ListObjects
-- | --

From the doc We can see "

Returns: | A Response object with data of type ListObjects
-- | --

But in the output . the value of md5/size/time_created are NULL
"

Here is the output ,

**Comment by jodoglevy** [comment]
@vipmike007 did you try passing the fields parameter with the names of the fields you want returned, as @arthall suggested?

Please see https://github.com/oracle/oci-python-sdk/issues/78 for more info.

**Comment by vipmike007** [comment]
Sorry for that ,Just tried pass fields to the func ,then the issue is gone.
Thanks for your effforts!
