### ISSUE TITLE
On Ubuntu 16.04, pip3 install fails due to no openssl

### ISSUE THREAD

**Issue by monktastic** [oracle/oci-python-sdk#93]
This is not an issue with the SDK, of course, but it might be a useful tip for others running into this problem.

```
$ pip3 install oci
...
Building wheels for collected packages: cryptography
  Running setup.py bdist_wheel for cryptography ... error
...
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/_openssl.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/_openssl.o -Wconversion -Wno-error=sign-conversion
  build/temp.linux-x86_64-3.5/_openssl.c:498:30: fatal error: openssl/opensslv.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
...
```

Just need to install openssl (`sudo apt-get update && sudo apt-get install libssl-dev`).

**Comment by monktastic** [comment]
Ah, I now see that the oci command line depends on libssl-dev, and since most users would install that first, they won't run into this.

**Comment by arthall** [comment]
@monktastic, Thank you for tip. 

In case anyone is looking for additional information concerning the oci package and openssl here are some links to the the documentation.

The cryptography package requires openssl and there is a note in the prerequisites section of the oci package documentation stating that the prerequisites for cryptography need to be met.  The prerequisites for the oci package are here:  https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/installation.html#prerequisites

There is also a section on verifying and installing openssl here: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/installation.html#verify-openssl-version
