### ISSUE TITLE
KmsManagementClient - MissingEndpointForNonRegionalServiceClientError exception

### ISSUE THREAD

**Issue by adizohar** [oracle/oci-python-sdk#95]
Hi SDK group

I would like to list the vaults and then the keys per vault.
Issue to initiate KmsManagementClient

kms_keys = oci.key_management.KmsManagementClient(config)
    Throw exception - MissingEndpointForNonRegionalServiceClientError('An endpoint must be provided for a non-regional service client')
    Altough the documentation mentioned service_endpoint is optional

Adding service_endpoint from the vault: 
    kms_keys = oci.key_management.KmsManagementClient(config,service_endpoint=vault.management_endpoint)
    But the function list_keys does not have option to filter by vault_id therefore, there is some issue here !
    keySummary has vault_id which I need to filter inside a loop

Please advise:
1. Why service_endpoint is required when specify optional in documentation
2. How do I fetch the key if I have key_id but not vault (need to use KmsManagementClient and get_key but don't have service_endpoint) ? 
3. Why cannot filter vault_id in list keys

**Comment by adizohar** [comment]
Thank you, appreciate it

**Comment by Matt-Mcl** [comment]
@adizohar Can we re-open this issue as multiple vaults can now be provisioned per tenancy per region?

**Comment by adizohar** [comment]
Hi Matt, I will need to check if the search option can be used and if not I will reopen

**Comment by adizohar** [comment]
Matt, you are right, There is no option to get the vault id from key_id
We must have an option, I will open this ticket and create as well internal ticket for the KMS team

**Comment by Matt-Mcl** [comment]
Also in addition to this - A bucket only exposes the kms_key_id and not the version of the key it is using. Is there any way to find out if a bucket is using a specific version of a key as the API itself does not seem to expose this.

**Comment by jodoglevy** [comment]
Looks like Obj Storage API is returning only the KMS key id, not the key's version nor the key's vault. I'll ask Obj Storage team to take a look

**Comment by adizohar** [comment]
Hi Matt,
Bucket and other services may use different versions of the keys
If you created new version the new objects will use the new version, and the old used the previous versions
I will check with the services if they can specify all the key versions that being used
I opened ticket related to finding vault id from key id in order to get the end point, I will update once we have a solution
For your info

**Comment by adizohar** [comment]
Below is a solution how to fetch vault id from the kms_key_id

```
import oci

config_file="~/.oci/config"
config = oci.config.from_file(config_file,"DEFAULT")

# Get Regions
identity_client = oci.identity.IdentityClient(config)
regions = identity_client.list_regions().data

# KMS
kms_id = "ocid1.key.oc1.iad.bbpqq6iuaacuu.abuwcljrjzehgml2wpiaahmmtnijvqj5tmohs2bsq6waxxxxx"
kms_namespace = kms_id.split(".")[4]
kms_region_key = kms_id.split(".")[3]
kms_region = [x for x in regions if x.key.lower() == kms_region_key][0]
kms_region_name = kms_region.name
kms_management_endpoint = "https://" + kms_namespace + "-management.kms." + kms_region_name + ".oraclecloud.com"

# fetch the key
kms_management_client = oci.key_management.KmsManagementClient(config, kms_management_endpoint)
kms_key = kms_management_client.get_key(kms_id).data
print (kms_key)

# output
{
  "compartment_id": "ocid1.compartment.oc1..aaaaaaaa24b3mfwu6aulib33oan3eqicwm4az65cog7o7xxxxxx",
  "current_key_version": "ocid1.keyversion.oc1.iad.bbpqq6iuaacuu.asqjl4ehwfyaa.abuwcljrerlnng7bxx3cn336f543373zfr4pxxxxx",
  "defined_tags": {},
  "display_name": "adi_master_key",
  "freeform_tags": {},
  "id": "ocid1.key.oc1.iad.bbpqq6iuaacuu.abuwcljrjzehgml2wpiaahmmtnijvqj5tmohs2bsq6walqxxxxx",
  "is_primary": true,
  "key_shape": {
    "algorithm": "AES",
    "curve_id": null,
    "length": 16
  },
  "lifecycle_state": "ENABLED",
  "protection_mode": "HSM",
  "replica_details": null,
  "restored_from_key_id": null,
  "time_created": "2020-07-10T14:28:40.167000+00:00",
  "time_of_deletion": "2020-10-24T01:30:00+00:00",
  "vault_id": "ocid1.vault.oc1.iad.bbpqq6iuaacuu.abuwcljrqlei3dlmyxm43fttfiiod4ttulbc4ifoi73kxxxxx"
}
```

**Comment by Matt-Mcl** [comment]
Thanks for the responses! 

I wasn't aware that new objects automatically used the new key version if the key has been rotated. It would however still be nice to have a way to check that all objects in a bucket are using the new key.

That code is very helpful, thank you!
