### ISSUE TITLE
Issue passing a list of strings into the object- UpdatePolicyDetails for statements

### ISSUE THREAD

**Issue by jauyzed** [oracle/oci-python-sdk#96]
Hello,

I am trying to update a policy with following statement

Here is the code snippet:
`statements_to_be_added = ['ALLOW group EXAMPLE TO MANAGE users IN TENANCY']`
`template_stmt = []`

#doing this convert to string in case
`for stmt in statements_to_be_added:`
	`stmt_to_be_added = str(stmt)`
	`template_stmt.append(stmt_to_be_added)`

#outside for loop
`identity.update_policy(policyid, oci.identity.models.UpdatePolicyDetails(statements=template_stmt))`

`oci.exceptions.ServiceError: {'opc-request-id': '43B518D6EB8E4D37A179A28984E78BF8/DC99C55F6291A49EC9C8199380EC472C/F0D0F0D3E738366C5C7492ECA3C9F981', 'code': 'InvalidParameter', 'message': "'syntax error starting with <<EOF>>'@'line 1, char 73' \n", 'status': 400}`

Based on the documentation, it is list[str]. 

The type for `template_stmt` above is <class 'list'>

Please let me know how to resolve this. Thanks

**Comment by arthall** [comment]
What do you get if you assign the results from UpdatePolicyDetails to a variable before calling update_policy?  Like the snippet below.

```
policy_details = oci.identity.models.UpdatePolicyDetails(statements=template_stmt)
print(policy_details)
```

The exception you are getting looks like it is coming back from the service, which makes me think that the issue isn't passing a list of strings into UpdatePolicyDetails.  

statements_to_be_added is already a list of strings.  If you don't see anything wrong with policy_details when you print it and are still getting an error, you can skip the loop and do this.

```
policy_details = oci.identity.models.UpdatePolicyDetails(statements=statements_to_add))
```
and use that policy_details when calling update_policy.

**Comment by jauyzed** [comment]
The print worked flawlessly as you suggested. I think the issue was actually when calling `update_policy` on identity object.  

`policy_details = oci.identity.models.UpdatePolicyDetails(statements=statements_to_add))`
`print(policy_details)`
`identity.update_policy(policyid, policy_details)` #policyid is a string var

It is still complaining the same error:

`oci.exceptions.ServiceError: {'opc-request-id': '8E23F8431FAD4EDA86A7FDA768144A2B/6BDF2E34600832D720EA02CF8134023A/F9FE1ADB1B48ADC72E02D22B11E34734', 'code': 'InvalidParameter', 'message': "'syntax error starting with <<EOF>>'@'line 1, char 73' \n", 'status': 400}`

**Comment by arthall** [comment]
This leads me to think there is something off in the policy statements that are being sent.  If there is no confidential information, would you be willing to post the results from printing policy_details?

Based on the examples you have provided, I expect it to look like this:
```
{
  "defined_tags": null,
  "description": null,
  "freeform_tags": null,
  "statements": [
    "ALLOW group EXAMPLE TO MANAGE users IN TENANCY"
  ],
  "version_date": null
} 
```
When I use that as my policy_details when calling update_policy I get an exception, but it's because I don't have a group named EXAMPLE.

```
'message': 'The group EXAMPLE specified in the policy statement does not exist under current compartment hierarchy.\n'
```

**Comment by jauyzed** [comment]
resolved
